/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1227870592
 */

/*
 *  XFaceMaker 4.0  Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' create_pb  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void create_pb(Widget w)
#else
void create_pb(w)
Widget w;
#endif
{
/*## begin user  ##*/
   Arg args[10];
    Cardinal num_args;
    Widget w_c,p;
    XmString xmstring;
    static int i;
    char buf[30];
    sprintf(buf,"child_%d",i++);

    #ifdef CCODE
    extern Widget FmCreatePBnodeC();
    #endif

    p = XtParent(w);
    xmstring = XmStringCreateSimple(buf);

    num_args = 0;
    XtSetArg(args[num_args], XmNlabelString, xmstring); num_args++;
    XtSetArg(args[num_args], XmNnodeState, XmAlwaysOpen); num_args++;
    XtSetArg(args[num_args], XmNparentNode, w); num_args++;

    #ifdef CCODE
    w_c=FmCreatePBnodeC(buf, p, args, num_args);
    #else
    w_c=FmLoadCreateGroup(buf,"PBnodeC.fm",p,args, num_args);
    #endif

    XmStringFree(xmstring);

    XtManageChild(w_c);

/*## end user  ##*/
}
/*## end `function' create_pb  ##*/
