/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1227536822
 */

/*
 *  XFaceMaker 3.5 Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

#include "ColorApp.h"

#include <stdio.h>
#include <X11/StringDefs.h>
#include <unistd.h>

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' Color  ##*/
Widget Parent;
/*## end `active_values' Color  ##*/

extern Widget Parent;
static Widget Items[1024];
static int    NumItems;

#if NeedFunctionPrototypes
Widget CreateItem (Widget parent, char *color)
#else
Widget CreateItem (parent, color)
     Widget  parent;
     char   *color;
#endif
{
  Arg          arg[10];
  int          nargs;
  XrmValue     from, to;
  Pixel        background;
  XmString     label;
  Widget       item;
#ifdef CCODE
  extern Widget FmCreateColorItem();
#endif
	
  from.addr = color;
  from.size = strlen(color)+1;
  to.addr = 0;
  to.size = 0;
  XtConvert(parent, XtRString, &from, XtRPixel, &to);
  if (! to.addr)
  {
    printf("Cannot convert color %s to pixel.\n", color);
    return(0);
  }
  background = *(Pixel *)to.addr;
	
  nargs = 0;
  XtSetArg(arg[nargs], XtNbackground, background); nargs++;
  XtSetArg(arg[nargs], "labelString", FmCreateXmString(color)); nargs++;
#ifdef CCODE
  item = FmCreateColorItem(color, parent, arg, nargs);
#else
  item = FmLoadCreateGroup(color, "ColorItem.fm", parent, arg, nargs);
#endif
  if(!item)
  {
    printf("Cannot create item %s.\n", color);
    return(0);
  }
  FmShowWidget(item);
  Items[NumItems++] = item;
  return(item);
}

void Clear (void)
{
  int i;
	
  for(i = 0; i < NumItems; i++)
    XtDestroyWidget(Items[i]);
}

#define INCR 128

#define MAXIMUM 65535

typedef struct color
{
  int    name_offset;
  XColor xcolor;
} color;

static color *colors      = NULL;
static char  *names       = NULL;
static color *colorp      = NULL;
static char  *namep       = NULL;
static int    ncolors     = 0;
static int    colors_size = 0;
static int    names_size  = 0;

#define expand(buf, size, ptr, incr, type) while(((char *)ptr) + incr > ((char *)buf) + size) {\
					int offset = ((char *)ptr) - ((char *)buf);\
					size += INCR;\
					buf = (type *)XtRealloc((char*)buf, size);\
					ptr = (type *)(((char *)buf) + offset);\
				     }

static color *lookup_color(XColor *xcolor)
{
  int i;
	
  register red   = xcolor->red;
  register green = xcolor->green;
  register blue  = xcolor->blue;
  register color *c;

  for (i = 0, c = colors; i < ncolors; i++, c++)
    if (c->xcolor.red   == red   &&
        c->xcolor.green == green &&
        c->xcolor.blue  == blue)
      return(c);
  return(0);
}

static void add_color(char *colorname, Pixel p, int r, int g, int b)
{
  XColor xcolor;
  int len;
	
  xcolor.pixel = p;
  xcolor.red = r;
  xcolor.green = g;
  xcolor.blue = b;
	
  if(lookup_color(&xcolor))
    return;
	
  len = strlen(colorname)+1;
	
  expand(colors, colors_size, colorp, sizeof(color), color)
	expand(names, names_size, namep, len, char)
	
	memcpy(&xcolor, &colorp->xcolor, sizeof(XColor));
  colorp->name_offset = namep - names;
  strcpy(namep, colorname);
	
  namep += len;
  colorp ++;
	
  ncolors++;
}

static void ListColors(Widget widget, Colormap colormap)
{
  int r, g, b;
  char colorname[50], line[256];
  FILE *rgb;
  char *rgbtxt;
  XColor xcolor, raf;
  char buffer[1024];
  char *s;
  char *f1 = "/usr/lib/X11/rgb.txt";
  char *f2 = "/usr/openwin/lib/X11/rgb.txt";
	
  /*  Si c'est deja fait, tant mieux.
   */
  if(colors)
    return;
	
  add_color("white", WhitePixelOfScreen(XtScreen(widget)), MAXIMUM, MAXIMUM, MAXIMUM);
  /*	
    if(DefaultDepthOfScreen(XtScreen(widget)) == 1)
    return;
  */
  if(access(f1, R_OK) == 0) { /* default /usr/lib/X11/rgb.txt is OK */
    rgbtxt = XtNewString(f1);
  }
  else if(access(f2, R_OK) == 0) { /* try /usr/openwin/lib/rgb.txt */
    rgbtxt = XtNewString(f2);
  } else {
    XtWarning("Cannot access rgb.txt file");
    return;
  }
		
	
  if (!(rgb = fopen(rgbtxt, "r"))) {
    printf("Cannot open %s", rgbtxt);
    return;
  }
	
	
  while ((s = fgets (buffer, 1024, rgb)) != 0) {
    if ( buffer[0] == '!') 
      continue;
    if ( 4 == sscanf(buffer, "%d %d %d %[^\n]\n", &r, &g, &b, colorname)){
		
      /*  On saute tous le synonymes du genre "light blue",
       *  pour ne prendre que la forme LightBlue.
       */
      if(strchr(colorname, ' '))
        continue;
		
      if(XAllocNamedColor(XtDisplay(widget), colormap, colorname, &xcolor, &raf)){
        add_color(colorname, xcolor.pixel, xcolor.red, xcolor.green, xcolor.blue);
      }
    }
  }

  /*
   *printf("%d bytes allocated for %d colors\n", colors_size + names_size, ncolors);
   */
  fclose(rgb);

  return;
}

void foo(Widget toplevel)
{
  int i;

  FmGetActiveValue(0, "Parent");
  if(! Parent)
  {
    printf("Parent not found.\n");
    exit (1);
  }
	
  ListColors(toplevel, DefaultColormapOfScreen(XtScreen(toplevel)));
	
  for(i = 0; i < ncolors; i++)
    CreateItem(Parent, &names[colors[i].name_offset]);
}

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
