/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1227870810
 */

/*
 *  XFaceMaker 3.5 Application Functions Definitions.
 */

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' Edit  ##*/
String CurrentFile;
/*## end `active_values' Edit  ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' LoadFile  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
String LoadFile(String filename)
#else
String LoadFile(filename)
String filename;
#endif
{
/*## begin user  ##*/
	int fd;
	struct stat st_buf;
	char *text;
	int size;
	int n;
	
	if((fd = open(filename, O_RDONLY, 0)) < 0){
		perror("open for reading");
		return(0);
	}
	if(fstat(fd, &st_buf) == -1){
		perror("fstat");
		close(fd);
		return(0);
	}
	size = st_buf.st_size;
	text = XtMalloc(size+1);
	n = read(fd, text, size);
	close(fd);
	if(n < 0){
		perror("read");
		return(0);
	}
	text[n] = 0;
	return(text);
/*## end user  ##*/
}
/*## end `function' LoadFile  ##*/
/*## begin `function' SaveFile  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
int SaveFile(String filename, String text)
#else
int SaveFile(filename, text)
String filename;
String text;
#endif
{
/*## begin user  ##*/
	int fd;
	int size;
	int n;
	
	if((fd = open(filename, O_WRONLY|O_CREAT|O_TRUNC, 0644)) < 0){
		perror("open for writing");
		return(0);
	}
	size = strlen(text);
	n = write(fd, text, size);
	close(fd);
	if(n < 0){
		perror("write");
		return(0);
	}
	return(1);
/*## end user  ##*/
}
/*## end `function' SaveFile  ##*/
