/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1034262734
 */

#include <stdio.h>

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#if !defined(XtSpecificationRelease) || XtSpecificationRelease <= 4
#include <X11/Quarks.h>
#else
extern	XrmQuark  XtQBool;
extern	XrmQuark  XtQBoolean;
extern	XrmQuark  XtQColor;
extern	XrmQuark  XtQCursor;
extern	XrmQuark  XtQDimension;
extern	XrmQuark  XtQDisplay;
extern	XrmQuark  XtQFile;
extern	XrmQuark  XtQFont;
extern	XrmQuark  XtQFontStruct;
extern	XrmQuark  XtQInt;
extern	XrmQuark  XtQPixel;
extern	XrmQuark  XtQPixmap;
extern	XrmQuark  XtQPointer;
extern  XrmQuark  XtQPosition;
extern  XrmQuark  XtQShort;
extern	XrmQuark  XtQString;
extern  XrmQuark  XtQUnsignedChar;
extern	XrmQuark  XtQWindow;
#endif
#include <X11/Shell.h>

#include <Xm/Xm.h>

#define	true	True
#define	false	False

#undef  XtMapWidget
#undef  XtUnmapWidget
#define XtMapWidget(widget)     XMapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))
#define XtUnmapWidget(widget)   XUnmapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))

#ifndef _EDITAPP_H_
#include "EditApp.h"
#define _EDITAPP_H_
#endif /* _EDITAPP_H_ */

#include <Fm.h>

#include <Xm/CascadeB.h>
#include <Xm/CascadeBG.h>
#include <Xm/MainW.h>
#include <Xm/PushB.h>
#include <Xm/PushBG.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Separator.h>
#include <Xm/SeparatoG.h>
#include <Xm/Text.h>

#ifndef _FACE_NO_FLOATS

static float _vtof_(
#if NeedFunctionPrototypes
XtArgVal v)
#else
v)
XtArgVal v;
#endif
{	float f;
	f = *(float*)&v;
	return(f);
}

static XtArgVal _ftov_(
#if NeedFunctionPrototypes
float f)
#else
f)
float f;
#endif
{	float _f = f;
	XtArgVal v;
	*(float*)&v = _f;
	return(v);
}

#endif


extern XrmQuark XtQNone;
extern XrmQuark XtQAny;
extern XrmQuark XtQFloat;
extern XrmQuark XtQWidget;
extern XrmQuark XtQCallback;

typedef struct {
	XtArgVal value;
	XrmQuark type;
} FaceVariable;

#ifdef __cplusplus
extern "C" {
#endif
extern Widget FaceGetWidget(
#if NeedFunctionPrototypes
Widget ref, int level, String names);
#else
);
#endif
extern XtArgVal FaceGetResource(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetResource(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceGetProperty(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetProperty(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern void FmNewAv(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, Widget widget, Widget* group);
#else
);
#endif
extern void FmCreateValue(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, String type, int storage, int scope, int immediate, int automatic, int genfun, Widget widget, Widget* group, Arg* avs, Cardinal num_avs);
#else
);
#endif
extern int FaceReadValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceFetchValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceInitValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceInitValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceWriteValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceChangeValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern String FmInternationalize(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern String FmNewIString(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern void FmFreeAllIStrings(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern int FmResetDatabase(
#if NeedFunctionPrototypes
Display* display);
#else
);
#endif
extern int FmLoadStringDataBase(
#if NeedFunctionPrototypes
Widget w, char** str, char* name);
#else
);
#endif
extern Widget FmToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern Widget FmAppShell(
#if NeedFunctionPrototypes
Widget w);
#else
);
#endif
extern Widget FmRealizeToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
#ifdef __cplusplus
}
#endif
#define WIDGET_TABLE ((Widget*)client_data)


/* XFM get script of av CurrentFile test */
static void CurrentFile_WIDGET_0_get(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;

	_r0.value = (XtArgVal) (! (XtArgVal)*((XtArgVal*)call_data));
	if((XtArgVal)_r0.value == 0){
		_r1.value = (XtArgVal) FmEqualString((String)*((XtArgVal*)call_data), (String)"");
	} else _r1.value = 1;
	_r2.value = (XtArgVal) ((XtArgVal)_r0.value || (XtArgVal)_r1.value);
	if(_r2.value){
		*(XtArgVal*)call_data = (XtArgVal) "unnamed";	/* XFM 2 */
	}
}


/* XFM set script of av CurrentFile test */
static void CurrentFile_WIDGET_0_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable buf;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;
	Arg _arg;

	buf.type = XtQString;
	_r0.value = (XtArgVal) (! (XtArgVal)*((XtArgVal*)call_data));
	if((XtArgVal)_r0.value == 0){
		_r1.value = (XtArgVal) FmEqualString((String)*((XtArgVal*)call_data), (String)"");
	} else _r1.value = 1;
	_r2.value = (XtArgVal) ((XtArgVal)_r0.value || (XtArgVal)_r1.value);
	if(_r2.value){
		_r0.value = (XtArgVal) "Edit: unnamed";	/* XFM 2 */
		XtSetArg(_arg, "title", _r0.value);
		XtSetValues((Widget)WIDGET_TABLE[0], &_arg, 1);
		return;	/* XFM 3 */
	}
	_r0.value = (XtArgVal) XtMalloc((int)512);	/* XFM 5 */
	_r0.type = XtQString;
	buf.value = (XtArgVal) _r0.value;
	sprintf((String)buf.value, (String)"Edit: %s", *((XtArgVal*)call_data));	/* XFM 6 */
	_r0.value = (XtArgVal) buf.value;	/* XFM 7 */
	XtSetArg(_arg, "title", _r0.value);
	XtSetValues((Widget)WIDGET_TABLE[0], &_arg, 1);
}


/* XFM get script of av text test.mainwin.text_scroll.text */
static void text_WIDGET_14_get(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	Arg _arg;
	FaceVariable _r0;

	XtSetArg(_arg, "value", &_r0.value);
	XtGetValues((Widget)WIDGET_TABLE[14], &_arg, 1);
	_r0.type = XtQString;
	*(XtArgVal*)call_data = (XtArgVal) _r0.value;
}


/* XFM set script of av text test.mainwin.text_scroll.text */
static void text_WIDGET_14_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	Arg _arg;

	_r0.value = (XtArgVal) *((XtArgVal*)call_data);
	XtSetArg(_arg, "value", _r0.value);
	XtSetValues((Widget)WIDGET_TABLE[14], &_arg, 1);
	FaceWriteValue((Widget)widget, (Widget)WIDGET_TABLE[14], "textModified", (XtArgVal)0, (XrmQuark)XtQInt);	/* XFM 2 */
}


/* XFM resource activateCallback test.mainwin.menubar.popup_filePulldown.filePulldown.open */
static void WIDGET_4_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable filename;
	static FaceVariable text;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;

	filename.type = XtQString;
	text.type = XtQString;
	_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*fsbox");	/* XFM 3 */
	FaceReadValue((Widget)widget, (Widget)WIDGET_TABLE[0], "CurrentFile", &_r1);
	_r2.value = (XtArgVal) FmCallValue((Widget)_r0.value, (String)"GetFileName", (int)2, _r1.value, (String)"*");
	_r2.type = XtQAny;
	filename.value = (XtArgVal) _r2.value;
	_r0.value = (XtArgVal) (! (XtArgVal)filename.value);	/* XFM 4 */
	if(_r0.value){
		return;	/* XFM 5 */
	}
	_r0.value = (XtArgVal) LoadFile((String)filename.value);	/* XFM 6 */
	_r0.type = XtQString;
	text.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) (! (XtArgVal)text.value);	/* XFM 7 */
	if(_r0.value){
		_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*alert_box");	/* XFM 8 */
		FmCallValue((Widget)_r0.value, (String)"Error", (int)1, (String)"Cannot load file");
		XtFree((String)text.value);	/* XFM 9 */
	} else {
		FaceWriteValue((Widget)widget, (Widget)WIDGET_TABLE[14], "text", (XtArgVal)text.value, (XrmQuark)text.type);	/* XFM 11 */
		XtFree((String)text.value);	/* XFM 12 */
		FaceWriteValue((Widget)widget, (Widget)WIDGET_TABLE[0], "CurrentFile", (XtArgVal)filename.value, (XrmQuark)filename.type);	/* XFM 13 */
	}
}


/* XFM resource activateCallback test.mainwin.menubar.popup_filePulldown.filePulldown.save */
static void WIDGET_5_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable filename;
	static FaceVariable text;
	static FaceVariable status;
	FaceVariable _r0;

	filename.type = XtQString;
	text.type = XtQString;
	status.type = XtQInt;
	FaceReadValue((Widget)widget, (Widget)WIDGET_TABLE[0], "CurrentFile", &_r0);	/* XFM 3 */
	filename.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) (! (XtArgVal)filename.value);	/* XFM 5 */
	if(_r0.value){
		return;	/* XFM 6 */
	}
	FaceReadValue((Widget)widget, (Widget)WIDGET_TABLE[14], "text", &_r0);	/* XFM 8 */
	text.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) SaveFile((String)filename.value, (String)text.value);	/* XFM 9 */
	_r0.type = XtQInt;
	status.value = (XtArgVal) _r0.value;
	XtFree((String)text.value);	/* XFM 10 */
	_r0.value = (XtArgVal) ((XtArgVal)status.value == (XtArgVal)0);	/* XFM 11 */
	if(_r0.value){
		_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*alert_box");	/* XFM 12 */
		FmCallValue((Widget)_r0.value, (String)"Error", (int)1, (String)"Cannot save file");
	}
}


/* XFM resource activateCallback test.mainwin.menubar.popup_filePulldown.filePulldown.saveas */
static void WIDGET_6_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable filename;
	static FaceVariable text;
	static FaceVariable status;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;

	filename.type = XtQString;
	text.type = XtQString;
	status.type = XtQInt;
	_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*fsbox");	/* XFM 3 */
	FaceReadValue((Widget)widget, (Widget)WIDGET_TABLE[0], "CurrentFile", &_r1);
	_r2.value = (XtArgVal) FmCallValue((Widget)_r0.value, (String)"GetFileName", (int)2, _r1.value, (String)"*");
	_r2.type = XtQAny;
	filename.value = (XtArgVal) _r2.value;
	_r0.value = (XtArgVal) (! (XtArgVal)filename.value);	/* XFM 4 */
	if(_r0.value){
		return;	/* XFM 5 */
	}
	FaceReadValue((Widget)widget, (Widget)WIDGET_TABLE[14], "text", &_r0);	/* XFM 7 */
	text.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) SaveFile((String)filename.value, (String)text.value);	/* XFM 8 */
	_r0.type = XtQInt;
	status.value = (XtArgVal) _r0.value;
	XtFree((String)text.value);	/* XFM 9 */
	_r0.value = (XtArgVal) ((XtArgVal)status.value == (XtArgVal)0);	/* XFM 10 */
	if(_r0.value){
		_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*alert_box");	/* XFM 11 */
		FmCallValue((Widget)_r0.value, (String)"Error", (int)1, (String)"Cannot save file");
	} else {
		FaceWriteValue((Widget)widget, (Widget)WIDGET_TABLE[0], "CurrentFile", (XtArgVal)filename.value, (XrmQuark)filename.type);	/* XFM 13 */
	}
}


/* XFM resource activateCallback test.mainwin.menubar.popup_filePulldown.filePulldown.quit */
static void WIDGET_8_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable sure;
	FaceVariable _r0;
	FaceVariable _r1;

	FaceReadValue((Widget)widget, (Widget)WIDGET_TABLE[14], "textModified", &_r0);
	if(_r0.value){
		_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*alert_box");	/* XFM 2 */
		_r1.value = (XtArgVal) FmCallValue((Widget)_r0.value, (String)"Question", (int)1, (String)"Text has been modified\nQuit anyway ?");
		_r1.type = XtQAny;
		sure.value = (XtArgVal) _r1.value;
		sure.type = _r1.type;
		_r0.value = (XtArgVal) (! (XtArgVal)sure.value);	/* XFM 4 */
		if(_r0.value){
			return;	/* XFM 5 */
		}
	}
	exit((int)0);	/* XFM 7 */
}


/* XFM resource activateCallback test.mainwin.menubar.popup_filePulldown.helpPulldown.ondemo */
static void WIDGET_11_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable help_text;
	FaceVariable _r0;

	help_text.type = XtQString;
	_r0.value = (XtArgVal) LoadFile((String)"README");	/* XFM 2 */
	_r0.type = XtQString;
	help_text.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) (! (XtArgVal)help_text.value);	/* XFM 3 */
	if(_r0.value){
		_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*alert_box");	/* XFM 4 */
		FmCallValue((Widget)_r0.value, (String)"Error", (int)1, (String)"Cannot load help file");
		return;	/* XFM 5 */
	}
	_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*help_box");	/* XFM 7 */
	FmCallValue((Widget)_r0.value, (String)"Help", (int)2, (String)"This Demo", (String)help_text.value);
	XtFree((String)help_text.value);	/* XFM 8 */
}

#ifndef True
#define True 1
#endif

/* XFM resource valueChangedCallback test.mainwin.text_scroll.text */
static void WIDGET_14_valueChangedCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FaceWriteValue((Widget)widget, (Widget)WIDGET_TABLE[14], "textModified", (XtArgVal)True, (XrmQuark)XtQBoolean);
}


/* XFM create proc test.mainwin.menubar */
static void WIDGET_2_createCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	Arg _arg;

	_r0.value = (XtArgVal) WIDGET_TABLE[12];
	XtSetArg(_arg, "menuHelpWidget", _r0.value);
	XtSetValues((Widget)WIDGET_TABLE[2], &_arg, 1);
}

/* XFM private */
#undef WIDGET_TABLE

static void FreeWidgetTable(
#if NeedFunctionPrototypes
Widget w, XtPointer table, XtPointer unused)
#else
w, table, unused)
Widget w;
XtPointer table;
XtPointer unused;
#endif
{
	XtFree((char*)table);
}

Widget
_FmCreateEdit(
#if NeedFunctionPrototypes
String name, Widget parent, Widget * toplevels, Cardinal num_toplevels, Widget ** widgets_return, Cardinal * num_widgets_return, Arg* avs, Cardinal num_avs, Arg* user_args, Cardinal num_user_args, Boolean manage_top_objects, XtPointer _this)
#else
name, parent, toplevels, num_toplevels, widgets_return, num_widgets_return, avs, num_avs, user_args, num_user_args, manage_top_objects, _this)
String name;
Widget parent;
Widget * toplevels;
Cardinal num_toplevels;
Widget ** widgets_return;
Cardinal * num_widgets_return;
Arg* avs;
Cardinal num_avs;
Arg* user_args;
Cardinal num_user_args;
Boolean manage_top_objects;
XtPointer _this;
#endif
{
	Arg args[107];
	Cardinal nargs, i;
	XrmValue from, to;
	String app_name, app_class;
	Widget *widget_table = (Widget*)XtMalloc(15*sizeof(Widget));
#define WIDGET_TABLE widget_table

	if(widgets_return) *widgets_return = widget_table;
	if(num_widgets_return) *num_widgets_return = 15;

	/* XFM create test */
	if(toplevels && 0 < num_toplevels && toplevels[0]){
		WIDGET_TABLE[0] = toplevels[0];
	} else {
	nargs = 0;
	XtSetArg(args[nargs], "x", 348); nargs++;
	XtSetArg(args[nargs], "y", 37); nargs++;
	XtSetArg(args[nargs], "width", 433); nargs++;
	XtSetArg(args[nargs], "height", 292); nargs++;
	XtSetArg(args[nargs], "title", "Edit"); nargs++;
	for(i = 0; i < num_user_args; i++){
		args[nargs].name = user_args[i].name;
		args[nargs].value = user_args[i].value;
		nargs++;
	}
	XtGetApplicationNameAndClass(XtDisplay(parent), &app_name, &app_class);
	WIDGET_TABLE[0] = XtAppCreateShell(app_name, app_class, applicationShellWidgetClass, XtDisplay(parent), args, nargs);
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[0], WIDGET_TABLE, &arg, 1);
	}
	FmCreateValue("CurrentFile", (XtCallbackProc)CurrentFile_WIDGET_0_get, (XtCallbackProc)CurrentFile_WIDGET_0_set, "String", 0, 0, 0, 1, 0, (Widget)WIDGET_TABLE[0], WIDGET_TABLE, avs, num_avs);

	/* XFM create test.mainwin */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 433); nargs++;
	XtSetArg(args[nargs], "height", 292); nargs++;
	WIDGET_TABLE[1] = XtCreateManagedWidget("mainwin", xmMainWindowWidgetClass, WIDGET_TABLE[0], args, nargs);

	/* XFM create test.mainwin.menubar */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 433); nargs++;
	XtSetArg(args[nargs], "height", 31); nargs++;
	WIDGET_TABLE[2] = XmCreateMenuBar(WIDGET_TABLE[1], "menubar", args, nargs);

	/* XFM create test.mainwin.menubar.filePulldown */
	nargs = 0;
	WIDGET_TABLE[3] = XmCreatePulldownMenu(WIDGET_TABLE[2], "filePulldown", args, nargs);

	/* XFM create test.mainwin.menubar.filePulldown.open */
	from.addr = "Open...";
	from.size = 8;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[4] = XtCreateManagedWidget("open", xmPushButtonGadgetClass, WIDGET_TABLE[3], args, nargs);
	XtAddCallback(WIDGET_TABLE[4], "activateCallback", (XtCallbackProc)WIDGET_4_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create test.mainwin.menubar.filePulldown.save */
	from.addr = "Save";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[5] = XtCreateManagedWidget("save", xmPushButtonGadgetClass, WIDGET_TABLE[3], args, nargs);
	XtAddCallback(WIDGET_TABLE[5], "activateCallback", (XtCallbackProc)WIDGET_5_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create test.mainwin.menubar.filePulldown.saveas */
	from.addr = "Save As...";
	from.size = 11;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[6] = XtCreateManagedWidget("saveas", xmPushButtonGadgetClass, WIDGET_TABLE[3], args, nargs);
	XtAddCallback(WIDGET_TABLE[6], "activateCallback", (XtCallbackProc)WIDGET_6_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create test.mainwin.menubar.filePulldown.sep */
	nargs = 0;
	WIDGET_TABLE[7] = XtCreateManagedWidget("sep", xmSeparatorGadgetClass, WIDGET_TABLE[3], args, nargs);

	/* XFM create test.mainwin.menubar.filePulldown.quit */
	from.addr = "Quit";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[8] = XtCreateManagedWidget("quit", xmPushButtonGadgetClass, WIDGET_TABLE[3], args, nargs);
	XtAddCallback(WIDGET_TABLE[8], "activateCallback", (XtCallbackProc)WIDGET_8_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create test.mainwin.menubar.file */
	from.addr = "File";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[2], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "subMenuId", WIDGET_TABLE[3]); nargs++;
	WIDGET_TABLE[9] = XtCreateManagedWidget("file", xmCascadeButtonGadgetClass, WIDGET_TABLE[2], args, nargs);

	/* XFM create test.mainwin.menubar.helpPulldown */
	nargs = 0;
	WIDGET_TABLE[10] = XmCreatePulldownMenu(WIDGET_TABLE[2], "helpPulldown", args, nargs);

	/* XFM create test.mainwin.menubar.helpPulldown.ondemo */
	from.addr = "On This Demo...";
	from.size = 16;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[10], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[11] = XtCreateManagedWidget("ondemo", xmPushButtonGadgetClass, WIDGET_TABLE[10], args, nargs);
	XtAddCallback(WIDGET_TABLE[11], "activateCallback", (XtCallbackProc)WIDGET_11_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create test.mainwin.menubar.help */
	from.addr = "Help";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[2], XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "subMenuId", WIDGET_TABLE[10]); nargs++;
	WIDGET_TABLE[12] = XtCreateManagedWidget("help", xmCascadeButtonGadgetClass, WIDGET_TABLE[2], args, nargs);
	XtManageChild(WIDGET_TABLE[2]);
	WIDGET_2_createCallback(WIDGET_TABLE[2], (XtPointer)WIDGET_TABLE, 0);

	/* XFM create test.mainwin.text_scroll */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 31); nargs++;
	XtSetArg(args[nargs], "width", 433); nargs++;
	XtSetArg(args[nargs], "height", 261); nargs++;
	WIDGET_TABLE[13] = XtCreateManagedWidget("text_scroll", xmScrolledWindowWidgetClass, WIDGET_TABLE[1], args, nargs);

	/* XFM create test.mainwin.text_scroll.text */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 414); nargs++;
	XtSetArg(args[nargs], "height", 242); nargs++;
	XtSetArg(args[nargs], "scrollVertical", True); nargs++;
	XtSetArg(args[nargs], "editMode", XmMULTI_LINE_EDIT); nargs++;
	WIDGET_TABLE[14] = XtCreateManagedWidget("text", xmTextWidgetClass, WIDGET_TABLE[13], args, nargs);
	XtAddCallback(WIDGET_TABLE[14], "valueChangedCallback", (XtCallbackProc)WIDGET_14_valueChangedCallback, (XtPointer)WIDGET_TABLE);
	FmCreateValue("text", (XtCallbackProc)text_WIDGET_14_get, (XtCallbackProc)text_WIDGET_14_set, "String", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[14], WIDGET_TABLE, avs, num_avs);
	FmCreateValue("textModified", (XtCallbackProc)0, (XtCallbackProc)0, "Int", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[14], WIDGET_TABLE, avs, num_avs);

	/* XFM private */

	if(manage_top_objects){
	XtRealizeWidget(WIDGET_TABLE[0]);
	}
	XtAddCallback(WIDGET_TABLE[0], XmNdestroyCallback, (XtCallbackProc)FreeWidgetTable, (XtPointer)WIDGET_TABLE);

	return(WIDGET_TABLE[0]);
}

Widget
FmCreateEdit(
#if NeedFunctionPrototypes
String name, Widget parent, Arg* args, Cardinal num_args)
#else
name, parent, args, num_args)
String name;
Widget parent;
Arg* args;
Cardinal num_args;
#endif
{
	return(_FmCreateEdit(name, parent, 0, 0, 0, 0, 0, 0, args, num_args, True, 0));
}
