
// -*- C++ -*-
// $Id: Version.h 95588 2012-03-07 08:07:23Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define TAO_MAJOR_VERSION 2
#define TAO_MINOR_VERSION 1
#define TAO_BETA_VERSION 0
#define TAO_VERSION "2.1.0"
