/*
 *  C file generated by XFaceMaker Version 4.2.
 *  Do not remove this comment.
 *  Timestamp:           1161186184
 */

/*
 *  XFaceMaker 4.0  Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin user ##*/
void OnlyNum(Widget w, XtPointer client, XtPointer call)
{
    XmTextVerifyCallbackStruct *verify_struct =
        (XmTextVerifyCallbackStruct *) call;

    if (verify_struct->text->ptr)
        if (!isdigit(*verify_struct->text->ptr))
            verify_struct->doit = False;
}
/*## end user ##*/
