include ../../config/Xfm-demos.rules

# Makefile used to build the xfm examples

	      PR1 = buttonbox
         PROGRAMS = $(PR1)
  GENERATED_FILES = $(PR1).c $(PR1)App.h $(PR1)Main.c

.PHONY: $(PROGRAMS)

all:: $(PROGRAMS)

$(PR1):    $(PR1)Make $(PR1).fm $(PR1)App.c $(PR1)App.h $(PR1)Main.c $(PR1).exe $(PR1).editor
