/*******************************************************************************
 * \file           EMdiDEFINES.H
 * Application  :  EMMA
 * Rôle         :  Définition des constantes du service di
 *
 * \author  Fichier généré automatiquement à partir de EMdiCONSTANTES.decl
 * \date  Génération :  27/05/2025 a 12:52:49
 *******************************************************************************
 */


#ifndef __EMDIDEFINES_H
#define __EMDIDEFINES_H


// ------------------ Definition des constantes du projet ---------------


const int   C_EM_NB_CRITERE = 64 ;   // nombre de CRITERE d ABONNEMENT dans une demande d abonnement client

const int   C_EM_NB_CHAMP_CRIT = 50 ;   // nombre de champ dans un critere d abonnement

const int   C_EM_NB_FIELDID = 20 ;   // nombre de champs modifiables pour les infos transaction dans un plan de vol

const int   C_EM_NB_REFIDCT = 3 ;   // nbre de blocs REFIDCT dans une Route d un plan de vol

const int   C_EM_NB_RTETR = 40 ;   // nbre de blocs route dans un plan de vol

const int   C_EM_NB_EQCST = 5 ;   // nombre de champs de la liste des equipements de radionavigation: 8.33, RVSM, RNAV, UHF, MODE S

const int   C_EM_NB_SECLIST = 50 ;   // nbre de blocs route dans un plan de vol

const int   C_EM_NB_TRANSLIST = 9 ;   // nbre de blocs transactions autorisees dans un plan de vol

const int   C_EM_NB_FPLIST = 50 ;   // nbre de blocs info plan de vol dans dans une reponse multiple


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMdiDEFINES.H
//------------------------------------------------------------------------------

