/*******************************************************************************
 * \file           EMdiTYPES.H
 * Application  :  EMMA
 * Rôle         :  Définition des types énumérés du service di
 *
 * \author  Fichier généré automatiquement à partir de EMdiENUMERES.decl
 * \date  Génération :  27/05/2025 a 12:52:49
 *******************************************************************************
 */


#ifndef __EMDITYPES_H
#define __EMDITYPES_H


// ------------------ Definition des types enumeres du projet ---------------


// Type de CHAMP CRITERE
enum EM_TYPE_CHAMP {
  C_EM_CHAMP_INCONNU = -1,
  C_EM_CHAMP_INT = 0,
  C_EM_CHAMP_CHAR,
  C_EM_CHAMP_STRING,
  C_EM_NB_CHAMP
};


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMdiTYPES.H
//------------------------------------------------------------------------------

