//*****************************************************************************
/**
 * \file        EMfd.H
 * Application  EMMA
 * \author      Erwan Demairy
 *
 * Déclare le type utilisé pour les descripteurs de fichiers utilisés par EMMA.
 */
//*****************************************************************************
#ifndef EMFD_H
#define EMFD_H
 
namespace emma 
{
   typedef int EMfd;
} 

#endif /* EMFD_H */
