/*******************************************************************************
 * \file           EMmassifDEFINES.H
 * Application  :  EMMA
 * Rôle         :  Définition des constantes du service massif
 *
 * \author  Fichier généré automatiquement à partir de EMmassifCONSTANTES.decl
 * \date  Génération :  27/05/2025 a 12:52:52
 *******************************************************************************
 */


#ifndef __EMMASSIFDEFINES_H
#define __EMMASSIFDEFINES_H


// ------------------ Definition des constantes du projet ---------------


const int   C_EM_NB_AERONEF = 1 ;   // 

const int   C_EM_NB_REGULATION = 1 ;   // 

const int   C_EM_MASSIF_NBMAX_IMPRIMANTE = 3 ;   // 

const int   C_EM_MASSIF_NBMAX_DESTINATAIRE = 3 ;   // 

const int   C_EM_MASSIF_NB_DEST = 21 ;   // 


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMmassifDEFINES.H
//------------------------------------------------------------------------------

