/*******************************************************************************
 * \file           EMolgaDEFINES.H
 * Application  :  EMMA
 * Rôle         :  Définition des constantes du service olga
 *
 * \author  Fichier généré automatiquement à partir de EMolgaCONSTANTES.decl
 * \date  Génération :  27/05/2025 a 12:52:52
 *******************************************************************************
 */


#ifndef __EMOLGADEFINES_H
#define __EMOLGADEFINES_H


// ------------------ Definition des constantes du projet ---------------


const int   C_EM_MAX_POS = 20 ;   // Nombre de positions dans les configurations operationnelles

const int   C_EM_MAX_SECT = 40 ;   // Nombre de secteurs par position


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMolgaDEFINES.H
//------------------------------------------------------------------------------

