/*******************************************************************************
 * \file           EMpisteDEFINES.H
 * Application  :  EMMA
 * Rôle         :  Définition des constantes du service piste
 *
 * \author  Fichier généré automatiquement à partir de EMpisteCONSTANTES.decl
 * \date  Génération :  27/05/2025 a 12:52:53
 *******************************************************************************
 */


#ifndef __EMPISTEDEFINES_H
#define __EMPISTEDEFINES_H


// ------------------ Definition des constantes du projet ---------------


const int   C_EM_PISTE_NBMAX_QFU = 8 ;   // nombre de blocs QFU dans une liste QFU


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMpisteDEFINES.H
//------------------------------------------------------------------------------

