/*******************************************************************************
 * \file           EMplnDEFINES.H
 * Application  :  EMMA
 * Rôle         :  Définition des constantes du service pln
 *
 * \author  Fichier généré automatiquement à partir de EMplnCONSTANTES.decl
 * \date  Génération :  27/05/2025 a 12:52:53
 *******************************************************************************
 */


#ifndef __EMPLNDEFINES_H
#define __EMPLNDEFINES_H


// ------------------ Definition des constantes du projet ---------------


const int   C_EM_PLN_NBMAX_QFU = 8 ;   // nombre de blocs QFU dans une liste QFU

const int   C_EM_NB_LIGNE_TXT = 3 ;   // strip STIN


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMplnDEFINES.H
//------------------------------------------------------------------------------

