/*******************************************************************************
 * \file           EMspyServeurVersClientImplementation.H
 * Application  :  EMMA
 * Rôle         :  Declarations des classes de reception cote client
 * Version(s)   :  v3.0.0  
 *
 * \author  Fichier généré automatiquement à partir de EMspy.act
 * \date  Génération :  27/05/2025 a 12:52:54
 *******************************************************************************
 */


#ifndef __EMspyServeurVersClientImplementation_H
#define __EMspyServeurVersClientImplementation_H


//-------------------- Includes ----------------------------------------

#include "EMspyServeurVersClientS.H"


//-------------------- Declaration de la classe en v3.0.0 ------------

class POA_EMspy_v3_0_0_ServeurVersClientImplementation :
    public POA_emma_corba::EMspy_v3_0_0_ServeurVersClient {


public:

    //---------- Operations declarees dans le fichier IDL --------------


    //----------------------------------------------------------------------------
    /// Opérations métiers. Cf. DDI du service spy pour plus de détails.
    //----------------------------------------------------------------------------

    //----------------------------------------------------------------------------
    /// Fin des opérations métiers.
    //----------------------------------------------------------------------------

};

#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMspyServeurVersClientImplementation.H
//------------------------------------------------------------------------------

