//*****************************************************************************
/*! \file        EMstatus.H
 *  Application  EMMA
 *  \author      Erwan Demairy
 *
 *  Déclare la structure EMstatut, qui définit les codes retournés
 *  par les fonctions d'EMMA. Pour être compatible avec EMMA1, on autorise 
 *  l'appel direct à EMstatus et EMstatut.
 */
//*****************************************************************************
#ifndef __EMSTATUS_H
#define __EMSTATUS_H

#include "EMstatut"
using namespace emma;

#endif /* __EMSTATUS_H */
