/*******************************************************************************
 * \file           EMsvc_testTYPES.H
 * Application  :  EMMA
 * Rôle         :  Définition des types énumérés du service svc_test
 *
 * \author  Fichier généré automatiquement à partir de EMsvc_testENUMERES.decl
 * \date  Génération :  27/05/2025 a 12:52:50
 *******************************************************************************
 */


#ifndef __EMSVC_TESTTYPES_H
#define __EMSVC_TESTTYPES_H


// ------------------ Definition des types enumeres du projet ---------------


// Type de m_enum
enum EM_TYPE_SVC_ENUM {
  C_EM_SVC_ENUM_INCONNU = -1,
  C_EM_SVC_ENUM_A = 0,
  C_EM_SVC_ENUM_B,
  C_EM_SVC_ENUM_C,
  C_EM_SVC_ENUM_D = 0,
  C_EM_SVC_ENUM_E,
  C_EM_SVC_ENUM_F,
  C_EM_SVC_ENUM_G = 0,
  C_EM_SVC_ENUM_H,
  C_EM_SVC_ENUM_I,
  C_EM_SVC_ENUM_J = 0,
  C_EM_SVC_ENUM_K,
  C_EM_SVC_ENUM_L,
  C_EM_SVC_ENUM_M = 0,
  C_EM_SVC_ENUM_N,
  C_EM_SVC_ENUM_O,
  C_EM_SVC_ENUM_P = 0,
  C_EM_SVC_ENUM_Q,
  C_EM_SVC_ENUM_S,
  C_EM_SVC_ENUM_T = 0,
  C_EM_SVC_ENUM_U,
  C_EM_SVC_ENUM_V,
  C_EM_SVC_ENUM_W = 0,
  C_EM_SVC_ENUM_X,
  C_EM_SVC_ENUM_Y,
  C_EM_SVC_ENUM_Z = 0,
  C_EM_NB_SVC_ENUM
};


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMsvc_testTYPES.H
//------------------------------------------------------------------------------

