/*******************************************************************************
 * \file           EMsvc_testDEFINES.H
 * Application  :  EMMA
 * Rôle         :  Définition des constantes du service svc_test
 *
 * \author  Fichier généré automatiquement à partir de EMsvc_testCONSTANTES.decl
 * \date  Génération :  27/05/2025 a 12:52:50
 *******************************************************************************
 */


#ifndef __EMSVC_TESTDEFINES_H
#define __EMSVC_TESTDEFINES_H


// ------------------ Definition des constantes du projet ---------------


const int   C_EM_MAX_SVC_CHAINE = 100 ;   // 

const int   C_EM_MAX_SVC_INT = 100 ;   // 

const int   C_EM_MAX_SVC_LONG = 100 ;   // 

const int   C_EM_MAX_SVC_FLOAT = 100 ;   // 

const int   C_EM_MAX_SVC_DOUBLE = 100 ;   // 

const int   C_EM_MAX_SVC_OBJET_CHAINE = 100 ;   // 

const int   C_EM_MAX_SVC_OBJET_BASE = 100 ;   // 

const int   C_EM_MAX_SVC_OBJET_COMPOSE = 100 ;   // 


#endif


//------------------------------------------------------------------------------
//  Fin du fichier EMsvc_testDEFINES.H
//------------------------------------------------------------------------------

