/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1227869592
 */

/*
 *  XFaceMaker 4.0  Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' new_child  ##*/
/*## begin user  ##*/
void create_node(Widget p, Widget p_n, String name, int state);
/*## end user  ##*/
#if NeedFunctionPrototypes
void new_child(Widget wp, Widget w)
#else
void new_child(wp, w)
Widget wp;
Widget w;
#endif
{
/*## begin user  ##*/
static int i;
char buf[30];
sprintf(buf,"child %d",i++);
create_node(wp,w,buf,XmAlwaysOpen);
/*## end user  ##*/
}
/*## end `function' new_child  ##*/
/*## begin `function' create_node  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void create_node(Widget p, Widget p_n, String name, int state)
#else
void create_node(p, p_n, name, state)
Widget p;
Widget p_n;
String name;
int state;
#endif
{
/*## begin user  ##*/
    Arg args[10];
    Cardinal num_args;
    Widget w;
    XmString xmstring;

    #ifdef CCODE
    extern Widget FmCreatePBnodeC();
    #endif
    if(name)
    {
    	xmstring = XmStringCreateSimple(name);

	num_args = 0;
	XtSetArg(args[num_args], XmNlabelString, xmstring); num_args++;
	XtSetArg(args[num_args], XmNnodeState, state); num_args++;
	XtSetArg(args[num_args], XmNparentNode, p_n); num_args++;

	#ifdef CCODE
	w=FmCreatePBnodeC(name, p, args, num_args);
	#else
	w=FmLoadCreateGroup(name,"PBnodeC.fm",p,args, num_args);
	#endif

	XmStringFree(xmstring);

	XtManageChild(w);

    }

/*## end user  ##*/
}
/*## end `function' create_node  ##*/
