/*
 *  C file generated by XFaceMaker Version 5.3.
 *  Do not remove this comment.
 *  Timestamp:           1240411165
 */

/*
 *  XFaceMaker 4.0  Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin user ##*/
#include <Xm/XpmP.h>
#include <Xm/MultiList.h>
#include "extlist.h"
#include <pixmaps/crab.xpm>
#include <pixmaps/stopsign.xpm>
#include <pixmaps/porsche.xpm>
#include <pixmaps/clown.xbm>

/*## end user  ##*/

/*## begin user ##*/
static int  NothingSort(short , XmMultiListRowInfo *, XmMultiListRowInfo *);
static int  ExtListAlphaSort(short , XmMultiListRowInfo *, XmMultiListRowInfo *);
static int  ExtListIntSort(short , XmMultiListRowInfo *, XmMultiListRowInfo *);
static int  ExtListDoubleSort(short , XmMultiListRowInfo *, XmMultiListRowInfo *);

Pixmap porsche_pix;
Pixmap stopsign_pix;
Pixmap crab_pix;
Pixmap clown_pix;

PlayerData players[] = {
/*   Name      AB   R    H   RBI   AVG   HR */
{ PPORSCHE, "Mo Vaughn", 159, 30,  55, 33, 346, 11 },
{ PCLOWN, "Tim Naehring", 133, 25, 43, 27, 323, 6 },
{ PSTOP, "Scott Cooper", 139, 24, 43, 30, 309, 9 },
{ PCLOWN, "John Valentin", 78, 12, 22, 11, 282, 2 },
{ PSTOP, "Carlos Rodriguez", 39, 2, 11, 4, 282, 1},
{ PCLOWN, "Otis Nixon", 148, 23, 41, 13, 277, 0},
{ PSTOP, "Scott Fletcher", 80, 13, 21, 8, 263, 2},
{ PCLOWN, "Andre Dawson", 134, 19, 33, 27, 246, 10},
{ PPORSCHE, "Damon Berryhill", 72, 4, 17, 6, 236, 1},
{ PPORSCHE, "Billy Hatcher", 139, 23, 32, 15, 230, 1},
{ PCLOWN, "Mike Greenwell", 151, 31, 35, 25, 232, 7},
{ PSTOP, "Rich Rowland", 28, 1, 6, 6, 214, 1},
{ PCLOWN, "Lee Tinsley", 34, 10, 7, 2, 206, 0},
{ PPORSCHE, "Dave Valle", 72, 5, 11, 4, 153, 1},
};
/*## end user ##*/

/************************************************************
 *
 *  Sort routines.
 *
 ************************************************************/
static int
NothingSort( short column, XmMultiListRowInfo *row1, XmMultiListRowInfo *row2 )
{
  return(0);
}

/*      Function Name: ExtListAlphaSort
 *      Description:   A sorting employee to sort things is alphabetic order.
 *          This function only compares the first segment in the XmStrings.
 *          If multi-segment XmStrings were expected, you could loop thru
 *             both strings, extracting all segments and then do the compare
 *      Arguments:     column - column to sort on.
 *                     row1, row2 - two rows to check.
 *      Returns:       -1, 0, or 1 depending upon whether 1 is less than,
 *                                 equal to, or greater than 2.
 */
static int
ExtListAlphaSort( short column, XmMultiListRowInfo *row1, XmMultiListRowInfo *row2 )
{
  String str1 = FmGetString(row1->values[column]);
  String str2 = FmGetString(row2->values[column]);

  int ret_val;

  if (str1 == NULL)
    ret_val = -1; /* str1 is empty. it must be less than str2 */
  else if (str2 == NULL)
    ret_val = 1; /* str2 is empty. str1 must be greater */
  else
    ret_val = strcmp(str1, str2);

  /* clean up */
  if (str1 != NULL) XtFree((XtPointer) str1);
  if (str2 != NULL) XtFree((XtPointer) str2);

  return (ret_val);
}

/*      Function Name: ExtListIntSort
 *      Description:   A sorting function to sort things in numerical order.
 *      Arguments:     column - column to sort on.
 *                     row1, row2 - two rows to check.
 *      Returns:       -1, 0, or 1 depending upon whether 1 is less than,
 *                                 equal to, or greater than 2.
 */
static int
ExtListIntSort( short column,  XmMultiListRowInfo *row1, XmMultiListRowInfo *row2 )
{
  String str1 = FmGetString(row1->values[column]);
  String str2 = FmGetString(row2->values[column]);
  int ret_val;

  if (str1 == NULL)
    ret_val = -1; /* str1 is empty. it must be less than str2 */
  else if (str2 == NULL)
    ret_val = 1; /* str2 is empty. str1 must be greater */
  else
    {
      int i1, i2;

      i1 = atoi(str1);
      i2 = atoi(str2);

      if (i1 == i2)
	ret_val = 0;
      else if (i1 < i2)
	ret_val = -1;
      else
	ret_val = 1;
    };

  /* clean up */
  if (str1 != NULL) XtFree((XtPointer) str1);
  if (str2 != NULL) XtFree((XtPointer) str2);

  return(ret_val);
}

/*      Function Name: ExtListIntSort
 *      Description:   A sorting function to sort things in numerical order.
 *      Arguments:     column - column to sort on.
 *                     row1, row2 - two rows to check.
 *      Returns:       -1, 0, or 1 depending upon whether 1 is less than,
 *                                 equal to, or greater than 2.
 */
static int
ExtListDoubleSort( short column, XmMultiListRowInfo *row1, XmMultiListRowInfo *row2 )
{
  String str1 = FmGetString(row1->values[column]);
  String str2 = FmGetString(row2->values[column]);
  int ret_val;

  if (str1 == NULL)
    ret_val = -1; /* str1 is empty. it must be less than str2 */
  else if (str2 == NULL)
    ret_val = 1; /* str2 is empty. str1 must be greater */
  else
    {
      float i1, i2;

      sscanf( str1, "%f", (float *)&i1 );
      sscanf( str2, "%f", (float *)&i2 );

      if (i1 == i2)
	ret_val = 0;
      else if (i1 < i2)
	ret_val = -1;
      else
	ret_val = 1;
    };

  /* clean up */
  if (str1 != NULL) XtFree((XtPointer) str1);
  if (str2 != NULL) XtFree((XtPointer) str2);

  return(ret_val);
}

/*## end user ##*/
/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' InitPixmap  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void InitPixmap(Widget w)
#else
void InitPixmap(w)
Widget w;
#endif
{
/*## begin user  ##*/
	porsche_pix = FmGetPixmap(w,"porsche.xpm");
	crab_pix  = FmGetPixmap(w,"crab.xpm");
	stopsign_pix = FmGetPixmap(w,"stopsign.xpm");
	clown_pix = FmGetPixmap(w,"clown.xbm");
/*## end user  ##*/
}
/*## end `function' InitPixmap  ##*/
/*## begin `function' remCB  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void remCB(Widget w, Widget wTop)
#else
void remCB(w, wTop)
Widget w;
Widget wTop;
#endif
{
/*## begin user  ##*/
    Arg args[5];
    Cardinal argcnt;
    XmMultiListRowInfo *items = NULL, *new_items = NULL;
    short items_count = 0, new_items_count = 0;
    int i, j, k;

    Widget extlist,rem_pb;

    extlist = XtNameToWidget(wTop,"*multiList");
    rem_pb = XtNameToWidget(wTop,"*rem_pb");

    argcnt = 0;
    XtSetArg(args[argcnt], XmNentryData, &items); argcnt++;
    XtSetArg(args[argcnt], XmNnumRows, &items_count); argcnt++;
    XtGetValues(extlist, args, argcnt);

    XmString tcs = XmStringCreateSimple("No Selected Player");
    XtVaSetValues( rem_pb, XmNlabelString,tcs, NULL);
    XmStringFree(tcs);

    if (items_count == 0)
	return;

    /* Count how many were NOT selected */
    for (i = 0; i < items_count; i++)
	if (!items[i].selected)
	    new_items_count++;

    /* Allocate this amount of memory */
    new_items = (XmMultiListRowInfo *) XtMalloc(sizeof(XmMultiListRowInfo) * LINEUP_LIMIT);

    for (i = 0; i < LINEUP_LIMIT; i++) {
	new_items[i].values = (XmString *) XtMalloc(NUM_COLUMNS * sizeof(XmString));
	for (j = 0; j < NUM_COLUMNS; j++)
	    new_items[i].values[j] = NULL;
    }

    for (i = 0, j = 0; i < items_count; i++) {
	if (!items[i].selected) {
	    new_items[j].pixmap = items[i].pixmap;
	    new_items[j].selected = False;
	    new_items[j].data = items[i].data;
	    for (k = 0; k < NUM_COLUMNS; k++)
		new_items[j].values[k] = items[i].values[k];
	    j++;
	}
    }

    argcnt = 0;
    XtSetArg(args[argcnt], XmNentryData, new_items); argcnt++;
    XtSetArg(args[argcnt], XmNnumRows, new_items_count); argcnt++;
    XtSetValues(extlist, args, argcnt);

    for (i = 0; i < items_count; i++) {
	XtFree((XtPointer) items[i].values);
    }
    XtFree((XtPointer) items);

/*## end user  ##*/
}
/*## end `function' remCB  ##*/
/*## begin `function' InitMultilist  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void InitMultilist(Widget w)
#else
void InitMultilist(w)
Widget w;
#endif
{
/*## begin user  ##*/
    XmString tcs;
    Widget retWid;
    Arg args[MAX_ARGS];
    Cardinal argcnt;
    XmMultiListRowInfo *row_info;
    int i, j;
    XmString *col_title_str;
    static String col_titles[] = {
	"At Bat",
	"Name",
	"AVG",
	"AB",
	"R",
	"H",
	"HR",
	"RBI",
	NULL,
    };

    Xm18SortFunction **sort_funcs = (Xm18SortFunction **) XtMalloc(sizeof(Xm18SortFunction *) * NUM_COLUMNS);
    row_info = (XmMultiListRowInfo *) XtMalloc(sizeof(XmMultiListRowInfo) * LINEUP_LIMIT);
    for (i = 0; i < LINEUP_LIMIT; i++) {
	row_info[i].values = (XmString *)
	    XtMalloc(NUM_COLUMNS * sizeof(XmString));
	for (j = 0; j < NUM_COLUMNS; j++)
	    row_info[i].values[j] = NULL;
    }

    for (j = 0; j < NUM_COLUMNS; j++) {
     switch (j){
      case 0:
	sort_funcs[j] = (Xm18SortFunction *)NothingSort;
	break;
      case 1:
	sort_funcs[j] = (Xm18SortFunction *)ExtListAlphaSort;
	break;
      case 2:
      sort_funcs[j] = (Xm18SortFunction *)ExtListDoubleSort;
	break;
      default : sort_funcs[j] = (Xm18SortFunction *)ExtListIntSort;
      }
    }

    argcnt = 0;
    XtSetArg(args[argcnt], XmNentryData, row_info); argcnt++;
    XtSetArg(args[argcnt], XmNsortFunctions, sort_funcs);        argcnt++;
    XtSetValues(w,args,argcnt );

/*## end user  ##*/
}
/*## end `function' InitMultilist  ##*/
/*## begin `function' choosePlayerCB  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void choosePlayerCB(Widget w, Widget parent)
#else
void choosePlayerCB(w, parent)
Widget w;
Widget parent;
#endif
{
/*## begin user  ##*/
Arg args[5];
    Cardinal argcnt;
    XmMultiListRowInfo *row_info;
    short num_rows;
    int i=0, playernum=0;
    char buf[BUFSIZ];
    Boolean found=False;
    String strName;

    Widget wTop = parent;
    Widget wExtlist,wRem_pb,wPlayer[NUM_PLAYERS],wError;

    wExtlist = XtNameToWidget(wTop,"*multiList");
    wRem_pb = XtNameToWidget(wTop,"*rem_pb");
    wError = XtNameToWidget(wTop,"*error");

    strName = (String)malloc(12);

    for (i=0; i <NUM_PLAYERS ; i++)
    {
    	sprintf(strName,"*player%d",i+1);
    	wPlayer[i] = XtNameToWidget(wTop,strName);
    }
    free(strName);
    argcnt = 0;
    XtSetArg(args[argcnt], XmNentryData, &row_info); argcnt++;
    XtSetArg(args[argcnt], XmNnumRows, &num_rows); argcnt++;
    XtGetValues(wExtlist, args, argcnt);

    i = 0;
      while ((i < NUM_PLAYERS) && (!found)){
      if (w == wPlayer[i]) found = True;
      else i++;
    }
    playernum = i;

/*    argcnt = 0;
    XtSetArg(args[argcnt], XmNpositionIndex, &playernum); argcnt++;
    XtGetValues(w, args, argcnt);*/

    if (num_rows == LINEUP_LIMIT) {
	XmString xmstring;
	Widget info = NULL;
	    Cardinal argcnt;

	    xmstring = XmStringCreateSimple("Cannot have more than nine players.");

	    argcnt = 0;
	    XtSetArg(args[argcnt], XmNmessageString, xmstring); argcnt++;
	    XtSetValues(wError, args, argcnt);

	    XmStringFree(xmstring);
 	XtManageChild(wError);
	return;
    }

    for (i = 0; i < num_rows; i++) {
	XmString xmstring;
	static Widget info = NULL;

	if ((int) row_info[i].data == playernum) {

	    sprintf(buf, "%s already in line up.", players[playernum].name);
	    xmstring = XmStringCreateSimple(buf);

	    argcnt = 0;
	    XtSetArg(args[argcnt], XmNmessageString, xmstring); argcnt++;
	    XtSetValues(wError, args, argcnt);

	    XtManageChild(wError);
	    XmStringFree(xmstring);
	    return;
	}
    }

    row_info[num_rows].data = (XtPointer) playernum;

    switch (players[playernum].picture) {
    case PPORSCHE:
      row_info[num_rows].pixmap = porsche_pix;
      break;
    case PCRAB:
    row_info[num_rows].pixmap = crab_pix;
      break;
    case PCLOWN:
    row_info[num_rows].pixmap = clown_pix;
      break;
    case PSTOP:
    row_info[num_rows].pixmap = stopsign_pix;
      break;
    }

    row_info[num_rows].selected = False;

    row_info[num_rows].values[1] =
      XmStringCreateSimple(players[playernum].name);

    XtFree((XtPointer) row_info[num_rows].values[2]);
    sprintf(buf, ".%d", players[playernum].average);
    row_info[num_rows].values[2] = XmStringCreateSimple(buf);

    XtFree((XtPointer) row_info[num_rows].values[3]);
    sprintf(buf, "%d", players[playernum].at_bats);
    row_info[num_rows].values[3] = XmStringCreateSimple(buf);

    XtFree((XtPointer) row_info[num_rows].values[4]);
    sprintf(buf, "%d", players[playernum].runs);
    row_info[num_rows].values[4] = XmStringCreateSimple(buf);

    XtFree((XtPointer) row_info[num_rows].values[5]);
    sprintf(buf, "%d", players[playernum].hits);
    row_info[num_rows].values[5] = XmStringCreateSimple(buf);

    XtFree((XtPointer) row_info[num_rows].values[6]);
    sprintf(buf, "%d", players[playernum].home_runs);
    row_info[num_rows].values[6] = XmStringCreateSimple(buf);

    XtFree((XtPointer) row_info[num_rows].values[7]);
    sprintf(buf, "%d", players[playernum].rbi);
    row_info[num_rows].values[7] = XmStringCreateSimple(buf);

    num_rows++;

    argcnt = 0;
    XtSetArg(args[argcnt], XmNentryData, row_info); argcnt++;
    XtSetArg(args[argcnt], XmNnumColumns, NUM_COLUMNS); argcnt++;
    XtSetArg(args[argcnt], XmNnumRows, num_rows); argcnt++;
    XtSetValues(wExtlist, args, argcnt);
/*## end user  ##*/
}
/*## end `function' choosePlayerCB  ##*/
