/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1034262685
 */

#include <stdio.h>

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#if !defined(XtSpecificationRelease) || XtSpecificationRelease <= 4
#include <X11/Quarks.h>
#else
extern	XrmQuark  XtQBool;
extern	XrmQuark  XtQBoolean;
extern	XrmQuark  XtQColor;
extern	XrmQuark  XtQCursor;
extern	XrmQuark  XtQDimension;
extern	XrmQuark  XtQDisplay;
extern	XrmQuark  XtQFile;
extern	XrmQuark  XtQFont;
extern	XrmQuark  XtQFontStruct;
extern	XrmQuark  XtQInt;
extern	XrmQuark  XtQPixel;
extern	XrmQuark  XtQPixmap;
extern	XrmQuark  XtQPointer;
extern  XrmQuark  XtQPosition;
extern  XrmQuark  XtQShort;
extern	XrmQuark  XtQString;
extern  XrmQuark  XtQUnsignedChar;
extern	XrmQuark  XtQWindow;
#endif
#include <X11/Shell.h>

#include <Xm/Xm.h>

#define	true	True
#define	false	False

#undef  XtMapWidget
#undef  XtUnmapWidget
#define XtMapWidget(widget)     XMapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))
#define XtUnmapWidget(widget)   XUnmapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))

#ifndef _CROSSAPP_H_
#include "CrossApp.h"
#define _CROSSAPP_H_
#endif /* _CROSSAPP_H_ */

#include <Fm.h>

#include <Xm/DrawingA.h>

#ifndef _FACE_NO_FLOATS

static float _vtof_(
#if NeedFunctionPrototypes
XtArgVal v)
#else
v)
XtArgVal v;
#endif
{	float f;
	f = *(float*)&v;
	return(f);
}

static XtArgVal _ftov_(
#if NeedFunctionPrototypes
float f)
#else
f)
float f;
#endif
{	float _f = f;
	XtArgVal v;
	*(float*)&v = _f;
	return(v);
}

#endif


extern XrmQuark XtQNone;
extern XrmQuark XtQAny;
extern XrmQuark XtQFloat;
extern XrmQuark XtQWidget;
extern XrmQuark XtQCallback;

typedef struct {
	XtArgVal value;
	XrmQuark type;
} FaceVariable;

#ifdef __cplusplus
extern "C" {
#endif
extern Widget FaceGetWidget(
#if NeedFunctionPrototypes
Widget ref, int level, String names);
#else
);
#endif
extern XtArgVal FaceGetResource(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetResource(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceGetProperty(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetProperty(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern void FmNewAv(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, Widget widget, Widget* group);
#else
);
#endif
extern void FmCreateValue(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, String type, int storage, int scope, int immediate, int automatic, int genfun, Widget widget, Widget* group, Arg* avs, Cardinal num_avs);
#else
);
#endif
extern int FaceReadValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceFetchValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceInitValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceInitValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceWriteValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceChangeValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern String FmInternationalize(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern String FmNewIString(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern void FmFreeAllIStrings(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern int FmResetDatabase(
#if NeedFunctionPrototypes
Display* display);
#else
);
#endif
extern int FmLoadStringDataBase(
#if NeedFunctionPrototypes
Widget w, char** str, char* name);
#else
);
#endif
extern Widget FmToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern Widget FmAppShell(
#if NeedFunctionPrototypes
Widget w);
#else
);
#endif
extern Widget FmRealizeToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
#ifdef __cplusplus
}
#endif
#define WIDGET_TABLE ((Widget*)client_data)


/* XFM resource exposeCallback ApplicationShell25.WorkSpace1 */
static void WIDGET_1_exposeCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;

	_r0.value = (XtArgVal) *(((XtArgVal*)call_data) + 1);	/* XFM 3 */
	draw_cross((Widget)WIDGET_TABLE[1], (XEvent*)_r0.value);
}


/* XFM resource resizeCallback ApplicationShell25.WorkSpace1 */
static void WIDGET_1_resizeCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;

	_r0.value = (XtArgVal) 0;
	draw_cross((Widget)WIDGET_TABLE[1], (XEvent*)_r0.value);
}

/* XFM private */
#undef WIDGET_TABLE

static void FreeWidgetTable(
#if NeedFunctionPrototypes
Widget w, XtPointer table, XtPointer unused)
#else
w, table, unused)
Widget w;
XtPointer table;
XtPointer unused;
#endif
{
	XtFree((char*)table);
}

Widget
_FmCreateCross(
#if NeedFunctionPrototypes
String name, Widget parent, Widget * toplevels, Cardinal num_toplevels, Widget ** widgets_return, Cardinal * num_widgets_return, Arg* avs, Cardinal num_avs, Arg* user_args, Cardinal num_user_args, Boolean manage_top_objects, XtPointer _this)
#else
name, parent, toplevels, num_toplevels, widgets_return, num_widgets_return, avs, num_avs, user_args, num_user_args, manage_top_objects, _this)
String name;
Widget parent;
Widget * toplevels;
Cardinal num_toplevels;
Widget ** widgets_return;
Cardinal * num_widgets_return;
Arg* avs;
Cardinal num_avs;
Arg* user_args;
Cardinal num_user_args;
Boolean manage_top_objects;
XtPointer _this;
#endif
{
	Arg args[107];
	Cardinal nargs, i;
	XrmValue from, to;
	String app_name, app_class;
	Widget *widget_table = (Widget*)XtMalloc(2*sizeof(Widget));
#define WIDGET_TABLE widget_table

	if(widgets_return) *widgets_return = widget_table;
	if(num_widgets_return) *num_widgets_return = 2;

	/* XFM create ApplicationShell25 */
	if(toplevels && 0 < num_toplevels && toplevels[0]){
		WIDGET_TABLE[0] = toplevels[0];
	} else {
	nargs = 0;
	XtSetArg(args[nargs], "saveUnder", False); nargs++;
	XtSetArg(args[nargs], "wmTimeout", 0); nargs++;
	XtSetArg(args[nargs], "x", 181); nargs++;
	XtSetArg(args[nargs], "y", 129); nargs++;
	XtSetArg(args[nargs], "width", 530); nargs++;
	XtSetArg(args[nargs], "height", 550); nargs++;
	XtSetArg(args[nargs], "title", "Cross"); nargs++;
	for(i = 0; i < num_user_args; i++){
		args[nargs].name = user_args[i].name;
		args[nargs].value = user_args[i].value;
		nargs++;
	}
	XtGetApplicationNameAndClass(XtDisplay(parent), &app_name, &app_class);
	WIDGET_TABLE[0] = XtAppCreateShell(app_name, app_class, applicationShellWidgetClass, XtDisplay(parent), args, nargs);
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[0], WIDGET_TABLE, &arg, 1);
	}

	/* XFM create ApplicationShell25.WorkSpace1 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 530); nargs++;
	XtSetArg(args[nargs], "height", 550); nargs++;
	WIDGET_TABLE[1] = XtCreateManagedWidget("WorkSpace1", xmDrawingAreaWidgetClass, WIDGET_TABLE[0], args, nargs);
	XtAddCallback(WIDGET_TABLE[1], "resizeCallback", (XtCallbackProc)WIDGET_1_resizeCallback, (XtPointer)WIDGET_TABLE);
	XtAddCallback(WIDGET_TABLE[1], "exposeCallback", (XtCallbackProc)WIDGET_1_exposeCallback, (XtPointer)WIDGET_TABLE);

	/* XFM private */

	if(manage_top_objects){
	XtRealizeWidget(WIDGET_TABLE[0]);
	}
	XtAddCallback(WIDGET_TABLE[0], XmNdestroyCallback, (XtCallbackProc)FreeWidgetTable, (XtPointer)WIDGET_TABLE);

	return(WIDGET_TABLE[0]);
}

Widget
FmCreateCross(
#if NeedFunctionPrototypes
String name, Widget parent, Arg* args, Cardinal num_args)
#else
name, parent, args, num_args)
String name;
Widget parent;
Arg* args;
Cardinal num_args;
#endif
{
	return(_FmCreateCross(name, parent, 0, 0, 0, 0, 0, 0, args, num_args, True, 0));
}
