/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1033033205
 */

/*
 *  XFaceMaker 3.5 Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' draw_cross  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void draw_cross(Widget w, XEvent* event)
#else
void draw_cross(w, event)
Widget  w;
XEvent* event;
#endif
{
/*## begin user  ##*/
	Display *dpy = XtDisplay(w);
	Window window = XtWindow(w);
	GC gc = DefaultGC(dpy, 0);
	Dimension width, height;
		
	XtVaGetValues(w, XmNwidth, &width, XmNheight, &height, 0);
	
	/* if event is NULL function is a resizeCallback	*/
	/* if event is not the last expose event, do nothing	*/
	if (event)
		if (event->type == Expose && event->xexpose.count != 0)
			return;

	XClearWindow(dpy, window);
	XDrawLine( dpy, window, gc, 0, 0, width, height);
	XDrawLine( dpy, window, gc, 0, height, width, 0);
/*## end user  ##*/
}
/*## end `function' draw_cross  ##*/
