include ../../config/Xfm-demos.rules

# Makefile used to build the xfm examples

	      PR1 = Age
         PROGRAMS = $(PR1)
  GENERATED_FILES =  $(PR1).c $(PR1)Main.c $(PR1)App.h

.PHONY: $(PROGRAMS)

all:: $(PROGRAMS)

$(PR1):    $(PR1).fm $(PR1)Make $(PR1)App.c $(PR1)App.h $(PR1)Main.c $(PR1).exe $(PR1).editor
