/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1034262699
 */

#include <stdio.h>

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#if !defined(XtSpecificationRelease) || XtSpecificationRelease <= 4
#include <X11/Quarks.h>
#else
extern	XrmQuark  XtQBool;
extern	XrmQuark  XtQBoolean;
extern	XrmQuark  XtQColor;
extern	XrmQuark  XtQCursor;
extern	XrmQuark  XtQDimension;
extern	XrmQuark  XtQDisplay;
extern	XrmQuark  XtQFile;
extern	XrmQuark  XtQFont;
extern	XrmQuark  XtQFontStruct;
extern	XrmQuark  XtQInt;
extern	XrmQuark  XtQPixel;
extern	XrmQuark  XtQPixmap;
extern	XrmQuark  XtQPointer;
extern  XrmQuark  XtQPosition;
extern  XrmQuark  XtQShort;
extern	XrmQuark  XtQString;
extern  XrmQuark  XtQUnsignedChar;
extern	XrmQuark  XtQWindow;
#endif
#include <X11/Shell.h>

#include <Xm/Xm.h>

#define	true	True
#define	false	False

#undef  XtMapWidget
#undef  XtUnmapWidget
#define XtMapWidget(widget)     XMapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))
#define XtUnmapWidget(widget)   XUnmapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))

#ifndef _DRAGDROPAPP_H_
#include "DragDropApp.h"
#define _DRAGDROPAPP_H_
#endif /* _DRAGDROPAPP_H_ */

#include <Fm.h>

#include <Xm/Form.h>
#include <Xm/ScrollBar.h>
#include <Xm/Text.h>
#include <Xm/Display.h>
#include <Xm/Screen.h>

#ifndef _FACE_NO_FLOATS

static float _vtof_(
#if NeedFunctionPrototypes
XtArgVal v)
#else
v)
XtArgVal v;
#endif
{	float f;
	f = *(float*)&v;
	return(f);
}

static XtArgVal _ftov_(
#if NeedFunctionPrototypes
float f)
#else
f)
float f;
#endif
{	float _f = f;
	XtArgVal v;
	*(float*)&v = _f;
	return(v);
}

#endif


extern XrmQuark XtQNone;
extern XrmQuark XtQAny;
extern XrmQuark XtQFloat;
extern XrmQuark XtQWidget;
extern XrmQuark XtQCallback;

typedef struct {
	XtArgVal value;
	XrmQuark type;
} FaceVariable;

#ifdef __cplusplus
extern "C" {
#endif
extern Widget FaceGetWidget(
#if NeedFunctionPrototypes
Widget ref, int level, String names);
#else
);
#endif
extern XtArgVal FaceGetResource(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetResource(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceGetProperty(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetProperty(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern void FmNewAv(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, Widget widget, Widget* group);
#else
);
#endif
extern void FmCreateValue(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, String type, int storage, int scope, int immediate, int automatic, int genfun, Widget widget, Widget* group, Arg* avs, Cardinal num_avs);
#else
);
#endif
extern int FaceReadValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceFetchValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceInitValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceInitValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceWriteValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceChangeValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern String FmInternationalize(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern String FmNewIString(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern void FmFreeAllIStrings(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern int FmResetDatabase(
#if NeedFunctionPrototypes
Display* display);
#else
);
#endif
extern int FmLoadStringDataBase(
#if NeedFunctionPrototypes
Widget w, char** str, char* name);
#else
);
#endif
extern Widget FmToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern Widget FmAppShell(
#if NeedFunctionPrototypes
Widget w);
#else
);
#endif
extern Widget FmRealizeToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
#ifdef __cplusplus
}
#endif
#define WIDGET_TABLE ((Widget*)client_data)


/* XFM set script of av STRING ApplicationShell0.XmForm0.XmScrollBar0 */
static void STRING_WIDGET_4_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	Arg _arg;

	_r0.value = (XtArgVal) atoi((String)*((XtArgVal*)call_data));
	_r0.type = XtQInt;
	_r1.value = (XtArgVal) _r0.value;
	XtSetArg(_arg, "value", _r1.value);
	XtSetValues((Widget)WIDGET_TABLE[4], &_arg, 1);
}


/* XFM get script of av INTEGER ApplicationShell0.XmForm0.XmScrollBar0 */
static void INTEGER_WIDGET_4_get(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	Arg _arg;
	FaceVariable _r0;

	XtSetArg(_arg, "value", &_r0.value);
	XtGetValues((Widget)WIDGET_TABLE[4], &_arg, 1);
	_r0.value = (XtArgVal)*(int*)&_r0.value;
	_r0.type = XtQInt;
	*(XtArgVal*)call_data = (XtArgVal) _r0.value;
}

#ifndef XmDROP_COPY
#define XmDROP_COPY 2
#endif
FaceVariable copy_icon;
#ifndef XmDROP_MOVE
#define XmDROP_MOVE 1
#endif
FaceVariable move_icon;

/* XFM set script of av operationChangedCallback ApplicationShell0.XmForm0.XmText0 */
static void operationChangedCallback_WIDGET_5_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable cbs;
	static FaceVariable icon;
	static FaceVariable drag_context;
	FaceVariable _r0;
	FaceVariable _r1;

	cbs.type = XrmStringToQuark("XmOperationChangedCallback");
	drag_context.type = XtQWidget;
	cbs.value = (XtArgVal) call_data;	/* XFM 2 */
	_r0.value = (XtArgVal) ((XmOperationChangedCallback )cbs.value)->operation;	/* XFM 5 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value == (XtArgVal)XmDROP_COPY);
	if(_r1.value){
		icon.value = (XtArgVal) copy_icon.value;	/* XFM 6 */
		icon.type = copy_icon.type;
	} else {
		_r0.value = (XtArgVal) ((XmOperationChangedCallback )cbs.value)->operation;	/* XFM 8 */
		_r1.value = (XtArgVal) ((XtArgVal)_r0.value == (XtArgVal)XmDROP_MOVE);
		if(_r1.value){
			icon.value = (XtArgVal) move_icon.value;	/* XFM 9 */
			icon.type = move_icon.type;
		} else {
			_r0.value = (XtArgVal) 0;	/* XFM 11 */
			_r0.type = XtQWidget;
			icon.value = (XtArgVal) _r0.value;
			icon.type = _r0.type;
		}
	}
	_r0.value = (XtArgVal) ((XmOperationChangedCallback )cbs.value)->timeStamp;	/* XFM 12 */
	_r1.value = (XtArgVal) XmGetDragContext((Widget)WIDGET_TABLE[5], (Time)_r0.value);
	_r1.type = XtQWidget;
	drag_context.value = (XtArgVal) _r1.value;
	_r0.value = (XtArgVal)drag_context.value;	/* XFM 13 */
	FaceSetResource((Widget)_r0.value, "operationCursorIcon", (XtArgVal)icon.value, (XrmQuark)icon.type);
}

#ifndef XmVALID_DROP_SITE
#define XmVALID_DROP_SITE 3
#endif
FaceVariable valid_icon;
#ifndef XmINVALID_DROP_SITE
#define XmINVALID_DROP_SITE 2
#endif
FaceVariable invalid_icon;

/* XFM set script of av dragMotionCallback ApplicationShell0.XmForm0.XmText0 */
static void dragMotionCallback_WIDGET_5_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable cbs;
	static FaceVariable icon;
	static FaceVariable drag_context;
	FaceVariable _r0;
	FaceVariable _r1;

	cbs.type = XrmStringToQuark("XmDragMotionCallback");
	drag_context.type = XtQWidget;
	cbs.value = (XtArgVal) call_data;	/* XFM 2 */
	_r0.value = (XtArgVal) ((XmDragMotionCallback )cbs.value)->dropSiteStatus;	/* XFM 5 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value == (XtArgVal)XmVALID_DROP_SITE);
	if(_r1.value){
		icon.value = (XtArgVal) valid_icon.value;	/* XFM 6 */
		icon.type = valid_icon.type;
	} else {
		_r0.value = (XtArgVal) ((XmDragMotionCallback )cbs.value)->dropSiteStatus;	/* XFM 8 */
		_r1.value = (XtArgVal) ((XtArgVal)_r0.value == (XtArgVal)XmINVALID_DROP_SITE);
		if(_r1.value){
			icon.value = (XtArgVal) invalid_icon.value;	/* XFM 9 */
			icon.type = invalid_icon.type;
		} else {
			_r0.value = (XtArgVal) 0;	/* XFM 11 */
			_r0.type = XtQWidget;
			icon.value = (XtArgVal) _r0.value;
			icon.type = _r0.type;
		}
	}
	_r0.value = (XtArgVal) ((XmDragMotionCallback )cbs.value)->timeStamp;	/* XFM 12 */
	_r1.value = (XtArgVal) XmGetDragContext((Widget)WIDGET_TABLE[5], (Time)_r0.value);
	_r1.type = XtQWidget;
	drag_context.value = (XtArgVal) _r1.value;
	_r0.value = (XtArgVal)drag_context.value;	/* XFM 13 */
	FaceSetResource((Widget)_r0.value, "stateCursorIcon", (XtArgVal)icon.value, (XrmQuark)icon.type);
}


/* XFM set script of av INTEGER ApplicationShell0.XmForm0.XmText0 */
static void INTEGER_WIDGET_5_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	Arg _arg;

	_r0.value = (XtArgVal) FmItoa((int)*((XtArgVal*)call_data));
	_r0.type = XtQString;
	_r1.value = (XtArgVal) _r0.value;
	XtSetArg(_arg, "value", _r1.value);
	XtSetValues((Widget)WIDGET_TABLE[5], &_arg, 1);
}


/* XFM get script of av STRING ApplicationShell0.XmForm0.XmText0 */
static void STRING_WIDGET_5_get(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	Arg _arg;
	FaceVariable _r0;

	XtSetArg(_arg, "value", &_r0.value);
	XtGetValues((Widget)WIDGET_TABLE[5], &_arg, 1);
	_r0.type = XtQString;
	*(XtArgVal*)call_data = (XtArgVal) _r0.value;
}


/* XFM create proc ApplicationShell0.XmForm0.XmScrollBar0 */
static void WIDGET_4_createCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FmRegisterSimpleDropSite((Widget)WIDGET_TABLE[4], (String)"STRING");
}


/* XFM create proc ApplicationShell0.XmForm0.XmText0 */
static void WIDGET_5_createCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	XmDropSiteUnregister((Widget)WIDGET_TABLE[5]);
	FmRegisterSimpleDropSite((Widget)WIDGET_TABLE[5], (String)"operationChangedCallback,dragMotionCallback,INTEGER");	/* XFM 2 */
}

/* XFM action DragDrop_Action_0 translations <Btn2Down> */

/* XFM resource ??? ApplicationShell0.XmForm0.XmScrollBar0 */
static void _WIDGET_4_DragDrop_Action_0(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data);
#else
);
#endif
static void WIDGET_4_DragDrop_Action_0(
#if NeedFunctionPrototypes
Widget widget, XEvent* event)
#else
widget, event)
Widget widget;
XEvent* event;
#endif
{
	_WIDGET_4_DragDrop_Action_0(widget, 0, (XtPointer)event);
}
static void _WIDGET_4_DragDrop_Action_0(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;

	_r0.value = (XtArgVal)widget;
	_r1.value = (XtArgVal)widget;
	_r2.value = (XtArgVal) FaceConvertString((Widget)_r1.value, (String)"numbers.bm", (String)"Pixmap");
	FmStartSimpleDrag((Widget)_r0.value, (XEvent*)call_data, (String)"INTEGER", (Pixmap)_r2.value);
}

/* XFM action DragDrop_Action_0 translations <Btn2Down> */
#ifndef XmATTACH_SOUTH_EAST
#define XmATTACH_SOUTH_EAST 4
#endif
#ifndef XmATTACH_SOUTH_WEST
#define XmATTACH_SOUTH_WEST 6
#endif
/* XFM function StartDrag */
/* XFM resource ??? ApplicationShell0.XmForm0.XmText0 */
/* XFM 6 */
static void StartDrag(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else /* NeedFunctionPrototypes */
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif /* NeedFunctionPrototypes */
{
	FaceVariable arglist;
	FaceVariable source_icon;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;
	FaceVariable _r3;
	FaceVariable _r4;
	FaceVariable _r5;
	FaceVariable _r6;
	FaceVariable _r7;
	FaceVariable _r8;
	FaceVariable _r9;
	FaceVariable _r10;
	FaceVariable _r11;
	FaceVariable _r12;
	FaceVariable _r13;
	FaceVariable _r14;
	FaceVariable _r15;
	FaceVariable _r16;
	FaceVariable _r17;
	FaceVariable _r18;
	FaceVariable _r19;
	FaceVariable _r20;
	FaceVariable _r21;
	FaceVariable _r22;
	FaceVariable _r23;

	arglist.value = 0;
	arglist.type = XrmStringToQuark("FmArgList");
	source_icon.value = 0;
	source_icon.type = XtQWidget;
	_r0.value = (XtArgVal) FmNewArgList();	/* XFM 6 */
	_r0.type = XrmStringToQuark("FmArgList");
	arglist.value = (XtArgVal) _r0.value;
	_r1.value = (XtArgVal)widget;	/* XFM 8 */
	_r2.value = (XtArgVal) FmGetPixmap((Widget)_r1.value, (String)"letters.bm");
	FmAddArg((FmArgList*)arglist.value, (String)"pixmap", _r2.value);
	_r3.value = (XtArgVal)widget;	/* XFM 9 */
	_r4.value = (XtArgVal) FaceConvertString((Widget)_r3.value, (String)"letters_m.bm", (String)"Bitmap");
	FmAddArg((FmArgList*)arglist.value, (String)"mask", _r4.value);
	_r5.value = (XtArgVal)widget;	/* XFM 10 */
	_r6.value = (XtArgVal) FmCreateDragIcon((Widget)_r5.value, (String)"source", (FmArgList*)arglist.value);
	_r6.type = XtQWidget;
	source_icon.value = (XtArgVal) _r6.value;
	FmClearArgList((FmArgList*)arglist.value);	/* XFM 11 */
	_r7.value = (XtArgVal)widget;	/* XFM 14 */
	_r8.value = (XtArgVal) FaceConvertString((Widget)_r7.value, (String)"copy.bm", (String)"Bitmap");
	FmAddArg((FmArgList*)arglist.value, (String)"pixmap", _r8.value);
	FmAddArg((FmArgList*)arglist.value, (String)"attachment", XmATTACH_SOUTH_EAST);	/* XFM 15 */
	_r9.value = (XtArgVal)widget;	/* XFM 16 */
	_r10.value = (XtArgVal) FmCreateDragIcon((Widget)_r9.value, (String)"copy", (FmArgList*)arglist.value);
	_r10.type = XtQWidget;
	copy_icon.value = (XtArgVal) _r10.value;
	FmClearArgList((FmArgList*)arglist.value);	/* XFM 17 */
	_r11.value = (XtArgVal)widget;	/* XFM 20 */
	_r12.value = (XtArgVal) FaceConvertString((Widget)_r11.value, (String)"move.bm", (String)"Bitmap");
	FmAddArg((FmArgList*)arglist.value, (String)"pixmap", _r12.value);
	FmAddArg((FmArgList*)arglist.value, (String)"attachment", XmATTACH_SOUTH_EAST);	/* XFM 21 */
	_r13.value = (XtArgVal)widget;	/* XFM 22 */
	_r14.value = (XtArgVal) FmCreateDragIcon((Widget)_r13.value, (String)"move", (FmArgList*)arglist.value);
	_r14.type = XtQWidget;
	move_icon.value = (XtArgVal) _r14.value;
	FmClearArgList((FmArgList*)arglist.value);	/* XFM 23 */
	_r15.value = (XtArgVal)widget;	/* XFM 26 */
	_r16.value = (XtArgVal) FaceConvertString((Widget)_r15.value, (String)"valid.bm", (String)"Bitmap");
	FmAddArg((FmArgList*)arglist.value, (String)"pixmap", _r16.value);
	FmAddArg((FmArgList*)arglist.value, (String)"attachment", XmATTACH_SOUTH_WEST);	/* XFM 27 */
	_r17.value = (XtArgVal)widget;	/* XFM 28 */
	_r18.value = (XtArgVal) FmCreateDragIcon((Widget)_r17.value, (String)"valid", (FmArgList*)arglist.value);
	_r18.type = XtQWidget;
	valid_icon.value = (XtArgVal) _r18.value;
	FmClearArgList((FmArgList*)arglist.value);	/* XFM 29 */
	_r19.value = (XtArgVal)widget;	/* XFM 32 */
	_r20.value = (XtArgVal) FaceConvertString((Widget)_r19.value, (String)"invalid.bm", (String)"Bitmap");
	FmAddArg((FmArgList*)arglist.value, (String)"pixmap", _r20.value);
	FmAddArg((FmArgList*)arglist.value, (String)"attachment", XmATTACH_SOUTH_WEST);	/* XFM 33 */
	_r21.value = (XtArgVal)widget;	/* XFM 34 */
	_r22.value = (XtArgVal) FmCreateDragIcon((Widget)_r21.value, (String)"invalid", (FmArgList*)arglist.value);
	_r22.type = XtQWidget;
	invalid_icon.value = (XtArgVal) _r22.value;
	FmClearArgList((FmArgList*)arglist.value);	/* XFM 35 */
	FmAddArg((FmArgList*)arglist.value, (String)"sourcePixmapIcon", source_icon.value);	/* XFM 37 */
	FmAddArg((FmArgList*)arglist.value, (String)"sourceCursorIcon", source_icon.value);	/* XFM 38 */
	FmAddArg((FmArgList*)arglist.value, (String)"operationCursorIcon", move_icon.value);	/* XFM 39 */
	FmAddArg((FmArgList*)arglist.value, (String)"stateCursorIcon", invalid_icon.value);	/* XFM 40 */
	_r23.value = (XtArgVal)widget;	/* XFM 41 */
	FmDragStart((Widget)_r23.value, (XEvent*)call_data, (String)"STRING", (FmArgList*)arglist.value);
	FmFreeArgList((FmArgList*)arglist.value);	/* XFM 43 */
}


/* XFM resource ??? ApplicationShell0.XmForm0.XmText0 */
static void _WIDGET_5_DragDrop_Action_0(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data);
#else
);
#endif
static void WIDGET_5_DragDrop_Action_0(
#if NeedFunctionPrototypes
Widget widget, XEvent* event)
#else
widget, event)
Widget widget;
XEvent* event;
#endif
{
	_WIDGET_5_DragDrop_Action_0(widget, 0, (XtPointer)event);
}
static void _WIDGET_5_DragDrop_Action_0(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	StartDrag(widget, client_data, call_data);
}

/* XFM private */
static XtActionsRec EvalActions[] = {
	{"WIDGET_4_DragDrop_Action_0", (XtActionProc)WIDGET_4_DragDrop_Action_0},
	{"WIDGET_5_DragDrop_Action_0", (XtActionProc)WIDGET_5_DragDrop_Action_0},
};

#undef WIDGET_TABLE

static void FreeWidgetTable(
#if NeedFunctionPrototypes
Widget w, XtPointer table, XtPointer unused)
#else
w, table, unused)
Widget w;
XtPointer table;
XtPointer unused;
#endif
{
	XtFree((char*)table);
}

Widget
_FmCreateDragDrop(
#if NeedFunctionPrototypes
String name, Widget parent, Widget * toplevels, Cardinal num_toplevels, Widget ** widgets_return, Cardinal * num_widgets_return, Arg* avs, Cardinal num_avs, Arg* user_args, Cardinal num_user_args, Boolean manage_top_objects, XtPointer _this)
#else
name, parent, toplevels, num_toplevels, widgets_return, num_widgets_return, avs, num_avs, user_args, num_user_args, manage_top_objects, _this)
String name;
Widget parent;
Widget * toplevels;
Cardinal num_toplevels;
Widget ** widgets_return;
Cardinal * num_widgets_return;
Arg* avs;
Cardinal num_avs;
Arg* user_args;
Cardinal num_user_args;
Boolean manage_top_objects;
XtPointer _this;
#endif
{
	Arg args[106];
	Cardinal nargs, i;
	XrmValue from, to;
	String app_name, app_class;
	Widget *widget_table = (Widget*)XtMalloc(6*sizeof(Widget));
#define WIDGET_TABLE widget_table

	if(widgets_return) *widgets_return = widget_table;
	if(num_widgets_return) *num_widgets_return = 6;

	{
		static int actions_added;
		if(!actions_added){
			XtAppAddActions(XtWidgetToApplicationContext(parent), EvalActions, XtNumber(EvalActions));
			actions_added = 1;
		}
	}


	/* XFM create XmDisplay */
	if(toplevels && 0 < num_toplevels && toplevels[0]){
		WIDGET_TABLE[0] = toplevels[0];
	} else {
	WIDGET_TABLE[0] = XmGetXmDisplay(XtDisplay(parent));
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[0], WIDGET_TABLE, &arg, 1);
	}
	nargs = 0;
	XtSetArg(args[nargs], "dragInitiatorProtocolStyle", XmDRAG_PREREGISTER); nargs++;
	XtSetArg(args[nargs], "dragReceiverProtocolStyle", XmDRAG_PREREGISTER); nargs++;
	XtSetValues(WIDGET_TABLE[0], args, nargs);

	/* XFM create XmScreen */
	if(toplevels && 1 < num_toplevels && toplevels[1]){
		WIDGET_TABLE[1] = toplevels[1];
	} else {
	WIDGET_TABLE[1] = XmGetXmScreen(XtScreen(parent));
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[1], WIDGET_TABLE, &arg, 1);
	}
	nargs = 0;
	XtSetArg(args[nargs], "moveOpaque", True); nargs++;
	XtSetValues(WIDGET_TABLE[1], args, nargs);

	/* XFM create ApplicationShell0 */
	if(toplevels && 2 < num_toplevels && toplevels[2]){
		WIDGET_TABLE[2] = toplevels[2];
	} else {
	nargs = 0;
	XtSetArg(args[nargs], "x", 408); nargs++;
	XtSetArg(args[nargs], "y", 175); nargs++;
	XtSetArg(args[nargs], "width", 228); nargs++;
	XtSetArg(args[nargs], "height", 159); nargs++;
	for(i = 0; i < num_user_args; i++){
		args[nargs].name = user_args[i].name;
		args[nargs].value = user_args[i].value;
		nargs++;
	}
	XtGetApplicationNameAndClass(XtDisplay(parent), &app_name, &app_class);
	WIDGET_TABLE[2] = XtAppCreateShell(app_name, app_class, applicationShellWidgetClass, XtDisplay(parent), args, nargs);
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[2], WIDGET_TABLE, &arg, 1);
	}

	/* XFM create ApplicationShell0.XmForm0 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 228); nargs++;
	XtSetArg(args[nargs], "height", 159); nargs++;
	WIDGET_TABLE[3] = XtCreateManagedWidget("XmForm0", xmFormWidgetClass, WIDGET_TABLE[2], args, nargs);

	/* XFM create ApplicationShell0.XmForm0.XmScrollBar0 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 28); nargs++;
	XtSetArg(args[nargs], "y", 38); nargs++;
	XtSetArg(args[nargs], "width", 24); nargs++;
	XtSetArg(args[nargs], "height", 80); nargs++;
	from.addr = "#override\n\
<Btn2Down>: WIDGET_4_DragDrop_Action_0()";
	from.size = 51;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XtRTranslationTable, &to);
	if(to.addr) { XtSetArg(args[nargs], "translations", *(XtTranslations*)to.addr); nargs++; }
	from.addr = "black";
	from.size = 6;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XtRPixel, &to);
	if(to.addr) { XtSetArg(args[nargs], "foreground", *(Pixel*)to.addr); nargs++; }
	WIDGET_TABLE[4] = XtCreateManagedWidget("XmScrollBar0", xmScrollBarWidgetClass, WIDGET_TABLE[3], args, nargs);
	FmCreateValue("STRING", (XtCallbackProc)0, (XtCallbackProc)STRING_WIDGET_4_set, 0, 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[4], WIDGET_TABLE, avs, num_avs);
	FmCreateValue("INTEGER", (XtCallbackProc)INTEGER_WIDGET_4_get, (XtCallbackProc)0, 0, 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[4], WIDGET_TABLE, avs, num_avs);
	WIDGET_4_createCallback(WIDGET_TABLE[4], (XtPointer)WIDGET_TABLE, 0);

	/* XFM create ApplicationShell0.XmForm0.XmText0 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 93); nargs++;
	XtSetArg(args[nargs], "y", 32); nargs++;
	XtSetArg(args[nargs], "width", 104); nargs++;
	XtSetArg(args[nargs], "height", 34); nargs++;
	from.addr = "#override\n\
<Btn2Down>: WIDGET_5_DragDrop_Action_0()";
	from.size = 51;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[3], XmRString, &from, XtRTranslationTable, &to);
	if(to.addr) { XtSetArg(args[nargs], "translations", *(XtTranslations*)to.addr); nargs++; }
	WIDGET_TABLE[5] = XtCreateManagedWidget("XmText0", xmTextWidgetClass, WIDGET_TABLE[3], args, nargs);
	FmCreateValue("operationChangedCallback", (XtCallbackProc)0, (XtCallbackProc)operationChangedCallback_WIDGET_5_set, "Callback", 0, 0, 0, 0, 0, (Widget)WIDGET_TABLE[5], WIDGET_TABLE, avs, num_avs);
	FmCreateValue("dragMotionCallback", (XtCallbackProc)0, (XtCallbackProc)dragMotionCallback_WIDGET_5_set, "Callback", 0, 0, 0, 0, 0, (Widget)WIDGET_TABLE[5], WIDGET_TABLE, avs, num_avs);
	FmCreateValue("INTEGER", (XtCallbackProc)0, (XtCallbackProc)INTEGER_WIDGET_5_set, 0, 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[5], WIDGET_TABLE, avs, num_avs);
	FmCreateValue("STRING", (XtCallbackProc)STRING_WIDGET_5_get, (XtCallbackProc)0, 0, 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[5], WIDGET_TABLE, avs, num_avs);
	WIDGET_5_createCallback(WIDGET_TABLE[5], (XtPointer)WIDGET_TABLE, 0);

	/* XFM private */

	if(manage_top_objects){
	XtRealizeWidget(WIDGET_TABLE[2]);
	}
	XtAddCallback(WIDGET_TABLE[2], XmNdestroyCallback, (XtCallbackProc)FreeWidgetTable, (XtPointer)WIDGET_TABLE);

	return(WIDGET_TABLE[2]);
}

Widget
FmCreateDragDrop(
#if NeedFunctionPrototypes
String name, Widget parent, Arg* args, Cardinal num_args)
#else
name, parent, args, num_args)
String name;
Widget parent;
Arg* args;
Cardinal num_args;
#endif
{
	return(_FmCreateDragDrop(name, parent, 0, 0, 0, 0, 0, 0, args, num_args, True, 0));
}
