// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_FT_CORBAS_TUKWXZ_H_
#define _TAO_IDL_FT_CORBAS_TUKWXZ_H_

#include /**/ "ace/pre.h"

#include "FT_CORBAC.h"
#include "orbsvcs/FT_CORBA_ORBS.h"
#include "orbsvcs/PortableGroupS.h"
#include "orbsvcs/CosNamingS.h"
#include "orbsvcs/CosNotificationS.h"
#include "orbsvcs/CosNotifyFilterS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/TypeCode_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

#include /**/ "tao/PortableServer/PolicyS.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO TAO_FT_Export

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_FT_FAULTNOTIFIER__SARG_TRAITS_)
#define _FT_FAULTNOTIFIER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::FT::FaultNotifier>
    : public
        Object_SArg_Traits_T<
            ::FT::FaultNotifier_ptr,
            ::FT::FaultNotifier_var,
            ::FT::FaultNotifier_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::FT::FaultMonitoringIntervalAndTimeoutValue>
    : public
        Fixed_Size_SArg_Traits_T<
            ::FT::FaultMonitoringIntervalAndTimeoutValue,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_FT_FTOBJECTGROUPMANAGER__SARG_TRAITS_)
#define _FT_FTOBJECTGROUPMANAGER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::FT::FTObjectGroupManager>
    : public
        Object_SArg_Traits_T<
            ::FT::FTObjectGroupManager_ptr,
            ::FT::FTObjectGroupManager_var,
            ::FT::FTObjectGroupManager_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_FT
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:76

  class FTObjectGroupManager;
  typedef FTObjectGroupManager *FTObjectGroupManager_ptr;

  class TAO_FT_Export FTObjectGroupManager
    : public virtual POA_PortableGroup::ObjectGroupManager
  {
  protected:
    FTObjectGroupManager (void);
  
  public:
    /// Useful for template programming.
    typedef ::FT::FTObjectGroupManager _stub_type;
    typedef ::FT::FTObjectGroupManager_ptr _stub_ptr_type;
    typedef ::FT::FTObjectGroupManager_var _stub_var_type;

    FTObjectGroupManager (const FTObjectGroupManager& rhs);
    virtual ~FTObjectGroupManager (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::FT::FTObjectGroupManager *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual ::PortableGroup::ObjectGroup_ptr set_primary_member (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Location & the_location) = 0;

    static void set_primary_member_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module FT

TAO_END_VERSIONED_NAMESPACE_DECL



#include /**/ "ace/post.h"

#endif /* ifndef */

