// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_FT_NOTIFIERC_GBWCTP_H_
#define _TAO_IDL_FT_NOTIFIERC_GBWCTP_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "orbsvcs/FaultTolerance/fault_tol_export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "orbsvcs/FT_CORBA_ORBC.h"
#include "orbsvcs/FT_ReplicaC.h"
#include "orbsvcs/CosNamingC.h"
#include "orbsvcs/CosNotificationC.h"
#include "orbsvcs/CosNotifyFilterC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO TAO_FT_Export

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_root/root_ch.cpp:160

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace FT
{

  // TAO_IDL - Generated from
  // be/be_interface.cpp:750

#if !defined (_FT_FAULTNOTIFIER__VAR_OUT_CH_)
#define _FT_FAULTNOTIFIER__VAR_OUT_CH_

  class FaultNotifier;
  typedef FaultNotifier *FaultNotifier_ptr;

  typedef
    TAO_Objref_Var_T<
        FaultNotifier
      >
    FaultNotifier_var;
  
  typedef
    TAO_Objref_Out_T<
        FaultNotifier
      >
    FaultNotifier_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class TAO_FT_Export FaultNotifier
    : public virtual ::FT::PullMonitorable
  
  {
  public:
    friend class TAO::Narrow_Utils<FaultNotifier>;

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef FaultNotifier_ptr _ptr_type;
    typedef FaultNotifier_var _var_type;
    typedef FaultNotifier_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static FaultNotifier_ptr _duplicate (FaultNotifier_ptr obj);

    static void _tao_release (FaultNotifier_ptr obj);

    static FaultNotifier_ptr _narrow (::CORBA::Object_ptr obj);
    static FaultNotifier_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static FaultNotifier_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:370

    typedef ::CORBA::ULongLong ConsumerId;
    typedef ::CORBA::ULongLong_out ConsumerId_out;

    // TAO_IDL - Generated from
    // be/be_visitor_typecode/typecode_decl.cpp:37

    static ::CORBA::TypeCode_ptr const _tc_ConsumerId;

    virtual void push_structured_fault (
      const ::CosNotification::StructuredEvent & event);

    virtual void push_sequence_fault (
      const ::CosNotification::EventBatch & events);

    virtual ::CosNotifyFilter::Filter_ptr create_subscription_filter (
      const char * constraint_grammar);

    virtual ::FT::FaultNotifier::ConsumerId connect_structured_fault_consumer (
      ::CosNotifyComm::StructuredPushConsumer_ptr push_consumer,
      ::CosNotifyFilter::Filter_ptr filter);

    virtual ::FT::FaultNotifier::ConsumerId connect_sequence_fault_consumer (
      ::CosNotifyComm::SequencePushConsumer_ptr push_consumer,
      ::CosNotifyFilter::Filter_ptr filter);

    virtual void disconnect_consumer (
      ::FT::FaultNotifier::ConsumerId connection);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    FaultNotifier (void);

    // Concrete non-local interface only.
    FaultNotifier (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    FaultNotifier (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~FaultNotifier (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    FaultNotifier (const FaultNotifier &);

    void operator= (const FaultNotifier &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FaultNotifier;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module FT

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_FT_FAULTNOTIFIER__ARG_TRAITS_)
#define _FT_FAULTNOTIFIER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::FT::FaultNotifier>
    : public
        Object_Arg_Traits_T<
            ::FT::FaultNotifier_ptr,
            ::FT::FaultNotifier_var,
            ::FT::FaultNotifier_out,
            TAO::Objref_Traits<FT::FaultNotifier>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_FT_FAULTNOTIFIER__TRAITS_)
#define _FT_FAULTNOTIFIER__TRAITS_

  template<>
  struct TAO_FT_Export Objref_Traits< ::FT::FaultNotifier>
  {
    static ::FT::FaultNotifier_ptr duplicate (
        ::FT::FaultNotifier_ptr p);
    static void release (
        ::FT::FaultNotifier_ptr p);
    static ::FT::FaultNotifier_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::FT::FaultNotifier_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FaultNotifier_ptr); // copying
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FaultNotifier_ptr *); // non-copying
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FaultNotifier_ptr &);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultNotifier_ptr); // copying
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultNotifier_ptr *); // non-copying
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::FaultNotifier_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:44


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::FaultNotifier_ptr );
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::FaultNotifier_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be/be_codegen.cpp:1703


TAO_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "FT_NotifierC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

