/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1233576079
 */

/*
 *  XFaceMaker 3.5 Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif
#include "xlogo32"

extern XtAppContext app_context;
static XtIntervalId id;

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' Bounce  ##*/
int interval;
int dy;
int dx;
int height;
int width;
int Help;
int size;
int origin;
/*## end `active_values' Bounce  ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' MoveBall  ##*/
/*## begin user  ##*/
int                 interval = 100;
int                 dy       = 10;
int                 dx       = 10;
int                 height;
int                 width;
int                 Help;
int                 size     = 100;
int                 origin   = 0;
int                 xO       = 100;
int                 yO       = 100;

int                 ballx, bally;
static void DrawBall(Widget w,int x,int y);

/*## end user  ##*/
#if NeedFunctionPrototypes
void MoveBall(Widget w)
#else
void MoveBall(w)
Widget w;
#endif
{
/*## begin user  ##*/
  ballx += dx;
  bally += dy;

  DrawBall(w, ballx, bally);

  if (ballx < 0 || ballx + 32 > width)
  {
    dx = -dx;
  }
  if (bally < 0)
  {
    dy = -dy;
  } else if (bally + 32 > height) {
    if(ballx > origin && (ballx + 32) < (origin + size))
    {
      dy = -dy;
    } else {
      XBell(XtDisplay(w), 100);
      ballx = xO;
      bally = yO;
      id = 0;
      return;
    }
  }
	
  id = XtAppAddTimeOut(app_context, interval, (XtTimerCallbackProc)MoveBall, w);
/*## end user  ##*/
}
/*## end `function' MoveBall  ##*/
/*## begin `function' StopBall  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void StopBall()
#else
void StopBall()

#endif
{
/*## begin user  ##*/
  if (id)
    XtRemoveTimeOut (id);
/*## end user  ##*/
}
/*## end `function' StopBall  ##*/
/*## begin `function' DrawBall  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
static void DrawBall(
Widget w,
int    x,
int    y)
#else
static void DrawBall(w, x, y)
     Widget w;
     int    x;
     int    y;
#endif
{
/*## begin user  ##*/
  static int curx = -10000, cury = -10000;
  static GC  gc = 0;
  
  if (!gc)
  {
    XGCValues gcv;
		
    gcv.clip_mask = XCreateBitmapFromData(XtDisplay(w),
                                          XtWindow(w),
                                          xlogo32_bits,
                                          xlogo32_width,
                                          xlogo32_height);
    gcv.function = GXinvert;
    gc = XCreateGC(XtDisplay(w), XtWindow(w), GCClipMask|GCFunction, &gcv);
    XSetClipOrigin(XtDisplay(w), gc, x, y);
    XFillRectangle(XtDisplay(w), XtWindow(w), gc, x, y, xlogo32_width, xlogo32_height);
    curx = x;
    cury = y;
    return;
  }
  if (x == curx && y == cury)
    return;
  XSetClipOrigin(XtDisplay(w), gc, curx, cury);
  XFillRectangle(XtDisplay(w), XtWindow(w), gc, curx, cury, xlogo32_width, xlogo32_height);
  curx = x;
  cury = y;
  XSetClipOrigin(XtDisplay(w), gc, curx, cury);
  XFillRectangle(XtDisplay(w), XtWindow(w), gc, curx, cury, xlogo32_width, xlogo32_height);
/*## end user  ##*/
}
/*## end `function' StopBall  ##*/
