/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1233576079
 */

/*
 *  XFaceMaker 3.5 Application Functions Declarations.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif
/*## 					begin pattern define [ VARNAME left (length _XFM_EXT_BUILD_INCLUDES) == _XFM_EXT_BUILD_INCLUDES ] ##*/
/*## VALUE ##*/
/*## 					end pattern ##*/

/*## begin pattern `active_values' ##*/
/*## $$extern AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' Bounce  ##*/
extern int interval;
extern int dy;
extern int dx;
extern int height;
extern int width;
extern int Help;
extern int size;
extern int origin;
/*## end `active_values' Bounce  ##*/

#if NeedFunctionPrototypes
/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## extern CTYPE CNAME($$CARGTYPES ARGNAMES$, $); ##*/
/*## end pattern `function' ##*/
/*## begin `function' MoveBall  ##*/
extern void MoveBall(Widget w);
/*## end `function' MoveBall  ##*/
/*## begin `function' StopBall  ##*/
extern void StopBall();
/*## end `function' StopBall  ##*/
#else /* NeedFunctionPrototypes */
/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## extern CTYPE CNAME(); ##*/
/*## end pattern `function' ##*/
/*## begin `function' MoveBall  ##*/
extern void MoveBall();
/*## end `function' MoveBall  ##*/
/*## begin `function' StopBall  ##*/
extern void StopBall();
/*## end `function' StopBall  ##*/
#endif /* NeedFunctionPrototypes */
