/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1227870437
 */

#include <stdio.h>

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#if !defined(XtSpecificationRelease) || XtSpecificationRelease <= 4
#include <X11/Quarks.h>
#else
extern	XrmQuark  XtQBool;
extern	XrmQuark  XtQBoolean;
extern	XrmQuark  XtQColor;
extern	XrmQuark  XtQCursor;
extern	XrmQuark  XtQDimension;
extern	XrmQuark  XtQDisplay;
extern	XrmQuark  XtQFile;
extern	XrmQuark  XtQFont;
extern	XrmQuark  XtQFontStruct;
extern	XrmQuark  XtQInt;
extern	XrmQuark  XtQPixel;
extern	XrmQuark  XtQPixmap;
extern	XrmQuark  XtQPointer;
extern  XrmQuark  XtQPosition;
extern  XrmQuark  XtQShort;
extern	XrmQuark  XtQString;
extern  XrmQuark  XtQUnsignedChar;
extern	XrmQuark  XtQWindow;
#endif
#include <X11/Shell.h>

#include <Xm/Xm.h>

#define	true	True
#define	false	False

#undef  XtMapWidget
#undef  XtUnmapWidget
#define XtMapWidget(widget)     XMapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))
#define XtUnmapWidget(widget)   XUnmapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))

#include <Fm.h>

#include <Xm/DialogS.h>
#include <Xm/FileSB.h>

Widget Fmfsbox_shellWidget, FmfsboxWidget;
#ifndef _FACE_NO_FLOATS

static float _vtof_(
#if NeedFunctionPrototypes
XtArgVal v)
#else
v)
XtArgVal v;
#endif
{	float f;
	f = *(float*)&v;
	return(f);
}

static XtArgVal _ftov_(
#if NeedFunctionPrototypes
float f)
#else
f)
float f;
#endif
{	float _f = f;
	XtArgVal v;
	*(float*)&v = _f;
	return(v);
}

#endif


extern XrmQuark XtQNone;
extern XrmQuark XtQAny;
extern XrmQuark XtQFloat;
extern XrmQuark XtQWidget;
extern XrmQuark XtQCallback;

typedef struct {
	XtArgVal value;
	XrmQuark type;
} FaceVariable;

#ifdef __cplusplus
extern "C" {
#endif
extern Widget FaceGetWidget(
#if NeedFunctionPrototypes
Widget ref, int level, String names);
#else
);
#endif
extern XtArgVal FaceGetResource(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetResource(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceGetProperty(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetProperty(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern void FmNewAv(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, Widget widget, Widget* group);
#else
);
#endif
extern void FmCreateValue(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, String type, int storage, int scope, int immediate, int automatic, int genfun, Widget widget, Widget* group, Arg* avs, Cardinal num_avs);
#else
);
#endif
extern int FaceReadValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceFetchValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceInitValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceInitValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceWriteValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceChangeValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern String FmInternationalize(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern String FmNewIString(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern void FmFreeAllIStrings(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern int FmResetDatabase(
#if NeedFunctionPrototypes
Display* display);
#else
);
#endif
extern int FmLoadStringDataBase(
#if NeedFunctionPrototypes
Widget w, char** str, char* name);
#else
);
#endif
extern Widget FmToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern Widget FmAppShell(
#if NeedFunctionPrototypes
Widget w);
#else
);
#endif
extern Widget FmRealizeToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
#ifdef __cplusplus
}
#endif

/* XFM get script of av fsFile xfm.fsbox_shell.fsbox */
static void fsFile_FmfsboxWidget_get(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	Arg _arg;

	XtManageChild((Widget)FmfsboxWidget);	/* XFM 2 */
	FaceWriteValue((Widget)widget, (Widget)FmfsboxWidget, "fsFinished", (XtArgVal)-1, (XrmQuark)XtQInt);	/* XFM 3 */
	for(;;){	/* XFM 4 */
		FaceReadValue((Widget)widget, (Widget)FmfsboxWidget, "fsFinished", &_r0);
		_r1.value = (XtArgVal) ((XtArgVal)_r0.value == (XtArgVal)-1);
		if(!(_r1.value))
			break;
		else {
			FmDoEvent();	/* XFM 5 */
		}
	}
	FaceReadValue((Widget)widget, (Widget)FmfsboxWidget, "fsFinished", &_r0);	/* XFM 7 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value == (XtArgVal)0);
	if(_r1.value){
		_r0.value = (XtArgVal) 0;	/* XFM 8 */
		_r0.type = XtQString;
		*(XtArgVal*)call_data = (XtArgVal) _r0.value;
	} else {
		XtSetArg(_arg, "dirSpec", &_r0.value);	/* XFM 10 */
		XtGetValues((Widget)FmfsboxWidget, &_arg, 1);
		_r1.value = (XtArgVal) FmGetString((XmString)_r0.value);
		_r1.type = XtQString;
		*(XtArgVal*)call_data = (XtArgVal) _r1.value;
	}
}


/* XFM set script of av fsFile xfm.fsbox_shell.fsbox */
static void fsFile_FmfsboxWidget_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	XrmValue from, to;
	FaceVariable _r1;
	Arg _arg;

	_r0.value = (XtArgVal) *((XtArgVal*)call_data);
	_r0.type = XtQString;
	from.addr = (char *)_r0.value;
	from.size = strlen(from.addr)+1;
	to.addr = 0;
	XtConvertAndStore(FmfsboxWidget, XtRString, &from, XmRXmString, &to);
	_r1.value = (XtArgVal)*(XmString*)to.addr;
	XtSetArg(_arg, "dirSpec", _r1.value);
	XtSetValues((Widget)FmfsboxWidget, &_arg, 1);
}


/* XFM set script of av GetFileName xfm.fsbox_shell.fsbox */
static void GetFileName_FmfsboxWidget_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable a;
	FaceVariable _r0;
	XrmValue from, to;
	FaceVariable _r1;
	Arg _arg;

	a.type = XrmStringToQuark("GetFileNameArgs");
	a.value = (XtArgVal) *((XtArgVal*)call_data);	/* XFM 6 */
	_r0.value = (XtArgVal) (*(((XtArgVal*)(a.value))+(2)));	/* XFM 7 */
	_r0.type = XtQString;
	from.addr = (char *)_r0.value;
	from.size = strlen(from.addr)+1;
	to.addr = 0;
	XtConvertAndStore(FmfsboxWidget, XtRString, &from, XmRXmString, &to);
	_r1.value = (XtArgVal)*(XmString*)to.addr;
	XtSetArg(_arg, "pattern", _r1.value);
	XtSetValues((Widget)FmfsboxWidget, &_arg, 1);
	_r0.value = (XtArgVal) (*(((XtArgVal*)(a.value))+(1)));	/* XFM 8 */
	_r0.type = XtQString;
	FaceWriteValue((Widget)widget, (Widget)FmfsboxWidget, "fsFile", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
	FaceReadValue((Widget)widget, (Widget)FmfsboxWidget, "fsFile", &_r0);	/* XFM 9 */
	(*(((XtArgVal*)(a.value))+(0))) = (XtArgVal)_r0.value;
}


/* XFM resource okCallback xfm.fsbox_shell.fsbox */
static void FmfsboxWidget_okCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FaceWriteValue((Widget)widget, (Widget)FmfsboxWidget, "fsFinished", (XtArgVal)1, (XrmQuark)XtQInt);
}


/* XFM resource cancelCallback xfm.fsbox_shell.fsbox */
static void FmfsboxWidget_cancelCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FaceWriteValue((Widget)widget, (Widget)FmfsboxWidget, "fsFinished", (XtArgVal)0, (XrmQuark)XtQInt);
}

/* XFM private */
Widget
_FmCreateFileSel(
#if NeedFunctionPrototypes
String name, Widget parent, Widget * toplevels, Cardinal num_toplevels, Widget ** widgets_return, Cardinal * num_widgets_return, Arg* avs, Cardinal num_avs, Arg* user_args, Cardinal num_user_args, Boolean manage_top_objects, XtPointer _this)
#else
name, parent, toplevels, num_toplevels, widgets_return, num_widgets_return, avs, num_avs, user_args, num_user_args, manage_top_objects, _this)
String name;
Widget parent;
Widget * toplevels;
Cardinal num_toplevels;
Widget ** widgets_return;
Cardinal * num_widgets_return;
Arg* avs;
Cardinal num_avs;
Arg* user_args;
Cardinal num_user_args;
Boolean manage_top_objects;
XtPointer _this;
#endif
{
	Arg args[110];
	Cardinal nargs, i;
	XrmValue from, to;

	/* XFM create fsbox_shell */
	if(toplevels && 0 < num_toplevels && toplevels[0]){
		Fmfsbox_shellWidget = toplevels[0];
	} else {
	nargs = 0;
	XtSetArg(args[nargs], "x", 261); nargs++;
	XtSetArg(args[nargs], "y", 352); nargs++;
	XtSetArg(args[nargs], "width", 290); nargs++;
	XtSetArg(args[nargs], "height", 378); nargs++;
	for(i = 0; i < num_user_args; i++){
		args[nargs].name = user_args[i].name;
		args[nargs].value = user_args[i].value;
		nargs++;
	}
	Fmfsbox_shellWidget = XtCreatePopupShell((name ? name : "fsbox_shell"), xmDialogShellWidgetClass, parent, args, nargs);
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)Fmfsbox_shellWidget, (Widget*)0, &arg, 1);
	}

	/* XFM create fsbox_shell.fsbox */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 290); nargs++;
	XtSetArg(args[nargs], "height", 378); nargs++;
	XtSetArg(args[nargs], "defaultPosition", False ); nargs++;
	from.addr = "File Selector";
	from.size = 14;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(Fmfsbox_shellWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "dialogTitle", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "autoUnmanage", True ); nargs++;
	XtSetArg(args[nargs], "dialogStyle", XmDIALOG_FULL_APPLICATION_MODAL); nargs++;
	FmfsboxWidget = XtCreateWidget("fsbox", xmFileSelectionBoxWidgetClass, Fmfsbox_shellWidget, args, nargs);
	XtAddCallback(FmfsboxWidget, "cancelCallback", (XtCallbackProc)FmfsboxWidget_cancelCallback, (XtPointer)0);
	XtAddCallback(FmfsboxWidget, "okCallback", (XtCallbackProc)FmfsboxWidget_okCallback, (XtPointer)0);
	FmCreateValue("fsFile", (XtCallbackProc)fsFile_FmfsboxWidget_get, (XtCallbackProc)fsFile_FmfsboxWidget_set, "String", 1, 0, 0, 1, 0, (Widget)FmfsboxWidget, (Widget*)0, avs, num_avs);
	FmCreateValue("fsFinished", (XtCallbackProc)0, (XtCallbackProc)0, "Int", 1, 1, 0, 1, 0, (Widget)FmfsboxWidget, (Widget*)0, avs, num_avs);
	FmCreateValue("GetFileName", (XtCallbackProc)0, (XtCallbackProc)GetFileName_FmfsboxWidget_set, "GetFileNameArgs", 2, 0, 0, 1, 0, (Widget)FmfsboxWidget, (Widget*)0, avs, num_avs);

	/* XFM private */

	if(manage_top_objects){
	}

	return(Fmfsbox_shellWidget);
}

Widget
FmCreateFileSel(
#if NeedFunctionPrototypes
String name, Widget parent, Arg* args, Cardinal num_args)
#else
name, parent, args, num_args)
String name;
Widget parent;
Arg* args;
Cardinal num_args;
#endif
{
	return(_FmCreateFileSel(name, parent, 0, 0, 0, 0, 0, 0, args, num_args, True, 0));
}
