/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1227870437
 */

#include <stdio.h>

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#if !defined(XtSpecificationRelease) || XtSpecificationRelease <= 4
#include <X11/Quarks.h>
#else
extern	XrmQuark  XtQBool;
extern	XrmQuark  XtQBoolean;
extern	XrmQuark  XtQColor;
extern	XrmQuark  XtQCursor;
extern	XrmQuark  XtQDimension;
extern	XrmQuark  XtQDisplay;
extern	XrmQuark  XtQFile;
extern	XrmQuark  XtQFont;
extern	XrmQuark  XtQFontStruct;
extern	XrmQuark  XtQInt;
extern	XrmQuark  XtQPixel;
extern	XrmQuark  XtQPixmap;
extern	XrmQuark  XtQPointer;
extern  XrmQuark  XtQPosition;
extern  XrmQuark  XtQShort;
extern	XrmQuark  XtQString;
extern  XrmQuark  XtQUnsignedChar;
extern	XrmQuark  XtQWindow;
#endif
#include <X11/Shell.h>

#include <Xm/Xm.h>

#define	true	True
#define	false	False

#undef  XtMapWidget
#undef  XtUnmapWidget
#define XtMapWidget(widget)     XMapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))
#define XtUnmapWidget(widget)   XUnmapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))

#include <Fm.h>

#include <Xm/DialogS.h>
#include <Xm/CascadeB.h>
#include <Xm/CascadeBG.h>
#include <Xm/Label.h>
#include <Xm/LabelG.h>
#include <Xm/MainW.h>
#include <Xm/MessageB.h>
#include <Xm/PushB.h>
#include <Xm/PushBG.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Separator.h>
#include <Xm/SeparatoG.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/Notebook.h>

Widget FmsessionShell0Widget, FmmainwWidget, FmmenubWidget, FmselectedPulldownWidget, FmpropertiesWidget,
		 FmnewWidget, FmopenWidget, Fmseparator1Widget, Fmseparator2Widget, Fmsetected_deleteWidget,
		 Fmexit1Widget, FmFilePulldownWidget, Fmnew_selectedWidget, Fmopen_selectedWidget, FmsaveWidget,
		 FmsaveasWidget, Fmseparator1Widget_1, FmprintWidget, Fmseperator2Widget, Fmexit2Widget,
		 FmFileWidget, FmselectedWidget, FmhelpPulldownWidget, FmoverviewWidget, FmhelpWidget,
		 FmnotebookWidget, FmscrolltextWidget, FmtextWidget, FmlabelWidget, FmxmDialogShell2Widget,
		 FmdeletePageWidget, FmxmDialogShell0_2Widget, FmEditPageWidget, FmrcWidget, Fmrc2Widget,
		 Fmlabel1Widget, FmeditTFWidget, Fmrc2_2Widget, Fmlabel2Widget, FmmajorTFWidget,
		 Fmrc2_3Widget, Fmlabel3Widget, FmminorTFWidget;
#ifndef _FACE_NO_FLOATS

static float _vtof_(
#if NeedFunctionPrototypes
XtArgVal v)
#else
v)
XtArgVal v;
#endif
{	float f;
	f = *(float*)&v;
	return(f);
}

static XtArgVal _ftov_(
#if NeedFunctionPrototypes
float f)
#else
f)
float f;
#endif
{	float _f = f;
	XtArgVal v;
	*(float*)&v = _f;
	return(v);
}

#endif


extern XrmQuark XtQNone;
extern XrmQuark XtQAny;
extern XrmQuark XtQFloat;
extern XrmQuark XtQWidget;
extern XrmQuark XtQCallback;

typedef struct {
	XtArgVal value;
	XrmQuark type;
} FaceVariable;

#ifdef __cplusplus
extern "C" {
#endif
extern Widget FaceGetWidget(
#if NeedFunctionPrototypes
Widget ref, int level, String names);
#else
);
#endif
extern XtArgVal FaceGetResource(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetResource(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceGetProperty(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetProperty(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern void FmNewAv(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, Widget widget, Widget* group);
#else
);
#endif
extern void FmCreateValue(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, String type, int storage, int scope, int immediate, int automatic, int genfun, Widget widget, Widget* group, Arg* avs, Cardinal num_avs);
#else
);
#endif
extern int FaceReadValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceFetchValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceInitValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceInitValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceWriteValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceChangeValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern String FmInternationalize(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern String FmNewIString(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern void FmFreeAllIStrings(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern int FmResetDatabase(
#if NeedFunctionPrototypes
Display* display);
#else
);
#endif
extern int FmLoadStringDataBase(
#if NeedFunctionPrototypes
Widget w, char** str, char* name);
#else
);
#endif
extern Widget FmToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern Widget FmAppShell(
#if NeedFunctionPrototypes
Widget w);
#else
);
#endif
extern Widget FmRealizeToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
#ifdef __cplusplus
}
#endif

/* XFM get script of av todo_filename sessionShell0 */
static void todo_filename_FmsessionShell0Widget_get(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;

	_r0.value = (XtArgVal) (! (XtArgVal)*((XtArgVal*)call_data));
	if((XtArgVal)_r0.value == 0){
		_r1.value = (XtArgVal) FmEqualString((String)*((XtArgVal*)call_data), (String)"");
	} else _r1.value = 1;
	_r2.value = (XtArgVal) ((XtArgVal)_r0.value || (XtArgVal)_r1.value);
	if(_r2.value){
		*(XtArgVal*)call_data = (XtArgVal) "unnamed";	/* XFM 2 */
	}
}


/* XFM set script of av todo_filename sessionShell0 */
static void todo_filename_FmsessionShell0Widget_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable buf;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;
	Arg _arg;

	buf.type = XtQString;
	_r0.value = (XtArgVal) (! (XtArgVal)*((XtArgVal*)call_data));
	if((XtArgVal)_r0.value == 0){
		_r1.value = (XtArgVal) FmEqualString((String)*((XtArgVal*)call_data), (String)"");
	} else _r1.value = 1;
	_r2.value = (XtArgVal) ((XtArgVal)_r0.value || (XtArgVal)_r1.value);
	if(_r2.value){
		_r0.value = (XtArgVal) "Edit: unnamed";	/* XFM 2 */
		XtSetArg(_arg, "title", _r0.value);
		XtSetValues((Widget)FmsessionShell0Widget, &_arg, 1);
		return;	/* XFM 3 */
	}
	_r0.value = (XtArgVal) XtMalloc((int)512);	/* XFM 5 */
	_r0.type = XtQString;
	buf.value = (XtArgVal) _r0.value;
	sprintf((String)buf.value, (String)"Edit: %s", *((XtArgVal*)call_data));	/* XFM 6 */
	_r0.value = (XtArgVal) buf.value;	/* XFM 7 */
	XtSetArg(_arg, "title", _r0.value);
	XtSetValues((Widget)FmsessionShell0Widget, &_arg, 1);
}


/* XFM set script of av ModifPage sessionShell0.mainw.notebook */
static void ModifPage_FmnotebookWidget_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable xmstrtmp;
	static FaceVariable buf;
	static FaceVariable cur;
	static FaceVariable page_current;
	static FaceVariable cur1;
	FaceVariable _r0;
	FaceVariable _r1;
	Arg _arg;
	FaceVariable _r2;

	xmstrtmp.type = XrmStringToQuark("XmString");
	buf.type = XtQString;
	cur.type = XtQInt;
	page_current.type = XrmStringToQuark("Page");
	cur1.type = XtQInt;
	FaceWriteValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", (XtArgVal)*((XtArgVal*)call_data), (XrmQuark)XtQAny);
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 4 */
	cur.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) getPageCurrent((Widget)FmnotebookWidget);	/* XFM 5 */
	_r0.type = XrmStringToQuark("Page");
	page_current.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) ((XtArgVal)cur.value + (XtArgVal)1);	/* XFM 6 */
	_r0.type = XtQInt;
	cur1.value = (XtArgVal) _r0.value;
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "maxpages", &_r0);	/* XFM 7 */
	_r1.value = (XtArgVal) ((XtArgVal)cur.value <= (XtArgVal)_r0.value);
	if(_r1.value){
		_r0.value = (XtArgVal) cur1.value;	/* XFM 8 */
		XtSetArg(_arg, "pageNumber", _r0.value);
		XtSetValues((Widget)FmscrolltextWidget, &_arg, 1);
	}
	if(page_current.value){	/* XFM 10 */
		_r0.value = (XtArgVal) (*(((XtArgVal*)(page_current.value))+(0)));	/* XFM 12 */
		if(_r0.value){
			_r0.value = (XtArgVal) (*(((XtArgVal*)(page_current.value))+(0)));	/* XFM 13 */
			_r0.type = XtQString;
			_r1.value = (XtArgVal) _r0.value;
			XtSetArg(_arg, "value", _r1.value);
			XtSetValues((Widget)FmtextWidget, &_arg, 1);
		} else {
			_r0.value = (XtArgVal) "";	/* XFM 15 */
			XtSetArg(_arg, "value", _r0.value);
			XtSetValues((Widget)FmtextWidget, &_arg, 1);
		}
		_r0.value = (XtArgVal) (*(((XtArgVal*)(page_current.value))+(3)));	/* XFM 16 */
		if(_r0.value){
			_r0.value = (XtArgVal) (*(((XtArgVal*)(page_current.value))+(3)));	/* XFM 17 */
			_r0.type = XtQString;
			buf.value = (XtArgVal) _r0.value;
		} else {
			_r0.value = (XtArgVal) XtMalloc((int)80);	/* XFM 20 */
			_r0.type = XtQString;
			buf.value = (XtArgVal) _r0.value;
			sprintf((String)buf.value, (String)"Page %d (Bad Page)", (int)cur1.value);	/* XFM 21 */
		}
	} else {
		_r0.value = (XtArgVal) "";	/* XFM 26 */
		XtSetArg(_arg, "value", _r0.value);
		XtSetValues((Widget)FmtextWidget, &_arg, 1);
		sprintf((String)buf.value, (String)"Page %d (Bad Page)", (int)cur1.value);	/* XFM 27 */
	}
	_r0.value = (XtArgVal) XmStringCreateLocalized((String)buf.value);	/* XFM 29 */
	_r0.type = XrmStringToQuark("XmString");
	xmstrtmp.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) (*(((XtArgVal*)(page_current.value))+(6)));	/* XFM 30 */
	_r0.type = XtQInt;
	_r1.value = (XtArgVal) _r0.value;
	XtSetArg(_arg, "topCharacter", _r1.value);
	XtSetValues((Widget)FmtextWidget, &_arg, 1);
	_r0.value = (XtArgVal) (*(((XtArgVal*)(page_current.value))+(7)));	/* XFM 31 */
	_r0.type = XtQInt;
	_r1.value = (XtArgVal) _r0.value;
	XtSetArg(_arg, "cursorPosition", _r1.value);
	XtSetValues((Widget)FmtextWidget, &_arg, 1);
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 32 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value + (XtArgVal)1);
	_r1.type = XtQInt;
	_r2.value = (XtArgVal) _r1.value;
	XtSetArg(_arg, "pageNumber", _r2.value);
	XtSetValues((Widget)FmlabelWidget, &_arg, 1);
	_r0.value = (XtArgVal) xmstrtmp.value;	/* XFM 33 */
	XtSetArg(_arg, "labelString", _r0.value);
	XtSetValues((Widget)FmlabelWidget, &_arg, 1);
	XmStringFree((XmString)xmstrtmp.value);	/* XFM 34 */
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.selectedPulldown.properties */
static void FmpropertiesWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable page_cur;
	FaceVariable _r0;
	FaceVariable _r1;
	Arg _arg;

	page_cur.type = XrmStringToQuark("Page");
	_r0.value = (XtArgVal) getPageCurrent((Widget)FmnotebookWidget);	/* XFM 3 */
	_r0.type = XrmStringToQuark("Page");
	page_cur.value = (XtArgVal) _r0.value;
	if(page_cur.value){	/* XFM 4 */
		_r0.value = (XtArgVal) (*(((XtArgVal*)(page_cur.value))+(3)));	/* XFM 6 */
		if(_r0.value){
			_r0.value = (XtArgVal) (*(((XtArgVal*)(page_cur.value))+(3)));	/* XFM 8 */
			_r0.type = XtQString;
			_r1.value = (XtArgVal) _r0.value;
			XtSetArg(_arg, "value", _r1.value);
			XtSetValues((Widget)FmeditTFWidget, &_arg, 1);
		} else {
			_r0.value = (XtArgVal) "";	/* XFM 11 */
			XtSetArg(_arg, "value", _r0.value);
			XtSetValues((Widget)FmeditTFWidget, &_arg, 1);
		}
		_r0.value = (XtArgVal) (*(((XtArgVal*)(page_cur.value))+(1)));	/* XFM 13 */
		if(_r0.value){
			_r0.value = (XtArgVal) (*(((XtArgVal*)(page_cur.value))+(1)));	/* XFM 15 */
			_r0.type = XtQString;
			_r1.value = (XtArgVal) _r0.value;
			XtSetArg(_arg, "value", _r1.value);
			XtSetValues((Widget)FmmajorTFWidget, &_arg, 1);
		} else {
			_r0.value = (XtArgVal) "";	/* XFM 18 */
			XtSetArg(_arg, "value", _r0.value);
			XtSetValues((Widget)FmmajorTFWidget, &_arg, 1);
		}
		_r0.value = (XtArgVal) (*(((XtArgVal*)(page_cur.value))+(2)));	/* XFM 19 */
		if(_r0.value){
			_r0.value = (XtArgVal) (*(((XtArgVal*)(page_cur.value))+(2)));	/* XFM 21 */
			_r0.type = XtQString;
			_r1.value = (XtArgVal) _r0.value;
			XtSetArg(_arg, "value", _r1.value);
			XtSetValues((Widget)FmminorTFWidget, &_arg, 1);
		} else {
			_r0.value = (XtArgVal) "";	/* XFM 24 */
			XtSetArg(_arg, "value", _r0.value);
			XtSetValues((Widget)FmminorTFWidget, &_arg, 1);
		}
		FmShowWidget((Widget)FmEditPageWidget);	/* XFM 25 */
	}
}

extern void NewPage(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
);


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.selectedPulldown.new */
static void FmnewWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable modifPage;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;
	Arg _arg;

	NewPage(widget, client_data, call_data);	/* XFM 2 */
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 4 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value + (XtArgVal)1);
	_r1.type = XtQInt;
	_r2.value = (XtArgVal) _r1.value;
	XtSetArg(_arg, "currentPageNumber", _r2.value);
	XtSetValues((Widget)FmnotebookWidget, &_arg, 1);
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "maxpages", &_r0);	/* XFM 5 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value + (XtArgVal)1);
	_r1.type = XtQInt;
	_r2.value = (XtArgVal) _r1.value;
	XtSetArg(_arg, "lastPageNumber", _r2.value);
	XtSetValues((Widget)FmnotebookWidget, &_arg, 1);
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 6 */
	modifPage.value = (XtArgVal) _r0.value;
	modifPage.type = _r0.type;
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.selectedPulldown.setected_delete */
static void Fmsetected_deleteWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FmShowWidget((Widget)FmdeletePageWidget);	/* XFM 4 */
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.selectedPulldown.exit1 */
static void Fmexit1Widget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	exit((int)0);
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.FilePulldown.new_selected */
static void Fmnew_selectedWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	XnslReadDB((String)"untitled.todo");	/* XFM 3 */
	FaceWriteValue((Widget)widget, (Widget)FmsessionShell0Widget, "todo_filename", (XtArgVal)"untitled.todo", (XrmQuark)XtQString);	/* XFM 4 */
	FaceWriteValue((Widget)widget, (Widget)FmnotebookWidget, "modifPage", (XtArgVal)0, (XrmQuark)XtQInt);	/* XFM 5 */
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.FilePulldown.open_selected */
static void Fmopen_selectedWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable filename;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;

	filename.type = XtQString;
	_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*fsbox");	/* XFM 4 */
	FaceReadValue((Widget)widget, (Widget)FmsessionShell0Widget, "todo_filename", &_r1);
	_r2.value = (XtArgVal) FmCallValue((Widget)_r0.value, (String)"GetFileName", (int)2, _r1.value, (String)"*");
	_r2.type = XtQAny;
	filename.value = (XtArgVal) _r2.value;
	_r0.value = (XtArgVal) (! (XtArgVal)filename.value);	/* XFM 5 */
	if(_r0.value){
		return;	/* XFM 6 */
	}
	XnslReadDB((String)filename.value);	/* XFM 7 */
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.FilePulldown.save */
static void FmsaveWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;

	FaceReadValue((Widget)widget, (Widget)FmsessionShell0Widget, "todo_filename", &_r0);	/* XFM 4 */
	XnslSaveDB((String)_r0.value);
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.FilePulldown.saveas */
static void FmsaveasWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable filename;
	FaceVariable _r0;

	filename.type = XtQString;
	FaceReadValue((Widget)widget, (Widget)FmsessionShell0Widget, "todo_filename", &_r0);	/* XFM 4 */
	filename.value = (XtArgVal) _r0.value;
	_r0.value = (XtArgVal) (! (XtArgVal)filename.value);	/* XFM 6 */
	if(_r0.value){
		return;	/* XFM 7 */
	}
	XnslSaveDB((String)filename.value);	/* XFM 9 */
}


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.FilePulldown.exit2 */
static void Fmexit2Widget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	exit((int)0);
}

extern void help_cb(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
);


/* XFM resource activateCallback sessionShell0.mainw.menub.popup_selectedPulldown.helpPulldown.overview */
static void FmoverviewWidget_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	help_cb(widget, client_data, call_data);	/* XFM 2 */
}


/* XFM resource valueChangedCallback sessionShell0.mainw.notebook.scrolltext.text */
static void FmtextWidget_valueChangedCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	*(XtArgVal*)FmGetAv("modified") = (XtArgVal) 1;
}

extern void DoDeletePage(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
);


/* XFM resource okCallback sessionShell0.xmDialogShell2.deletePage */
static void FmdeletePageWidget_okCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable ModifPage;
	FaceVariable _r0;
	FaceVariable _r1;
	FaceVariable _r2;
	Arg _arg;

	DoDeletePage(widget, client_data, call_data);	/* XFM 2 */
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 4 */
	FaceSetResource((Widget)FmnotebookWidget, "currentPageNumber", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "maxpages", &_r0);	/* XFM 5 */
	_r1.value = (XtArgVal) ((XtArgVal)_r0.value + (XtArgVal)1);
	_r1.type = XtQInt;
	_r2.value = (XtArgVal) _r1.value;
	XtSetArg(_arg, "lastPageNumber", _r2.value);
	XtSetValues((Widget)FmnotebookWidget, &_arg, 1);
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 6 */
	ModifPage.value = (XtArgVal) _r0.value;
	ModifPage.type = _r0.type;
}

extern void DoEditPage(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
);


/* XFM resource okCallback sessionShell0.xmDialogShell0_2.EditPage */
static void FmEditPageWidget_okCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable modifPage;
	FaceVariable _r0;

	DoEditPage(widget, client_data, call_data);	/* XFM 2 */
	FaceReadValue((Widget)widget, (Widget)FmnotebookWidget, "currentPage", &_r0);	/* XFM 3 */
	modifPage.value = (XtArgVal) _r0.value;
	modifPage.type = _r0.type;
}

#ifndef false
#define false 0
#endif

/* XFM create proc sessionShell0 */
static void FmsessionShell0Widget_createCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	static FaceVariable bopenOrSave;
	FaceVariable _r0;

	bopenOrSave.type = XtQBoolean;
	bopenOrSave.value = (XtArgVal) False;	/* XFM 12 */
	getFileName((Widget)FmsessionShell0Widget);	/* XFM 17 */
	FaceReadValue((Widget)widget, (Widget)FmsessionShell0Widget, "todo_filename", &_r0);	/* XFM 18 */
	XnslReadDB((String)_r0.value);
	FaceWriteValue((Widget)widget, (Widget)FmnotebookWidget, "ModifPage", (XtArgVal)0, (XrmQuark)XtQInt);	/* XFM 19 */
}


/* XFM create proc sessionShell0.mainw.menub */
static void FmmenubWidget_createCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	Arg _arg;

	_r0.value = (XtArgVal) FmhelpWidget;
	XtSetArg(_arg, "menuHelpWidget", _r0.value);
	XtSetValues((Widget)FmmenubWidget, &_arg, 1);
}

/* XFM private */
Widget
_FmCreatetodo(
#if NeedFunctionPrototypes
String name, Widget parent, Widget * toplevels, Cardinal num_toplevels, Widget ** widgets_return, Cardinal * num_widgets_return, Arg* avs, Cardinal num_avs, Arg* user_args, Cardinal num_user_args, Boolean manage_top_objects, XtPointer _this)
#else
name, parent, toplevels, num_toplevels, widgets_return, num_widgets_return, avs, num_avs, user_args, num_user_args, manage_top_objects, _this)
String name;
Widget parent;
Widget * toplevels;
Cardinal num_toplevels;
Widget ** widgets_return;
Cardinal * num_widgets_return;
Arg* avs;
Cardinal num_avs;
Arg* user_args;
Cardinal num_user_args;
Boolean manage_top_objects;
XtPointer _this;
#endif
{
	Arg args[109];
	Cardinal nargs, i;
	XrmValue from, to;
	String app_name, app_class;

	/* XFM create sessionShell0 */
	if(toplevels && 0 < num_toplevels && toplevels[0]){
		FmsessionShell0Widget = toplevels[0];
	} else {
	nargs = 0;
	XtSetArg(args[nargs], "x", 395); nargs++;
	XtSetArg(args[nargs], "y", 249); nargs++;
	XtSetArg(args[nargs], "width", 447); nargs++;
	XtSetArg(args[nargs], "height", 333); nargs++;
	for(i = 0; i < num_user_args; i++){
		args[nargs].name = user_args[i].name;
		args[nargs].value = user_args[i].value;
		nargs++;
	}
	XtGetApplicationNameAndClass(XtDisplay(parent), &app_name, &app_class);
	FmsessionShell0Widget = XtAppCreateShell(app_name, app_class, sessionShellWidgetClass, XtDisplay(parent), args, nargs);
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)FmsessionShell0Widget, (Widget*)0, &arg, 1);
	}
	FmCreateValue("modified", (XtCallbackProc)0, (XtCallbackProc)0, "Int", 0, 0, 0, 1, 0, (Widget)FmsessionShell0Widget, (Widget*)0, avs, num_avs);
	FmCreateValue("todo_filename", (XtCallbackProc)todo_filename_FmsessionShell0Widget_get, (XtCallbackProc)todo_filename_FmsessionShell0Widget_set, "String", 0, 0, 0, 1, 0, (Widget)FmsessionShell0Widget, (Widget*)0, avs, num_avs);

	/* XFM create sessionShell0.mainw */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 447); nargs++;
	XtSetArg(args[nargs], "height", 333); nargs++;
	FmmainwWidget = XtCreateManagedWidget("mainw", xmMainWindowWidgetClass, FmsessionShell0Widget, args, nargs);

	/* XFM create sessionShell0.mainw.menub */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 447); nargs++;
	XtSetArg(args[nargs], "height", 31); nargs++;
	FmmenubWidget = XmCreateMenuBar(FmmainwWidget, "menub", args, nargs);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown */
	nargs = 0;
	FmselectedPulldownWidget = XmCreatePulldownMenu(FmmenubWidget, "selectedPulldown", args, nargs);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.properties */
	from.addr = "Properties";
	from.size = 11;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "accelerator", "Ctrl<Key>I"); nargs++;
	from.addr = "Ctrl+I";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "acceleratorText", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("s")); nargs++;
	FmpropertiesWidget = XtCreateManagedWidget("properties", xmPushButtonWidgetClass, FmselectedPulldownWidget, args, nargs);
	XtAddCallback(FmpropertiesWidget, "activateCallback", (XtCallbackProc)FmpropertiesWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.new */
	from.addr = "New";
	from.size = 4;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("N")); nargs++;
	FmnewWidget = XtCreateManagedWidget("new", xmPushButtonWidgetClass, FmselectedPulldownWidget, args, nargs);
	XtAddCallback(FmnewWidget, "activateCallback", (XtCallbackProc)FmnewWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.open */
	from.addr = "Open";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("O")); nargs++;
	FmopenWidget = XtCreateManagedWidget("open", xmPushButtonWidgetClass, FmselectedPulldownWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.separator1 */
	nargs = 0;
	Fmseparator1Widget = XtCreateManagedWidget("separator1", xmSeparatorWidgetClass, FmselectedPulldownWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.separator2 */
	nargs = 0;
	Fmseparator2Widget = XtCreateManagedWidget("separator2", xmSeparatorWidgetClass, FmselectedPulldownWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.setected_delete */
	from.addr = "Delete To Trash";
	from.size = 16;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "accelerator", "<Key>osfDelete"); nargs++;
	from.addr = "Delete";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "acceleratorText", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("D")); nargs++;
	XtSetArg(args[nargs], "x", 2); nargs++;
	XtSetArg(args[nargs], "y", 69); nargs++;
	XtSetArg(args[nargs], "width", 149); nargs++;
	XtSetArg(args[nargs], "height", 21); nargs++;
	Fmsetected_deleteWidget = XtCreateManagedWidget("setected_delete", xmPushButtonWidgetClass, FmselectedPulldownWidget, args, nargs);
	XtAddCallback(Fmsetected_deleteWidget, "activateCallback", (XtCallbackProc)Fmsetected_deleteWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.selectedPulldown.exit1 */
	from.addr = "Exit";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmselectedPulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("x")); nargs++;
	Fmexit1Widget = XtCreateManagedWidget("exit1", xmPushButtonWidgetClass, FmselectedPulldownWidget, args, nargs);
	XtAddCallback(Fmexit1Widget, "activateCallback", (XtCallbackProc)Fmexit1Widget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.FilePulldown */
	nargs = 0;
	FmFilePulldownWidget = XmCreatePulldownMenu(FmmenubWidget, "FilePulldown", args, nargs);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.new_selected */
	from.addr = "New";
	from.size = 4;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "accelerator", "Ctrl<Key>N"); nargs++;
	from.addr = "Ctrl+N";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "acceleratorText", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("N")); nargs++;
	Fmnew_selectedWidget = XtCreateManagedWidget("new_selected", xmPushButtonWidgetClass, FmFilePulldownWidget, args, nargs);
	XtAddCallback(Fmnew_selectedWidget, "activateCallback", (XtCallbackProc)Fmnew_selectedWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.open_selected */
	from.addr = "Open";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("O")); nargs++;
	XtSetArg(args[nargs], "accelerator", "Ctrl<Key>O"); nargs++;
	from.addr = "Ctrl+O";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "acceleratorText", *(XmString*)to.addr); nargs++; }
	Fmopen_selectedWidget = XtCreateManagedWidget("open_selected", xmPushButtonWidgetClass, FmFilePulldownWidget, args, nargs);
	XtAddCallback(Fmopen_selectedWidget, "activateCallback", (XtCallbackProc)Fmopen_selectedWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.save */
	from.addr = "Save";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("S")); nargs++;
	XtSetArg(args[nargs], "accelerator", "Ctrl<Key>S"); nargs++;
	from.addr = "Ctrl+S";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "acceleratorText", *(XmString*)to.addr); nargs++; }
	FmsaveWidget = XtCreateManagedWidget("save", xmPushButtonWidgetClass, FmFilePulldownWidget, args, nargs);
	XtAddCallback(FmsaveWidget, "activateCallback", (XtCallbackProc)FmsaveWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.saveas */
	from.addr = "Save As...";
	from.size = 11;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("A")); nargs++;
	FmsaveasWidget = XtCreateManagedWidget("saveas", xmPushButtonWidgetClass, FmFilePulldownWidget, args, nargs);
	XtAddCallback(FmsaveasWidget, "activateCallback", (XtCallbackProc)FmsaveasWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.separator1 */
	nargs = 0;
	Fmseparator1Widget_1 = XtCreateManagedWidget("separator1", xmSeparatorWidgetClass, FmFilePulldownWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.print */
	from.addr = "Print...";
	from.size = 9;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("P")); nargs++;
	XtSetArg(args[nargs], "accelerator", "Ctrl<Key>P"); nargs++;
	from.addr = "Ctrl+P";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "acceleratorText", *(XmString*)to.addr); nargs++; }
	FmprintWidget = XtCreateManagedWidget("print", xmPushButtonWidgetClass, FmFilePulldownWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.seperator2 */
	nargs = 0;
	Fmseperator2Widget = XtCreateManagedWidget("seperator2", xmSeparatorWidgetClass, FmFilePulldownWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.FilePulldown.exit2 */
	from.addr = "Exit";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmFilePulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("x")); nargs++;
	Fmexit2Widget = XtCreateManagedWidget("exit2", xmPushButtonWidgetClass, FmFilePulldownWidget, args, nargs);
	XtAddCallback(Fmexit2Widget, "activateCallback", (XtCallbackProc)Fmexit2Widget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.File */
	from.addr = "File";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmmenubWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("F")); nargs++;
	XtSetArg(args[nargs], "subMenuId", FmFilePulldownWidget); nargs++;
	FmFileWidget = XtCreateManagedWidget("File", xmCascadeButtonWidgetClass, FmmenubWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.selected */
	from.addr = "Selected";
	from.size = 9;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmmenubWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("S")); nargs++;
	XtSetArg(args[nargs], "subMenuId", FmselectedPulldownWidget); nargs++;
	FmselectedWidget = XtCreateManagedWidget("selected", xmCascadeButtonWidgetClass, FmmenubWidget, args, nargs);

	/* XFM create sessionShell0.mainw.menub.helpPulldown */
	nargs = 0;
	FmhelpPulldownWidget = XmCreatePulldownMenu(FmmenubWidget, "helpPulldown", args, nargs);

	/* XFM create sessionShell0.mainw.menub.helpPulldown.overview */
	from.addr = "Overview";
	from.size = 9;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmhelpPulldownWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("O")); nargs++;
	FmoverviewWidget = XtCreateManagedWidget("overview", xmPushButtonWidgetClass, FmhelpPulldownWidget, args, nargs);
	XtAddCallback(FmoverviewWidget, "activateCallback", (XtCallbackProc)FmoverviewWidget_activateCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.menub.help */
	from.addr = "Help";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmmenubWidget, XmRString, &from, XmRXmString, &to);
	nargs = 0;
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "mnemonic", XStringToKeysym("H")); nargs++;
	XtSetArg(args[nargs], "subMenuId", FmhelpPulldownWidget); nargs++;
	FmhelpWidget = XtCreateManagedWidget("help", xmCascadeButtonWidgetClass, FmmenubWidget, args, nargs);
	XtManageChild(FmmenubWidget);
	FmmenubWidget_createCallback(FmmenubWidget, (XtPointer)0, 0);

	/* XFM create sessionShell0.mainw.notebook */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 31); nargs++;
	XtSetArg(args[nargs], "width", 447); nargs++;
	XtSetArg(args[nargs], "height", 302); nargs++;
	XtSetArg(args[nargs], "lastPageNumber", 100); nargs++;
	FmnotebookWidget = XtCreateManagedWidget("notebook", xmNotebookWidgetClass, FmmainwWidget, args, nargs);
	FmCreateValue("ModifPage", (XtCallbackProc)0, (XtCallbackProc)ModifPage_FmnotebookWidget_set, "Int", 0, 0, 0, 0, 0, (Widget)FmnotebookWidget, (Widget*)0, avs, num_avs);
	FmCreateValue("currentPage", (XtCallbackProc)0, (XtCallbackProc)0, "Int", 0, 0, 0, 0, 0, (Widget)FmnotebookWidget, (Widget*)0, avs, num_avs);
	FmCreateValue("maxpages", (XtCallbackProc)0, (XtCallbackProc)0, "Int", 0, 0, 0, 0, 0, (Widget)FmnotebookWidget, (Widget*)0, avs, num_avs);

	/* XFM create sessionShell0.mainw.notebook.scrolltext */
	nargs = 0;
	XtSetArg(args[nargs], "x", 40); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 397); nargs++;
	XtSetArg(args[nargs], "height", 264); nargs++;
	FmscrolltextWidget = XtCreateManagedWidget("scrolltext", xmScrolledWindowWidgetClass, FmnotebookWidget, args, nargs);

	/* XFM create sessionShell0.mainw.notebook.scrolltext.text */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 378); nargs++;
	XtSetArg(args[nargs], "height", 245); nargs++;
	XtSetArg(args[nargs], "editMode", XmMULTI_LINE_EDIT); nargs++;
	FmtextWidget = XtCreateManagedWidget("text", xmTextWidgetClass, FmscrolltextWidget, args, nargs);
	XtAddCallback(FmtextWidget, "valueChangedCallback", (XtCallbackProc)FmtextWidget_valueChangedCallback, (XtPointer)0);

	/* XFM create sessionShell0.mainw.notebook.label */
	nargs = 0;
	XtSetArg(args[nargs], "x", 40); nargs++;
	XtSetArg(args[nargs], "y", 267); nargs++;
	XtSetArg(args[nargs], "width", 307); nargs++;
	XtSetArg(args[nargs], "height", 25); nargs++;
	FmlabelWidget = XtCreateManagedWidget("label", xmLabelWidgetClass, FmnotebookWidget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell2 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 653); nargs++;
	XtSetArg(args[nargs], "y", 438); nargs++;
	XtSetArg(args[nargs], "width", 382); nargs++;
	XtSetArg(args[nargs], "height", 197); nargs++;
	FmxmDialogShell2Widget = XtCreatePopupShell("xmDialogShell2", xmDialogShellWidgetClass, FmsessionShell0Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell2.deletePage */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 382); nargs++;
	XtSetArg(args[nargs], "height", 197); nargs++;
	from.addr = "Page Delete Dialog";
	from.size = 19;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmxmDialogShell2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "dialogTitle", *(XmString*)to.addr); nargs++; }
	XtSetArg(args[nargs], "dialogStyle", XmDIALOG_PRIMARY_APPLICATION_MODAL); nargs++;
	from.addr = "Delete";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmxmDialogShell2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "okLabelString", *(XmString*)to.addr); nargs++; }
	from.addr = "Really delete this page?";
	from.size = 25;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmxmDialogShell2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "messageString", *(XmString*)to.addr); nargs++; }
	FmdeletePageWidget = XtCreateWidget("deletePage", xmMessageBoxWidgetClass, FmxmDialogShell2Widget, args, nargs);
	XtAddCallback(FmdeletePageWidget, "okCallback", (XtCallbackProc)FmdeletePageWidget_okCallback, (XtPointer)0);

	/* XFM create sessionShell0.xmDialogShell0_2 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 723); nargs++;
	XtSetArg(args[nargs], "y", 419); nargs++;
	XtSetArg(args[nargs], "width", 242); nargs++;
	XtSetArg(args[nargs], "height", 234); nargs++;
	FmxmDialogShell0_2Widget = XtCreatePopupShell("xmDialogShell0_2", xmDialogShellWidgetClass, FmsessionShell0Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 242); nargs++;
	XtSetArg(args[nargs], "height", 234); nargs++;
	XtSetArg(args[nargs], "dialogType", XmDIALOG_TEMPLATE); nargs++;
	from.addr = "Ok";
	from.size = 3;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmxmDialogShell0_2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "okLabelString", *(XmString*)to.addr); nargs++; }
	from.addr = "Cancel";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmxmDialogShell0_2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "cancelLabelString", *(XmString*)to.addr); nargs++; }
	from.addr = "Page Edit Dialog";
	from.size = 17;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(FmxmDialogShell0_2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "dialogTitle", *(XmString*)to.addr); nargs++; }
	FmEditPageWidget = XtCreateWidget("EditPage", xmMessageBoxWidgetClass, FmxmDialogShell0_2Widget, args, nargs);
	XtAddCallback(FmEditPageWidget, "okCallback", (XtCallbackProc)FmEditPageWidget_okCallback, (XtPointer)0);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc */
	nargs = 0;
	XtSetArg(args[nargs], "x", 11); nargs++;
	XtSetArg(args[nargs], "y", 11); nargs++;
	XtSetArg(args[nargs], "width", 220); nargs++;
	XtSetArg(args[nargs], "height", 149); nargs++;
	FmrcWidget = XtCreateManagedWidget("rc", xmRowColumnWidgetClass, FmEditPageWidget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 3); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 214); nargs++;
	XtSetArg(args[nargs], "height", 37); nargs++;
	XtSetArg(args[nargs], "orientation", XmHORIZONTAL); nargs++;
	Fmrc2Widget = XtCreateManagedWidget("rc2", xmRowColumnWidgetClass, FmrcWidget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2.label1 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 3); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 100); nargs++;
	XtSetArg(args[nargs], "height", 10); nargs++;
	from.addr = "Label:";
	from.size = 7;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(Fmrc2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	Fmlabel1Widget = XtCreateManagedWidget("label1", xmLabelGadgetClass, Fmrc2Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2.editTF */
	nargs = 0;
	XtSetArg(args[nargs], "x", 46); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 138); nargs++;
	XtSetArg(args[nargs], "height", 31); nargs++;
	FmeditTFWidget = XtCreateManagedWidget("editTF", xmTextFieldWidgetClass, Fmrc2Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2_2 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 3); nargs++;
	XtSetArg(args[nargs], "y", 43); nargs++;
	XtSetArg(args[nargs], "width", 214); nargs++;
	XtSetArg(args[nargs], "height", 37); nargs++;
	XtSetArg(args[nargs], "orientation", XmHORIZONTAL); nargs++;
	Fmrc2_2Widget = XtCreateManagedWidget("rc2_2", xmRowColumnWidgetClass, FmrcWidget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2_2.label2 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 3); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 100); nargs++;
	XtSetArg(args[nargs], "height", 10); nargs++;
	from.addr = "Major Tab:";
	from.size = 11;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(Fmrc2_2Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	Fmlabel2Widget = XtCreateManagedWidget("label2", xmLabelGadgetClass, Fmrc2_2Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2_2.majorTF */
	nargs = 0;
	XtSetArg(args[nargs], "x", 70); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 138); nargs++;
	XtSetArg(args[nargs], "height", 31); nargs++;
	FmmajorTFWidget = XtCreateManagedWidget("majorTF", xmTextFieldWidgetClass, Fmrc2_2Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2_3 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 3); nargs++;
	XtSetArg(args[nargs], "y", 83); nargs++;
	XtSetArg(args[nargs], "width", 214); nargs++;
	XtSetArg(args[nargs], "height", 37); nargs++;
	XtSetArg(args[nargs], "orientation", XmHORIZONTAL); nargs++;
	Fmrc2_3Widget = XtCreateManagedWidget("rc2_3", xmRowColumnWidgetClass, FmrcWidget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2_3.label3 */
	nargs = 0;
	XtSetArg(args[nargs], "x", 3); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 100); nargs++;
	XtSetArg(args[nargs], "height", 10); nargs++;
	from.addr = "Minor Tab:";
	from.size = 11;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(Fmrc2_3Widget, XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	Fmlabel3Widget = XtCreateManagedWidget("label3", xmLabelGadgetClass, Fmrc2_3Widget, args, nargs);

	/* XFM create sessionShell0.xmDialogShell0_2.EditPage.rc.rc2_3.minorTF */
	nargs = 0;
	XtSetArg(args[nargs], "x", 70); nargs++;
	XtSetArg(args[nargs], "y", 3); nargs++;
	XtSetArg(args[nargs], "width", 138); nargs++;
	XtSetArg(args[nargs], "height", 31); nargs++;
	FmminorTFWidget = XtCreateManagedWidget("minorTF", xmTextFieldWidgetClass, Fmrc2_3Widget, args, nargs);
	if(_this)
		FaceWriteValue((Widget)FmsessionShell0Widget, (Widget)FmsessionShell0Widget, "modified", (XtArgVal)"0", (XrmQuark)XtQString);
	else
		FaceInitValue((Widget)FmsessionShell0Widget, (Widget)FmsessionShell0Widget, "modified", (XtArgVal)"0", (XrmQuark)XtQString);
	FmsessionShell0Widget_createCallback(FmsessionShell0Widget, (XtPointer)0, 0);

	/* XFM private */

	if(manage_top_objects){
	XtRealizeWidget(FmsessionShell0Widget);
	}

	return(FmsessionShell0Widget);
}

Widget
FmCreatetodo(
#if NeedFunctionPrototypes
String name, Widget parent, Arg* args, Cardinal num_args)
#else
name, parent, args, num_args)
String name;
Widget parent;
Arg* args;
Cardinal num_args;
#endif
{
	return(_FmCreatetodo(name, parent, 0, 0, 0, 0, 0, 0, args, num_args, True, 0));
}
