/*
 *  C file generated by XFaceMaker Version 4.1.
 *  Do not remove this comment.
 *  Timestamp:           1155831402
 */

/*
 *  XFaceMaker 4.0  Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin user  ##*/
#include <pwd.h>
#include <unistd.h>
/* X include files */
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xatom.h>
/* Motif include files */
#include <Xm/CascadeBG.h>
#include <Xm/FileSB.h>
#include <Xm/Label.h>
#include <Xm/MainW.h>
#include <Xm/Notebook.h>
#include <Xm/PushBG.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrolledW.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>

#include "page.h"
extern Page pages[];
struct passwd *user;
extern Widget FmsessionShell0Widget, FmmainwWidget, FmmenubWidget, FmselectedPulldownWidget, FmpropertiesWidget,
		 FmnewWidget, FmopenWidget, Fmseparator1Widget, Fmseparator2Widget, Fmsetected_deleteWidget,
		 FmexitWidget, FmFilePulldownWidget, FmnewWidget_1, FmopenWidget_1, FmsaveWidget,
		 FmsaveasWidget, Fmseparator1Widget_1, FmprintWidget, Fmseperator2Widget, FmexitWidget_1,
		 FmFileWidget, FmselectedWidget, FmhelpPulldownWidget, FmoverviewWidget, FmhelpWidget,
		 FmnotebookWidget, FmscrolltextWidget, FmtextWidget, FmlabelWidget, FmxmDialogShell0Widget,
		 Fmfile_dialogWidget, FmxmDialogShell2Widget, FmdeletePageWidget, FmxmDialogShell0_2Widget, FmEditPageWidget,
		 FmrcWidget, Fmrc2Widget, Fmlabel1Widget, FmeditTFWidget, Fmrc2_2Widget,
		 Fmlabel2Widget, FmmajorTFWidget, Fmrc2_3Widget, Fmlabel3Widget, FmminorTFWidget;
/*## end user  ##*/

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' todo  ##*/
int modified;
String todo_filename;
int ModifPage;
int currentPage;
int maxpages;
/*## end `active_values' todo  ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' getPageCurrent  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
XtArgVal getPageCurrent(Widget w)
#else
XtArgVal getPageCurrent(w)
Widget w;
#endif
{
/*## begin user  ##*/
FmGetActiveValue(w, "currentPage");
if( pages[currentPage])
	return pages[currentPage];
else return NULL;
/*## end user  ##*/
}
/*## end `function' getPageCurrent  ##*/
/*## begin `function' XnslReadDB  ##*/
/*## begin user  ##*/
extern void ReadDB(String str);
/*## end user  ##*/
#if NeedFunctionPrototypes
void XnslReadDB(String str)
#else
void XnslReadDB(str)
String str;
#endif
{
/*## begin user  ##*/
ReadDB(str);
/*## end user  ##*/
}
/*## end `function' XnslReadDB  ##*/
/*## begin `function' XnslSaveDB  ##*/
/*## begin user  ##*/
extern void SaveDB(String str);
/*## end user  ##*/
#if NeedFunctionPrototypes
void XnslSaveDB(String str)
#else
void XnslSaveDB(str)
String str;
#endif
{
/*## begin user  ##*/
SaveDB(str);
/*## end user  ##*/
}
/*## end `function' XnslSaveDB  ##*/
/*## begin `function' getFileName  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void getFileName(Widget w)
#else
void getFileName(w)
Widget w;
#endif
{
/*## begin user  ##*/
int i;
 char temppath[256];

  user = getpwuid(getuid());
  for (i = 0; i < MAXPAGES; i++) {
    		pages[i] = NULL;
  }
   FmGetActiveValue(w, "todo_filename");
  if (todo_filename == NULL) {
    strcpy(temppath, user->pw_dir);
    strcat(temppath, "/.todo");
    todo_filename = XtNewString(temppath);
  } else {
    /* Copy the string for consistency */
    todo_filename = XtNewString(todo_filename);
  }

  FmSetActiveValue(w, "todo_filename");
/*## end user  ##*/
}
/*## end `function' getFileName  ##*/
/*## begin user  ##*/

void 
AdjustPages(int startpage, int ins) 
{
  int i;

  /* ins is either +1 or -1 for insert or delete a page */

  if (ins > 0) {
    for(i = maxpages; i >= startpage; i--)
      pages[i + 1] = pages[i];
    maxpages += 1;
  } else {
    for(i = startpage; i <= maxpages; i++)
      pages[i] = pages[i + 1];
    maxpages -= 1;
  }
}

void FixPages() {
  int i;
  Arg args[2];

  /* Now scan the pages and fix the tabs */
  for (i = 0; i <= maxpages; i++) {
    XtSetArg(args[0], XmNpageNumber, (i + 1));
    if (pages[i] -> majorPB != (Widget) 0)
      XtSetValues(pages[i] -> majorPB, args, 1);
    if (pages[i] -> minorPB != (Widget) 0)
      XtSetValues(pages[i] -> minorPB, args, 1);
  }
}

/* This function removes leading and trailing whitespace.  It
   deallocates the original string and returns a brand new string */

char* 
Trim(char* str)
{
  char *new;
  int first, last;
  int length;

  if (str == NULL) return(XtNewString(""));

  length = strlen(str);

  for(first = 0; first < length && isspace(str[first]); first++);
  for(last = length - 1; last > first && isspace(str[last]); last--);

  if (! isspace(str[last])) last++; /* Last needs to be adjusted */

  if (first == last) /* Empty */
    {
      free(str);
      return(strdup(""));
    }
  else
    {
      new = XtMalloc(last - first + 1); /* Don't forget last 0 */
      strncpy(new, &str[first], last - first);
      new[last - first] = 0;
      free(str);
      return(new);
    }
}

#define WIDGET_TABLE ((Widget*)client_data)
void NewPage(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
)
{
  Arg args[2];

  FmGetActiveValue(FmsessionShell0Widget,"currentPage" );
  FmGetActiveValue(FmsessionShell0Widget,"modified" );
  
  if (modified && pages[currentPage] != NULL) {
    if (pages[currentPage] -> page != NULL) 
      XtFree(pages[currentPage] -> page);
     pages[currentPage] -> page = XmTextGetString(FmtextWidget);
  }
  AdjustPages(currentPage, 1);
  pages[currentPage] = AllocPage();
  FixPages();

  FmSetActiveValue(FmsessionShell0Widget,"currentPage" );
  FmSetActiveValue(FmsessionShell0Widget,"modified" );

}
void help_cb(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
){

}

extern void DoDeletePage(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
)
{
Arg args[2];

  FmGetActiveValue(FmsessionShell0Widget,"currentPage" );
  FmGetActiveValue(FmsessionShell0Widget,"maxpages" );

  if (pages[currentPage] != NULL) {
    if (pages[currentPage] -> page != NULL) XtFree(pages[currentPage] -> page);
    if (pages[currentPage] -> minorPB != (Widget) 0)
      XtDestroyWidget(pages[currentPage] -> minorPB);
    if (pages[currentPage] -> majorPB != (Widget) 0)
      XtDestroyWidget(pages[currentPage] -> majorPB);
    XtFree((XtPointer) pages[currentPage]);
  }
  pages[currentPage] = NULL;
  AdjustPages(currentPage, -1);

  /* If there are no more pages left,  then create a blank one */
  if (maxpages < 0) {
    pages[0] = AllocPage();
    pages[0] -> page = XtMalloc(2);
    pages[0] -> page[0] = 0;
    maxpages = 0;
  }

  FixPages();

  FmSetActiveValue(FmsessionShell0Widget,"currentPage" );
  FmSetActiveValue(FmsessionShell0Widget,"maxpages" );

}

void DoEditPage(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data
#endif /* NeedFunctionPrototypes */
)
{
  char *temp;
  XmString tstr;
  Arg args[5];
  int i;

  FmGetActiveValue(FmsessionShell0Widget,"currentPage" );
  FmGetActiveValue(FmsessionShell0Widget,"maxpages" );

  pages[currentPage] -> label = XmTextFieldGetString(FmeditTFWidget);

  if (pages[currentPage] -> minorTab != NULL)
    XtFree(pages[currentPage] -> minorTab);
  temp = XmTextGetString(FmminorTFWidget);
  temp = Trim(temp);
  if (strlen(temp) > 0)
    pages[currentPage] -> minorTab = temp;
  else {
    XtFree(temp);
    pages[currentPage] -> minorTab = NULL;
    if (pages[currentPage] -> minorPB)
      XtUnmanageChild(pages[currentPage] -> minorPB);
  }

  if (pages[currentPage] -> majorTab != NULL)
    XtFree(pages[currentPage] -> majorTab);
  temp = XmTextGetString(FmmajorTFWidget);
  temp = Trim(temp);
  if (strlen(temp) > 0) 
    pages[currentPage] -> majorTab = temp;
  else {
    XtFree(temp);
    pages[currentPage] -> majorTab = NULL;
    if (pages[currentPage] -> majorPB)
      XtUnmanageChild(pages[currentPage] -> majorPB);
  }

  if (pages[currentPage] -> majorTab != NULL) {
    if (pages[currentPage] -> majorPB == (Widget) 0) {
      i = 0;
      XtSetArg(args[i], XmNpageNumber, currentPage + 1); i++;
      XtSetArg(args[i], XmNnotebookChildType, XmMAJOR_TAB); i++;
      XtSetArg(args[i], XmNshadowThickness, 1); i++;
      pages[currentPage] -> majorPB =
	XmCreatePushButton(FmnotebookWidget, "atab", args, i);
    }
    tstr = XmStringGenerate(pages[currentPage] -> majorTab, NULL, 
			    XmCHARSET_TEXT, NULL);
    XtSetArg(args[0], "labelString", tstr);
    XtSetValues(pages[currentPage] -> majorPB, args, 1);
    XtManageChild(pages[currentPage] -> majorPB);
  }

  if (pages[currentPage] -> minorTab != NULL) {
    if (pages[currentPage] -> minorPB == (Widget) 0) {
      i = 0;
      XtSetArg(args[i], XmNpageNumber, currentPage + 1); i++;
      XtSetArg(args[i], XmNnotebookChildType, XmMINOR_TAB); i++;
      XtSetArg(args[i], XmNshadowThickness, 1); i++;
      pages[currentPage] -> minorPB =
	XmCreatePushButton(FmnotebookWidget, "atab", args, i);
    }
    tstr = XmStringGenerate(pages[currentPage] -> minorTab, NULL, 
			    XmCHARSET_TEXT, NULL);
    XtSetArg(args[0], "labelString", tstr);
    XtSetValues(pages[currentPage] -> minorPB, args, 1);
    XtManageChild(pages[currentPage] -> minorPB);
  }

  /* Get contents before update */
  XtFree(pages[currentPage] -> page);
  pages[currentPage] -> page = XmTextGetString(FmtextWidget);

  FmSetActiveValue(FmsessionShell0Widget,"currentPage" );
  FmSetActiveValue(FmsessionShell0Widget,"maxpages" );
  
}

/*## end user  ##*/
