/*
 *  C file generated by XFaceMaker Version 4.1.
 *  Do not remove this comment.
 *  Timestamp:           1155831402
 */

/*
 *  XFaceMaker 4.0 Application Functions Declarations.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif
/*## 					begin pattern define [ VARNAME left (length _XFM_EXT_BUILD_INCLUDES) == _XFM_EXT_BUILD_INCLUDES ] ##*/
/*## VALUE ##*/
/*## 					end pattern ##*/

/*## begin pattern `active_values' ##*/
/*## $$extern AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' todo  ##*/
extern int modified;
extern String todo_filename;
extern int ModifPage;
extern int currentPage;
extern int maxpages;
/*## end `active_values' todo  ##*/

#if NeedFunctionPrototypes
/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## extern CTYPE CNAME($$CARGTYPES ARGNAMES$, $); ##*/
/*## end pattern `function' ##*/
/*## begin `function' getPageCurrent  ##*/
extern XtArgVal getPageCurrent(Widget w);
/*## end `function' getPageCurrent  ##*/
/*## begin `function' XnslReadDB  ##*/
extern void XnslReadDB(String str);
/*## end `function' XnslReadDB  ##*/
/*## begin `function' XnslSaveDB  ##*/
extern void XnslSaveDB(String str);
/*## end `function' XnslSaveDB  ##*/
/*## begin `function' getFileName  ##*/
extern void getFileName(Widget w);
/*## end `function' getFileName  ##*/
#else /* NeedFunctionPrototypes */
/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## extern CTYPE CNAME(); ##*/
/*## end pattern `function' ##*/
/*## begin `function' getPageCurrent  ##*/
extern XtArgVal getPageCurrent();
/*## end `function' getPageCurrent  ##*/
/*## begin `function' XnslReadDB  ##*/
extern void XnslReadDB();
/*## end `function' XnslReadDB  ##*/
/*## begin `function' XnslSaveDB  ##*/
extern void XnslSaveDB();
/*## end `function' XnslSaveDB  ##*/
/*## begin `function' getFileName  ##*/
extern void getFileName();
/*## end `function' getFileName  ##*/
#endif /* NeedFunctionPrototypes */
