/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1034262714
 */

#include <stdio.h>

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#if !defined(XtSpecificationRelease) || XtSpecificationRelease <= 4
#include <X11/Quarks.h>
#else
extern	XrmQuark  XtQBool;
extern	XrmQuark  XtQBoolean;
extern	XrmQuark  XtQColor;
extern	XrmQuark  XtQCursor;
extern	XrmQuark  XtQDimension;
extern	XrmQuark  XtQDisplay;
extern	XrmQuark  XtQFile;
extern	XrmQuark  XtQFont;
extern	XrmQuark  XtQFontStruct;
extern	XrmQuark  XtQInt;
extern	XrmQuark  XtQPixel;
extern	XrmQuark  XtQPixmap;
extern	XrmQuark  XtQPointer;
extern  XrmQuark  XtQPosition;
extern  XrmQuark  XtQShort;
extern	XrmQuark  XtQString;
extern  XrmQuark  XtQUnsignedChar;
extern	XrmQuark  XtQWindow;
#endif
#include <X11/Shell.h>

#include <Xm/Xm.h>

#define	true	True
#define	false	False

#undef  XtMapWidget
#undef  XtUnmapWidget
#define XtMapWidget(widget)     XMapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))
#define XtUnmapWidget(widget)   XUnmapWindow(XtDisplay((Widget)(widget)), XtWindow((Widget)(widget)))

#ifndef _MULTIAPP_H_
#include "MultiApp.h"
#define _MULTIAPP_H_
#endif /* _MULTIAPP_H_ */

#include <Fm.h>

#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/PushB.h>
#include <Xm/PushBG.h>
#include <Xm/Scale.h>

#ifndef _FACE_NO_FLOATS

static float _vtof_(
#if NeedFunctionPrototypes
XtArgVal v)
#else
v)
XtArgVal v;
#endif
{	float f;
	f = *(float*)&v;
	return(f);
}

static XtArgVal _ftov_(
#if NeedFunctionPrototypes
float f)
#else
f)
float f;
#endif
{	float _f = f;
	XtArgVal v;
	*(float*)&v = _f;
	return(v);
}

#endif


extern XrmQuark XtQNone;
extern XrmQuark XtQAny;
extern XrmQuark XtQFloat;
extern XrmQuark XtQWidget;
extern XrmQuark XtQCallback;

typedef struct {
	XtArgVal value;
	XrmQuark type;
} FaceVariable;

#ifdef __cplusplus
extern "C" {
#endif
extern Widget FaceGetWidget(
#if NeedFunctionPrototypes
Widget ref, int level, String names);
#else
);
#endif
extern XtArgVal FaceGetResource(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetResource(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceGetProperty(
#if NeedFunctionPrototypes
Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceSetProperty(
#if NeedFunctionPrototypes
Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern void FmNewAv(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, Widget widget, Widget* group);
#else
);
#endif
extern void FmCreateValue(
#if NeedFunctionPrototypes
String name, XtCallbackProc get, XtCallbackProc set, String type, int storage, int scope, int immediate, int automatic, int genfun, Widget widget, Widget* group, Arg* avs, Cardinal num_avs);
#else
);
#endif
extern int FaceReadValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceFetchValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, FaceVariable* v);
#else
);
#endif
extern int FaceInitValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceInitValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceWriteValue(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern int FaceChangeValueAddress(
#if NeedFunctionPrototypes
Widget ref, Widget w, String name, XtArgVal v, XrmQuark type);
#else
);
#endif
extern String FmInternationalize(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern String FmNewIString(
#if NeedFunctionPrototypes
const char * string);
#else
);
#endif
extern void FmFreeAllIStrings(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern int FmResetDatabase(
#if NeedFunctionPrototypes
Display* display);
#else
);
#endif
extern int FmLoadStringDataBase(
#if NeedFunctionPrototypes
Widget w, char** str, char* name);
#else
);
#endif
extern Widget FmToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
extern Widget FmAppShell(
#if NeedFunctionPrototypes
Widget w);
#else
);
#endif
extern Widget FmRealizeToplevel(
#if NeedFunctionPrototypes
#if !defined(__cplusplus) && !defined(c_plusplus)
void
#endif
);
#else
);
#endif
#ifdef __cplusplus
}
#endif
#define WIDGET_TABLE ((Widget*)client_data)

#ifndef True
#define True 1
#endif

/* XFM set script of av Blink multi.mainform.blink */
static void Blink_WIDGET_3_set(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	Arg _arg;
	XrmValue from, to;

	FaceGetProperty((Widget)WIDGET_TABLE[3], "inited", &_r0);	/* XFM 2 */
	_r1.value = (XtArgVal) (! (XtArgVal)_r0.value);
	if(_r1.value){
		XtSetArg(_arg, "background", &_r0.value);	/* XFM 3 */
		XtGetValues((Widget)WIDGET_TABLE[3], &_arg, 1);
		_r0.type = XtQPixel;
		FaceSetProperty((Widget)WIDGET_TABLE[3], "initial_color", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
		XtSetArg(_arg, "value", &_r0.value);	/* XFM 4 */
		XtGetValues((Widget)WIDGET_TABLE[7], &_arg, 1);
		_r0.value = (XtArgVal)*(int*)&_r0.value;
		_r0.type = XtQInt;
		FaceSetProperty((Widget)WIDGET_TABLE[3], "blink_rate", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
		FaceSetProperty((Widget)WIDGET_TABLE[3], "inited", (XtArgVal)1, (XrmQuark)XtQInt);	/* XFM 5 */
	}
	_r0.value = (XtArgVal) ((XtArgVal)call_data == (XtArgVal)True);	/* XFM 7 */
	if(_r0.value){
		FaceGetProperty((Widget)WIDGET_TABLE[3], "state", &_r0);	/* XFM 8 */
		_r1.value = (XtArgVal) (! (XtArgVal)_r0.value);
		_r1.type = XtQInt;
		FaceSetProperty((Widget)WIDGET_TABLE[3], "state", (XtArgVal)_r1.value, (XrmQuark)_r1.type);
		FaceGetProperty((Widget)WIDGET_TABLE[3], "state", &_r0);	/* XFM 9 */
		if(_r0.value){
			from.addr = (char *)"red";	/* XFM 10 */
			from.size = strlen(from.addr)+1;
			to.addr = 0;
			XtConvertAndStore(WIDGET_TABLE[3], XtRString, &from, XtRPixel, &to);
			_r0.value = (XtArgVal)*(Pixel*)to.addr;
			XtSetArg(_arg, "background", _r0.value);
			XtSetValues((Widget)WIDGET_TABLE[3], &_arg, 1);
		} else {
			FaceGetProperty((Widget)WIDGET_TABLE[3], "initial_color", &_r0);	/* XFM 12 */
			FaceSetResource((Widget)WIDGET_TABLE[3], "background", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
		}
		FaceGetProperty((Widget)WIDGET_TABLE[3], "blink_rate", &_r0);	/* XFM 14 */
		_r1.value = (XtArgVal) FmSetActiveValueTimeOut((Widget)WIDGET_TABLE[3], (String)"Blink", (int)_r0.value);
		_r1.type = XrmStringToQuark("TimeOutClosure");
		FaceSetProperty((Widget)WIDGET_TABLE[3], "timeout", (XtArgVal)_r1.value, (XrmQuark)_r1.type);
	} else {
		FaceGetProperty((Widget)WIDGET_TABLE[3], "timeout", &_r0);	/* XFM 16 */
		if(_r0.value){
			FaceGetProperty((Widget)WIDGET_TABLE[3], "timeout", &_r0);	/* XFM 17 */
			FmStopTimeOut((FmTimeOutPtr)_r0.value);
			FaceSetProperty((Widget)WIDGET_TABLE[3], "timeout", (XtArgVal)0, (XrmQuark)XtQInt);	/* XFM 18 */
		}
		FaceGetProperty((Widget)WIDGET_TABLE[3], "initial_color", &_r0);	/* XFM 20 */
		FaceSetResource((Widget)WIDGET_TABLE[3], "background", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
	}
}


/* XFM resource activateCallback multi.mainform.beep */
static void WIDGET_2_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FmBeep();
}


/* XFM resource activateCallback multi.mainform.blink */
static void WIDGET_3_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;
	FaceVariable _r1;
	XrmValue from, to;
	Arg _arg;

	FaceGetProperty((Widget)WIDGET_TABLE[3], "blinking", &_r0);	/* XFM 2 */
	_r1.value = (XtArgVal) (! (XtArgVal)_r0.value);
	_r1.type = XtQInt;
	FaceSetProperty((Widget)WIDGET_TABLE[3], "blinking", (XtArgVal)_r1.value, (XrmQuark)_r1.type);
	FaceGetProperty((Widget)WIDGET_TABLE[3], "blinking", &_r0);	/* XFM 3 */
	_r1.value = (XtArgVal) _r0.value;
	FmAttachAv((String)"Blink", (XtPointer)_r1.value);
	FmSetActiveValue((Widget)WIDGET_TABLE[3], (String)"Blink");	/* XFM 4 */
	FaceGetProperty((Widget)WIDGET_TABLE[3], "blinking", &_r0);	/* XFM 5 */
	if(_r0.value){
		from.addr = (char *)"Stop Blinking\n(MB3 to change rate)";	/* XFM 6 */
		from.size = strlen(from.addr)+1;
		to.addr = 0;
		XtConvertAndStore(WIDGET_TABLE[3], XtRString, &from, XmRXmString, &to);
		_r0.value = (XtArgVal)*(XmString*)to.addr;
		XtSetArg(_arg, "labelString", _r0.value);
		XtSetValues((Widget)WIDGET_TABLE[3], &_arg, 1);
	} else {
		from.addr = (char *)"Blink\n(MB3 to change rate)";	/* XFM 8 */
		from.size = strlen(from.addr)+1;
		to.addr = 0;
		XtConvertAndStore(WIDGET_TABLE[3], XtRString, &from, XmRXmString, &to);
		_r0.value = (XtArgVal)*(XmString*)to.addr;
		XtSetArg(_arg, "labelString", _r0.value);
		XtSetValues((Widget)WIDGET_TABLE[3], &_arg, 1);
	}
}


/* XFM resource activateCallback multi.mainform.blink.blink_dshell.blink_rate.ok */
static void WIDGET_6_activateCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{
	FmHideWidget((Widget)WIDGET_TABLE[5]);
}


/* XFM resource valueChangedCallback multi.mainform.blink.blink_dshell.blink_rate.scale */
static void WIDGET_7_valueChangedCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	Arg _arg;
	FaceVariable _r0;

	XtSetArg(_arg, "value", &_r0.value);
	XtGetValues((Widget)WIDGET_TABLE[7], &_arg, 1);
	_r0.value = (XtArgVal)*(int*)&_r0.value;
	_r0.type = XtQInt;
	FaceSetProperty((Widget)WIDGET_TABLE[3], "blink_rate", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
}


/* XFM resource dragCallback multi.mainform.blink.blink_dshell.blink_rate.scale */
static void WIDGET_7_dragCallback(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	Arg _arg;
	FaceVariable _r0;

	XtSetArg(_arg, "value", &_r0.value);
	XtGetValues((Widget)WIDGET_TABLE[7], &_arg, 1);
	_r0.value = (XtArgVal)*(int*)&_r0.value;
	_r0.type = XtQInt;
	FaceSetProperty((Widget)WIDGET_TABLE[3], "blink_rate", (XtArgVal)_r0.value, (XrmQuark)_r0.type);
}

/* XFM action Multi_Action_0 translations <Btn3Down> */

/* XFM resource ??? multi.mainform.blink */
static void _WIDGET_3_Multi_Action_0(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data);
#else
);
#endif
static void WIDGET_3_Multi_Action_0(
#if NeedFunctionPrototypes
Widget widget, XEvent* event)
#else
widget, event)
Widget widget;
XEvent* event;
#endif
{
	_WIDGET_3_Multi_Action_0(widget, 0, (XtPointer)event);
}
static void _WIDGET_3_Multi_Action_0(
#if NeedFunctionPrototypes
Widget widget, XtPointer client_data, XtPointer call_data)
#else
widget, client_data, call_data)
Widget widget;
XtPointer client_data;
XtPointer call_data;
#endif
{	FaceVariable _r0;

	_r0.value = (XtArgVal)FaceGetWidget((Widget)widget, -2, "*blink_rate");
	FmShowWidget((Widget)_r0.value);
}

/* XFM private */
static XtActionsRec EvalActions[] = {
	{"WIDGET_3_Multi_Action_0", (XtActionProc)WIDGET_3_Multi_Action_0},
};

#undef WIDGET_TABLE

static void FreeWidgetTable(
#if NeedFunctionPrototypes
Widget w, XtPointer table, XtPointer unused)
#else
w, table, unused)
Widget w;
XtPointer table;
XtPointer unused;
#endif
{
	XtFree((char*)table);
}

Widget
_FmCreateMulti(
#if NeedFunctionPrototypes
String name, Widget parent, Widget * toplevels, Cardinal num_toplevels, Widget ** widgets_return, Cardinal * num_widgets_return, Arg* avs, Cardinal num_avs, Arg* user_args, Cardinal num_user_args, Boolean manage_top_objects, XtPointer _this)
#else
name, parent, toplevels, num_toplevels, widgets_return, num_widgets_return, avs, num_avs, user_args, num_user_args, manage_top_objects, _this)
String name;
Widget parent;
Widget * toplevels;
Cardinal num_toplevels;
Widget ** widgets_return;
Cardinal * num_widgets_return;
Arg* avs;
Cardinal num_avs;
Arg* user_args;
Cardinal num_user_args;
Boolean manage_top_objects;
XtPointer _this;
#endif
{
	Arg args[115];
	Cardinal nargs, i;
	XrmValue from, to;
	String app_name, app_class;
	Widget *widget_table = (Widget*)XtMalloc(8*sizeof(Widget));
#define WIDGET_TABLE widget_table

	if(widgets_return) *widgets_return = widget_table;
	if(num_widgets_return) *num_widgets_return = 8;

	{
		static int actions_added;
		if(!actions_added){
			XtAppAddActions(XtWidgetToApplicationContext(parent), EvalActions, XtNumber(EvalActions));
			actions_added = 1;
		}
	}


	/* XFM create multi */
	if(toplevels && 0 < num_toplevels && toplevels[0]){
		WIDGET_TABLE[0] = toplevels[0];
	} else {
	nargs = 0;
	for(i = 0; i < num_user_args; i++){
		args[nargs].name = user_args[i].name;
		args[nargs].value = user_args[i].value;
		nargs++;
	}
	XtGetApplicationNameAndClass(XtDisplay(parent), &app_name, &app_class);
	WIDGET_TABLE[0] = XtAppCreateShell(app_name, app_class, applicationShellWidgetClass, XtDisplay(parent), args, nargs);
	}
	if(_this){
		Arg arg;
		arg.name = "this";
		arg.value = (XtArgVal)_this;
		FmCreateValue("this", 0, 0, "Pointer", 1, 0, 0, 1, 0, (Widget)WIDGET_TABLE[0], WIDGET_TABLE, &arg, 1);
	}

	/* XFM create multi.mainform */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 287); nargs++;
	XtSetArg(args[nargs], "height", 108); nargs++;
	WIDGET_TABLE[1] = XtCreateManagedWidget("mainform", xmFormWidgetClass, WIDGET_TABLE[0], args, nargs);

	/* XFM create multi.mainform.beep */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 144); nargs++;
	XtSetArg(args[nargs], "height", 108); nargs++;
	XtSetArg(args[nargs], "leftAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "rightAttachment", XmATTACH_POSITION); nargs++;
	XtSetArg(args[nargs], "rightPosition", 50); nargs++;
	XtSetArg(args[nargs], "topAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "bottomAttachment", XmATTACH_FORM); nargs++;
	from.addr = "Beep";
	from.size = 5;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[1], XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[2] = XtCreateManagedWidget("beep", xmPushButtonWidgetClass, WIDGET_TABLE[1], args, nargs);
	XtAddCallback(WIDGET_TABLE[2], "activateCallback", (XtCallbackProc)WIDGET_2_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create multi.mainform.blink */
	nargs = 0;
	XtSetArg(args[nargs], "x", 144); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 143); nargs++;
	XtSetArg(args[nargs], "height", 108); nargs++;
	XtSetArg(args[nargs], "leftAttachment", XmATTACH_WIDGET); nargs++;
	XtSetArg(args[nargs], "leftWidget", WIDGET_TABLE[2]); nargs++;
	XtSetArg(args[nargs], "rightAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "topAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "bottomAttachment", XmATTACH_FORM); nargs++;
	from.addr = "Blink\n\
(MB3 to change rate)";
	from.size = 27;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[1], XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	from.addr = "#override\n\
<Btn3Down>: WIDGET_3_Multi_Action_0()\n\
<Btn1Down>: Arm()\n\
<Btn1Up>: Disarm() Activate()";
	from.size = 96;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[1], XmRString, &from, XtRTranslationTable, &to);
	if(to.addr) { XtSetArg(args[nargs], "translations", *(XtTranslations*)to.addr); nargs++; }
	WIDGET_TABLE[3] = XtCreateManagedWidget("blink", xmPushButtonWidgetClass, WIDGET_TABLE[1], args, nargs);
	XtAddCallback(WIDGET_TABLE[3], "activateCallback", (XtCallbackProc)WIDGET_3_activateCallback, (XtPointer)WIDGET_TABLE);
	FmCreateValue("Blink", (XtCallbackProc)0, (XtCallbackProc)Blink_WIDGET_3_set, "Boolean", 0, 0, 0, 0, 0, (Widget)WIDGET_TABLE[3], WIDGET_TABLE, avs, num_avs);

	/* XFM create multi.mainform.blink.blink_dshell */
	nargs = 0;
	XtSetArg(args[nargs], "width", 278); nargs++;
	XtSetArg(args[nargs], "height", 104); nargs++;
	XtSetArg(args[nargs], "title", "Blinking Rate"); nargs++;
	XtSetArg(args[nargs], "x", 570); nargs++;
	XtSetArg(args[nargs], "y", 346); nargs++;
	WIDGET_TABLE[4] = XtCreatePopupShell("blink_dshell", xmDialogShellWidgetClass, WIDGET_TABLE[3], args, nargs);

	/* XFM create multi.mainform.blink.blink_dshell.blink_rate */
	nargs = 0;
	XtSetArg(args[nargs], "x", 0); nargs++;
	XtSetArg(args[nargs], "y", 0); nargs++;
	XtSetArg(args[nargs], "width", 278); nargs++;
	XtSetArg(args[nargs], "height", 104); nargs++;
	XtSetArg(args[nargs], "defaultPosition", False); nargs++;
	XtSetArg(args[nargs], "verticalSpacing", 10); nargs++;
	XtSetArg(args[nargs], "horizontalSpacing", 10); nargs++;
	WIDGET_TABLE[5] = XtCreateWidget("blink_rate", xmFormWidgetClass, WIDGET_TABLE[4], args, nargs);

	/* XFM create multi.mainform.blink.blink_dshell.blink_rate.ok */
	nargs = 0;
	XtSetArg(args[nargs], "x", 10); nargs++;
	XtSetArg(args[nargs], "y", 69); nargs++;
	XtSetArg(args[nargs], "width", 258); nargs++;
	XtSetArg(args[nargs], "height", 25); nargs++;
	XtSetArg(args[nargs], "leftAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "rightAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "bottomAttachment", XmATTACH_FORM); nargs++;
	from.addr = "OK";
	from.size = 3;
	to.addr = 0; to.size = 0;
	XtConvertAndStore(WIDGET_TABLE[5], XmRString, &from, XmRXmString, &to);
	if(to.addr) { XtSetArg(args[nargs], "labelString", *(XmString*)to.addr); nargs++; }
	WIDGET_TABLE[6] = XtCreateManagedWidget("ok", xmPushButtonWidgetClass, WIDGET_TABLE[5], args, nargs);
	XtAddCallback(WIDGET_TABLE[6], "activateCallback", (XtCallbackProc)WIDGET_6_activateCallback, (XtPointer)WIDGET_TABLE);

	/* XFM create multi.mainform.blink.blink_dshell.blink_rate.scale */
	nargs = 0;
	XtSetArg(args[nargs], "width", 258); nargs++;
	XtSetArg(args[nargs], "height", 49); nargs++;
	XtSetArg(args[nargs], "x", 10); nargs++;
	XtSetArg(args[nargs], "y", 10); nargs++;
	XtSetArg(args[nargs], "orientation", XmHORIZONTAL); nargs++;
	XtSetArg(args[nargs], "topAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "leftAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "rightAttachment", XmATTACH_FORM); nargs++;
	XtSetArg(args[nargs], "bottomAttachment", XmATTACH_WIDGET); nargs++;
	XtSetArg(args[nargs], "bottomWidget", WIDGET_TABLE[6]); nargs++;
	XtSetArg(args[nargs], "showValue", XmNEAR_SLIDER); nargs++;
	XtSetArg(args[nargs], "maximum", 1000); nargs++;
	XtSetArg(args[nargs], "value", 500); nargs++;
	WIDGET_TABLE[7] = XtCreateManagedWidget("scale", xmScaleWidgetClass, WIDGET_TABLE[5], args, nargs);
	XtAddCallback(WIDGET_TABLE[7], "dragCallback", (XtCallbackProc)WIDGET_7_dragCallback, (XtPointer)WIDGET_TABLE);
	XtAddCallback(WIDGET_TABLE[7], "valueChangedCallback", (XtCallbackProc)WIDGET_7_valueChangedCallback, (XtPointer)WIDGET_TABLE);

	/* XFM private */

	if(manage_top_objects){
	}
	XtAddCallback(WIDGET_TABLE[0], XmNdestroyCallback, (XtCallbackProc)FreeWidgetTable, (XtPointer)WIDGET_TABLE);

	return(WIDGET_TABLE[0]);
}

Widget
FmCreateMulti(
#if NeedFunctionPrototypes
String name, Widget parent, Arg* args, Cardinal num_args)
#else
name, parent, args, num_args)
String name;
Widget parent;
Arg* args;
Cardinal num_args;
#endif
{
	return(_FmCreateMulti(name, parent, 0, 0, 0, 0, 0, 0, args, num_args, True, 0));
}
