/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1032964861
 */

/*
 *  XFaceMaker 3.5 Application Functions Declarations.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif
/*## 					begin pattern define [ VARNAME left (length _XFM_EXT_BUILD_INCLUDES) == _XFM_EXT_BUILD_INCLUDES ] ##*/
/*## VALUE ##*/
/*## 					end pattern ##*/

/*## begin pattern `active_values' ##*/
/*## $$extern AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' Multi  ##*/
extern Boolean Blink;
/*## end `active_values' Multi  ##*/

#if NeedFunctionPrototypes
/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## extern CTYPE CNAME($$CARGTYPES ARGNAMES$, $); ##*/
/*## end pattern `function' ##*/
#else /* NeedFunctionPrototypes */
/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## extern CTYPE CNAME(); ##*/
/*## end pattern `function' ##*/
#endif /* NeedFunctionPrototypes */
