/*
 *  C file generated by XFaceMaker Version 3.0.
 *  Do not remove this comment.
 *  Timestamp:           1032964862
 */

/*
 *  XFaceMaker 3.5 Application Main Function
 */

/*## begin pattern interface ##*/
/*## set global RDBMODE = RDBMODE ##*/
/*## set global UILMODE = UILMODE ##*/
/*## begin if [ UILMODE == 1 ] ##*/
/*## 	set global UIDFILESPATH = `' ##*/
/*## end if ##*/
/*## end pattern interface ##*/
/*## begin `interface' Multi  ##*/
/*## end `interface' Multi  ##*/

#include <stdio.h>
#ifndef STANDALONE
#include <Fm.h>
#else
#include <Xm/Xm.h>
#endif

/*## 			begin pattern define [ VARNAME left (length _XFM_EXT_BUILD_INIT_FUNCTION_) == _XFM_EXT_BUILD_INIT_FUNCTION_ ] ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## extern void VALUE(void); ##*/
/*## #else ##*/
/*## extern void VALUE(); ##*/
/*## #endif ##*/
/*## 			end pattern define ##*/

/*## begin pattern interface ##*/
/*## #include "`NAME'App.h" ##*/
/*## end pattern interface ##*/
/*## begin `interface' Multi  ##*/
#include "MultiApp.h"

#include <X11/Shell.h>

/*## end `interface' Multi  ##*/

#ifndef REMOTE

#ifdef CCODE
#if NeedFunctionPrototypes
/*## begin pattern interface ##*/
/*## $$extern Widget FmCreate`CREATENAMES'(String,Widget,ArgList,Cardinal);$\n$ ##*/
/*## end pattern interface ##*/
/*## begin `interface' Multi  ##*/
extern Widget FmCreateMulti(String,Widget,ArgList,Cardinal);
/*## end `interface' Multi  ##*/
#else /* NeedFunctionPrototypes */
/*## begin pattern interface ##*/
/*## $$extern Widget FmCreate`CREATENAMES'();$\n$ ##*/
/*## end pattern interface ##*/
/*## begin `interface' Multi  ##*/
extern Widget FmCreateMulti();
/*## end `interface' Multi  ##*/
#endif /* NeedFunctionPrototypes */
#endif

#endif /* REMOTE */

#ifdef REMOTE

#if NeedFunctionPrototypes
extern int FaceIPCConnectApplication(Widget, char*);
#else /* NeedFunctionPrototypes */
extern int FaceIPCConnectApplication();
#endif /* NeedFunctionPrototypes */

static XrmOptionDescRec AddressOptions[] = {
	{"-host", "*xfmRemoteHost", XrmoptionSepArg},
	{"-port", "*xfmRemotePort", XrmoptionSepArg},
};

#define options 	AddressOptions
#define num_options 	XtNumber(AddressOptions)

#else /* REMOTE */

#define options 	0
#define num_options 	0

#endif /* REMOTE */

/*
 * This data structure records the <display, application shell>
 * couples and is used to find an application shell for a
 * given display.
 */
struct {
	Display *display;
	Widget toplevel;
} Toplevels[10];

/*
 * Adds a new <display, application shell> couple.
 */
#if NeedFunctionPrototypes
void NewDisplay(Display *display, Widget toplevel)
#else
void NewDisplay(display, toplevel)
Display *display;
Widget toplevel;
#endif
{
	int i;
	for(i = 0; Toplevels[i].display; i++)
		;
	Toplevels[i].display = display;
	Toplevels[i].toplevel = toplevel;
}

/*
 * Finds an application shell on a display.
 */
#if NeedFunctionPrototypes
Widget ToplevelOfDisplay(Display *display)
#else
Widget ToplevelOfDisplay(display)
Display *display;
#endif
{
	int i;
	for(i = 0; Toplevels[i].display; i++)
		if(Toplevels[i].display == display)
			return(Toplevels[i].toplevel);
	return((Widget)0);
}

/*
 * This redefinition of XtMainLoop calls FmSetToplevel
 * with an application shell of the event's display.
 *  It ensures that the Fm functions called in response
 * to the event will use the right default application
 * shell.
 */
#if NeedFunctionPrototypes
void MainLoop(XtAppContext ac)
#else
void MainLoop(ac)
XtAppContext ac;
#endif
{
	XEvent event;
	Widget toplevel;
	static Display *last_display;
	
	for(;;){
		/*
		 * Get next event on default app. context.
		 */
		XtAppNextEvent(ac, &event);
		/*
		 * Last_display is used to avoid switch toplevels
		 * if the display has not changed since the last time.
		 *  This works only if no one else calls FmSetToplevel,
		 * of course...
		 */
		if(event.xany.display != last_display){
			/*
			 * Display has changed: find an application shell
			 * on this display, and call FmSetToplevel with it.
			 */
			toplevel = ToplevelOfDisplay(event.xany.display);
			if(toplevel){
				FmSetToplevel(toplevel);
			} else {
				printf("No toplevel for display %x\n", event.xany.display);
			}
			last_display = event.xany.display;
		}
		/*
		 * Dispatch event.
		 */
		XtDispatchEvent(&event);
	}
}

main(
#if NeedFunctionPrototypes
int argc, char **argv)
#else
argc, argv)
int argc;
char **argv;
#endif
{
	Widget toplevel, parent;
/*## begin pattern interface ##*/
/*## 	Widget w[NUMNAMES]; ##*/
/*## end pattern interface ##*/
/*## begin `interface' Multi  ##*/
	Widget w[1];
/*## end `interface' Multi  ##*/
	int i;
	XtAppContext app_context;
	Display *display;
	Widget multi;
	char *displays[10];
	int num_displays = 1;

	/*
	 * Initialize toolkit.
	 */
/*## begin pattern module ##*/
/*## 	set local NAMEFM = NAME.fm ##*/
/*## 	begin if [ FILE != NAMEFM ] ##*/
/*## 		begin if [ FILE right 3 == ".fm" ] ##*/
/*## 			set local BASEFILE = [ FILE left (length FILE - 3) ] ##*/
/*## 		ifelse ##*/
/*## 			set local BASEFILE = FILE ##*/
/*## 		end if ##*/
/*## 		set local MODULEDIR = [ BASEFILE left (length BASEFILE - length BASENAME) ] ##*/
/*## 		begin if [ UIDFILESPATH == "" ]
/*## 			set global UIDFILESPATH = MODULEDIR%U ##*/
/*## 		ifelse ##*/
/*## 			set global UIDFILESPATH = UIDFILESPATH:MODULEDIR%U ##*/
/*## 		end if ##*/
/*## 	end if ##*/
/*## end pattern module ##*/
/*## begin `module' Multi  ##*/
/*## end `module' Multi  ##*/
/*## begin pattern interface ##*/
/*## 		begin if [ RDBMODE == 1 ] ##*/
/*## #ifndef CALLEDITOR ##*/
/*## 	if(!getenv("XUSERFILESEARCHPATH")) ##*/
/*## 		putenv("XUSERFILESEARCHPATH=%N.ad"); ##*/
/*## #endif ##*/
/*## 		end if ##*/
/*## 		begin if [ UILMODE == 1 && UIDFILESPATH != "" ] ##*/
/*## #ifndef CALLEDITOR ##*/
/*## 	if(!getenv("UIDPATH")) ##*/
/*## 		putenv("UIDPATH=UIDFILESPATH"); ##*/
/*## #endif ##*/
/*## 		end if ##*/
/*## #if defined(CCODE) && defined(STANDALONE) ##*/
/*## 	toplevel = XtAppInitialize(&app_context, "UCNAME", options, num_options, &argc, argv, 0, 0, 0); ##*/
/*## #else ##*/
/*## 	toplevel = FmAppInitialize(&app_context, "UCNAME", options, num_options, &argc, argv, 0, 0, 0); ##*/
/*## #endif ##*/
/*## end pattern interface ##*/
/*## begin `interface' Multi  ##*/
/*## end `interface' Multi  ##*/
	
/*## 			begin pattern define [ VARNAME left (length _XFM_EXT_BUILD_C_INIT_FUNCALL_) == _XFM_EXT_BUILD_C_INIT_FUNCALL_ ] ##*/
/*## 	VALUE ##*/
/*## 			end pattern define ##*/

XnslRegisterConverters();

#ifndef CCODE
	/*
	 * Call initialization routines for extension libraries.
	 */
/*## 			begin pattern define [ VARNAME left (length _XFM_EXT_BUILD_INIT_FUNCALL_) == _XFM_EXT_BUILD_INIT_FUNCALL_ ] ##*/
/*## 	VALUE ##*/
/*## 			end pattern define ##*/
	
	/*
	 * Attach application functions.
	 */
/*## begin pattern `function' [ ! defined NAMESPACE ]  ##*/
/*## 	FmAttachFunction("NAME", (FaceFunctionPtr)CNAME, "TYPE", NUMARGS$$, "ARGTYPES"$$); ##*/
/*## end pattern `function' ##*/
#ifndef CALLEDITOR
	/*
	 * Load user-defined classes.
	 */
/*## begin pattern `user_class' ##*/
/*## 	FmLoadWidgetClass("UCLASSNAME", "UCLASSFILE.fm"); ##*/
/*## end pattern `user_class' ##*/
#endif
#endif
	
#ifndef STANDALONE
	/*
	 * Attach active values.
	 */
/*## begin pattern `active_values' ##*/
/*## 	$$FmAttachAv("AVNAMES", (XtPointer)`AVADDRS'AVNAMES);$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' Multi  ##*/
/*## end `active_values' Multi  ##*/
#endif
	
#ifndef REMOTE

#ifdef CCODE

#ifndef STANDALONE
	/*
	 * Register creation functions for dynamic creation
	 * in FACE scripts.
	 */
/*## begin pattern module ##*/
/*## 	FmRegisterCreateFunction("NAME.fm", (FmCreationFunction)FmCreate`CREATENAME'); ##*/
/*## end pattern module ##*/
/*## begin `module' Multi  ##*/
	FmRegisterCreateFunction("Multi.fm", (FmCreationFunction)FmCreateMulti);
/*## end `module' Multi  ##*/
#endif /* STANDALONE*/
	
	/*
	 * Call interface creation functions.
	 */
/*## begin pattern module TOPOBJ = APP_SHELL ##*/
/*## 	w[INDEX] = toplevel = FmCreate`CREATENAME'(0, toplevel, 0, 0); ##*/
/*## end pattern module ##*/
/*## begin `module' Multi  ##*/
/*## end `module' Multi  ##*/
/*## begin pattern module TOPOBJ # APP_SHELL PARENTPATH = `' ##*/
/*## 	w[INDEX] = FmCreate`CREATENAME'(0, toplevel, 0, 0); ##*/
/*## end pattern module ##*/
/*## begin pattern module TOPOBJ # APP_SHELL PARENTPATH # `' ##*/
/*## 	parent = XtNameToWidget(toplevel, "PARENTPATH"); ##*/
/*## 	if(parent) ##*/
/*## 		w[INDEX] = FmCreate`CREATENAME'(0, parent, 0, 0); ##*/
/*## 	else  ##*/
/*## 		fprintf(stderr, "Cannot find parent widget `PARENTPATH'.\\n"); ##*/
/*## end pattern module ##*/
#else
#ifndef CALLEDITOR
	/*
	 * Load interface files.
	 */
/*## begin pattern module ##*/
/*##  		begin if [ RDBMODE == 1 ] ##*/
/*## 			set local FMSUFFIX = _rdb ##*/
/*## 		ifelse ##*/
/*## 			set local FMSUFFIX = `' ##*/
/*## 		end if ##*/
/*## 		begin if [ TOPOBJ == APP_SHELL ] ##*/
/*## 	w[INDEX] = toplevel = FmLoadCreate(0, "`FILE'`FMSUFFIX'", toplevel, 0, 0); ##*/
/*## 		ifelse ##*/
/*## 			begin if [ PARENTPATH == "" ] ##*/
/*## 	w[INDEX] = FmLoadCreate(0, "`FILE'`FMSUFFIX'", toplevel, 0, 0); ##*/
/*## 			ifelse ##*/
/*## 	parent = XtNameToWidget(toplevel, "PARENTPATH"); ##*/
/*## 	if(parent) ##*/
/*## 		w[INDEX] = FmLoadCreate(0, "`FILE'`FMSUFFIX'", parent, 0, 0); ##*/
/*## 	else  ##*/
/*## 		fprintf(stderr, "Cannot find parent widget `PARENTPATH'.\\n"); ##*/
/*## 			end if ##*/
/*## 		end if ##*/
/*## end pattern module ##*/
/*## begin `module' Multi  ##*/
/*## end `module' Multi  ##*/
#endif
#endif

#endif /* REMOTE */

#ifdef REMOTE
	
	FaceIPCConnectApplication(toplevel, argv[0]);
	
#endif /* REMOTE */

#ifndef REMOTE

	/*
	 * Show widgets.
	 */
#ifndef CALLEDITOR
#ifdef STANDALONE
/*## begin pattern module MAPPED = 1 TOPOBJ = APP_SHELL ##*/
/*## 	XtRealizeWidget(w[INDEX]); ##*/
/*## end pattern module ##*/
/*## begin pattern module MAPPED = 1 TOPOBJ = POPUP_SHELL ##*/
/*## 	XtPopup(w[INDEX], False); ##*/
/*## end pattern module ##*/
/*## begin pattern module MAPPED = 1 TOPOBJ = MANAGED_WIDGET ##*/
/*## 	XtManageChild(w[INDEX]); ##*/
/*## end pattern module ##*/
#else
/*## begin pattern module MAPPED = 1 ##*/
/*## 	FmShowWidget(w[INDEX]); ##*/
/*## end pattern module ##*/
#endif
#endif

#endif /* REMOTE */

	/*
	 * Enter main event loop.
	 */
#ifdef CALLEDITOR
	FmCallEditor();
#else
	displays[0] = "default";
	for(i = 1; i < argc; i++){
		if(index(argv[i], ':') != 0)
			displays[num_displays++] = XtNewString(argv[i]);
	}
	
	/*
	 * Each command-line argument is a new display name.
	 * The first display is the default display (so no arguments
	 * give a single window on the default display).
	 */
	for(i = 0; i < num_displays; i++){
printf("opening display no. %d: %s\n", i, displays[i]);
		if(i == 0){
			/*
			 * Default display: call FmInitialize, and get
			 * the default display and applicatin context.
			 */

#if defined(CCODE) && defined(STANDALONE)
			toplevel = XtAppInitialize(&app_context, "Multi", options, num_options, &argc, argv, 0, 0, 0);
#else
			toplevel = FmAppInitialize(&app_context, "Multi", options, num_options, &argc, argv, 0, 0, 0);
#endif			 
			display = XtDisplay(toplevel);

#ifndef STANDALONE
			/*
			 * Attach active values.
			 */
			FmAttachAv("Blink", (XtPointer)&Blink);
#endif
			
		} else {
			/*
			 * Additional display: open the display and
			 * create an application shell on it.
			 */
			display = XtOpenDisplay(app_context,
						i > 0 ? displays[i] : NULL,
						"multi", "Multi",
						NULL, 0,
						&argc, argv);
			if(!display){
				printf("Can't open display %s.\n",
					i > 0 ? displays[i] : "(null)");
				continue;
			}
			toplevel = XtAppCreateShell("multi",
						"Multi",
						applicationShellWidgetClass,
						display,
						NULL, 0);
		}
		/*
		 * Add the <display, application shell> to the
		 * global table so that MainLoop can switch to the
		 * correct display.
		 */
		NewDisplay(display, toplevel);
		/*
		 * Set the current XFM toplevel so that the creation
		 * function uses the right display.
		 */
		FmSetToplevel(toplevel);
		/*
		 * Create and map the XFM-defined window
		 * (interpreted or C mode).
		 */
#ifdef CCODE
		multi = FmCreateMulti("multi", toplevel, NULL, 0);
#else
		multi = FmLoadCreate("multi", "Multi.fm", toplevel, NULL, 0);
#endif
		FmShowWidget(multi);
	}
	
	/*
	 * Enter main loop.
	 */
	MainLoop(app_context);
#endif
}
