// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:715

#ifndef _TAO_IDL_QUOTERS_T_5PRH6P_CPP_
#define _TAO_IDL_QUOTERS_T_5PRH6P_CPP_

#include "QuoterS_T.h"

// TAO_IDL - Generated from
// be/be_visitor_interface/tie_ss.cpp:82

template <class T>
POA_Quoter::Stock_Factory_tie<T>::Stock_Factory_tie (T &t)
  : ptr_ (&t),
    poa_ ( ::PortableServer::POA::_nil ()),
    rel_ (false)
{}

template <class T>
POA_Quoter::Stock_Factory_tie<T>::Stock_Factory_tie (T &t, ::PortableServer::POA_ptr poa)
  : ptr_ (&t),
    poa_ ( ::PortableServer::POA::_duplicate (poa)),
    rel_ (false)
{}

template <class T>
POA_Quoter::Stock_Factory_tie<T>::Stock_Factory_tie (T *tp, ::CORBA::Boolean release)
  : ptr_ (tp),
    poa_ ( ::PortableServer::POA::_nil ()),
    rel_ (release)
{}

template <class T>
POA_Quoter::Stock_Factory_tie<T>::Stock_Factory_tie (T *tp, ::PortableServer::POA_ptr poa, ::CORBA::Boolean release)
  : ptr_ (tp),
    poa_ ( ::PortableServer::POA::_duplicate (poa)),
    rel_ (release)
{}

template <class T>
POA_Quoter::Stock_Factory_tie<T>::~Stock_Factory_tie (void)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
}

template <class T> T *
POA_Quoter::Stock_Factory_tie<T>::_tied_object (void)
{
  return this->ptr_;
}

template <class T> void
POA_Quoter::Stock_Factory_tie<T>::_tied_object (T &obj)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
  
  this->ptr_ = &obj;
  this->rel_ = false;
}

template <class T> void
POA_Quoter::Stock_Factory_tie<T>::_tied_object (T *obj, ::CORBA::Boolean release)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
  
  this->ptr_ = obj;
  this->rel_ = release;
}

template <class T>  ::CORBA::Boolean
POA_Quoter::Stock_Factory_tie<T>::_is_owner (void)
{
  return this->rel_;
}

template <class T> void
POA_Quoter::Stock_Factory_tie<T>::_is_owner ( ::CORBA::Boolean b)
{
  this->rel_ = b;
}

template <class T> PortableServer::POA_ptr
POA_Quoter::Stock_Factory_tie<T>::_default_POA ()
{
  if (! ::CORBA::is_nil (this->poa_.in ()))
    {
      return ::PortableServer::POA::_duplicate (this->poa_.in ());
    }
  
  return this->Stock_Factory::_default_POA ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
::Quoter::Stock_ptr POA_Quoter::Stock_Factory_tie<T>::get_stock  (
  const char * stock_symbol)
{
  return this->ptr_->get_stock (
    stock_symbol
  );
}

// TAO_IDL - Generated from
// be/be_visitor_interface/tie_ss.cpp:82

template <class T>
POA_Quoter::Stock_tie<T>::Stock_tie (T &t)
  : ptr_ (&t),
    poa_ ( ::PortableServer::POA::_nil ()),
    rel_ (false)
{}

template <class T>
POA_Quoter::Stock_tie<T>::Stock_tie (T &t, ::PortableServer::POA_ptr poa)
  : ptr_ (&t),
    poa_ ( ::PortableServer::POA::_duplicate (poa)),
    rel_ (false)
{}

template <class T>
POA_Quoter::Stock_tie<T>::Stock_tie (T *tp, ::CORBA::Boolean release)
  : ptr_ (tp),
    poa_ ( ::PortableServer::POA::_nil ()),
    rel_ (release)
{}

template <class T>
POA_Quoter::Stock_tie<T>::Stock_tie (T *tp, ::PortableServer::POA_ptr poa, ::CORBA::Boolean release)
  : ptr_ (tp),
    poa_ ( ::PortableServer::POA::_duplicate (poa)),
    rel_ (release)
{}

template <class T>
POA_Quoter::Stock_tie<T>::~Stock_tie (void)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
}

template <class T> T *
POA_Quoter::Stock_tie<T>::_tied_object (void)
{
  return this->ptr_;
}

template <class T> void
POA_Quoter::Stock_tie<T>::_tied_object (T &obj)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
  
  this->ptr_ = &obj;
  this->rel_ = false;
}

template <class T> void
POA_Quoter::Stock_tie<T>::_tied_object (T *obj, ::CORBA::Boolean release)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
  
  this->ptr_ = obj;
  this->rel_ = release;
}

template <class T>  ::CORBA::Boolean
POA_Quoter::Stock_tie<T>::_is_owner (void)
{
  return this->rel_;
}

template <class T> void
POA_Quoter::Stock_tie<T>::_is_owner ( ::CORBA::Boolean b)
{
  this->rel_ = b;
}

template <class T> PortableServer::POA_ptr
POA_Quoter::Stock_tie<T>::_default_POA ()
{
  if (! ::CORBA::is_nil (this->poa_.in ()))
    {
      return ::PortableServer::POA::_duplicate (this->poa_.in ());
    }
  
  return this->Stock::_default_POA ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
char * POA_Quoter::Stock_tie<T>::symbol  (
  void)
{
  return this->ptr_->symbol (
  );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
char * POA_Quoter::Stock_tie<T>::full_name  (
  void)
{
  return this->ptr_->full_name (
  );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
::CORBA::Double POA_Quoter::Stock_tie<T>::price  (
  void)
{
  return this->ptr_->price (
  );
}

// TAO_IDL - Generated from
// be/be_visitor_interface/tie_ss.cpp:82

template <class T>
POA_Quoter::Modify_Stock_tie<T>::Modify_Stock_tie (T &t)
  : ptr_ (&t),
    poa_ ( ::PortableServer::POA::_nil ()),
    rel_ (false)
{}

template <class T>
POA_Quoter::Modify_Stock_tie<T>::Modify_Stock_tie (T &t, ::PortableServer::POA_ptr poa)
  : ptr_ (&t),
    poa_ ( ::PortableServer::POA::_duplicate (poa)),
    rel_ (false)
{}

template <class T>
POA_Quoter::Modify_Stock_tie<T>::Modify_Stock_tie (T *tp, ::CORBA::Boolean release)
  : ptr_ (tp),
    poa_ ( ::PortableServer::POA::_nil ()),
    rel_ (release)
{}

template <class T>
POA_Quoter::Modify_Stock_tie<T>::Modify_Stock_tie (T *tp, ::PortableServer::POA_ptr poa, ::CORBA::Boolean release)
  : ptr_ (tp),
    poa_ ( ::PortableServer::POA::_duplicate (poa)),
    rel_ (release)
{}

template <class T>
POA_Quoter::Modify_Stock_tie<T>::~Modify_Stock_tie (void)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
}

template <class T> T *
POA_Quoter::Modify_Stock_tie<T>::_tied_object (void)
{
  return this->ptr_;
}

template <class T> void
POA_Quoter::Modify_Stock_tie<T>::_tied_object (T &obj)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
  
  this->ptr_ = &obj;
  this->rel_ = false;
}

template <class T> void
POA_Quoter::Modify_Stock_tie<T>::_tied_object (T *obj, ::CORBA::Boolean release)
{
  if (this->rel_)
    {
      delete this->ptr_;
    }
  
  this->ptr_ = obj;
  this->rel_ = release;
}

template <class T>  ::CORBA::Boolean
POA_Quoter::Modify_Stock_tie<T>::_is_owner (void)
{
  return this->rel_;
}

template <class T> void
POA_Quoter::Modify_Stock_tie<T>::_is_owner ( ::CORBA::Boolean b)
{
  this->rel_ = b;
}

template <class T> PortableServer::POA_ptr
POA_Quoter::Modify_Stock_tie<T>::_default_POA ()
{
  if (! ::CORBA::is_nil (this->poa_.in ()))
    {
      return ::PortableServer::POA::_duplicate (this->poa_.in ());
    }
  
  return this->Modify_Stock::_default_POA ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
char * POA_Quoter::Modify_Stock_tie<T>::symbol  (
  void)
{
  return this->ptr_->symbol (
  );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
char * POA_Quoter::Modify_Stock_tie<T>::full_name  (
  void)
{
  return this->ptr_->full_name (
  );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
::CORBA::Double POA_Quoter::Modify_Stock_tie<T>::price  (
  void)
{
  return this->ptr_->price (
  );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/tie_ss.cpp:95

template <class T>
void POA_Quoter::Modify_Stock_tie<T>::set_price  (
  ::CORBA::Double new_price)
{
  this->ptr_->set_price (
    new_price
  );
}
#endif /* ifndef */

