// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:599

#ifndef _TAO_IDL_QUOTERS_T_VH4HLJ_H_
#define _TAO_IDL_QUOTERS_T_VH4HLJ_H_

#include /**/ "ace/pre.h"

// TAO_IDL - Generated from
// be/be_visitor_root/root_sth.cpp:68

namespace POA_Quoter
{

  // TAO_IDL - Generated from
  // be/be_visitor_interface/tie_sh.cpp:74

  // TIE class: Refer to CORBA v2.2, Section 20.34.4
  template <class T>
  class  Stock_Factory_tie : public Stock_Factory
  {
  public:
    /// the T& ctor
    Stock_Factory_tie (T &t);
    /// ctor taking a POA
    Stock_Factory_tie (T &t, PortableServer::POA_ptr poa);
    /// ctor taking pointer and an ownership flag
    Stock_Factory_tie (T *tp, ::CORBA::Boolean release = true);
    /// ctor with T*, ownership flag and a POA
    Stock_Factory_tie (
        T *tp,
        PortableServer::POA_ptr poa,
        ::CORBA::Boolean release = true
      );
    /// dtor

    ~Stock_Factory_tie (void);
    // TIE specific functions
    /// return the underlying object
    T *_tied_object (void);
    /// set the underlying object
    void _tied_object (T &obj);
    /// set the underlying object and the ownership flag
    void _tied_object (T *obj, ::CORBA::Boolean release = true);
    /// do we own it
    ::CORBA::Boolean _is_owner (void);
    /// set the ownership

    void _is_owner ( ::CORBA::Boolean b);
    // overridden ServantBase operations
    PortableServer::POA_ptr _default_POA (void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    ::Quoter::Stock_ptr get_stock (
      const char *);
  
  private:
    T *ptr_;
    PortableServer::POA_var poa_;
    ::CORBA::Boolean rel_;

    // copy and assignment are not allowed
    Stock_Factory_tie (const Stock_Factory_tie &);
    void operator= (const Stock_Factory_tie &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_interface/tie_sh.cpp:74

  // TIE class: Refer to CORBA v2.2, Section 20.34.4
  template <class T>
  class  Stock_tie : public Stock
  {
  public:
    /// the T& ctor
    Stock_tie (T &t);
    /// ctor taking a POA
    Stock_tie (T &t, PortableServer::POA_ptr poa);
    /// ctor taking pointer and an ownership flag
    Stock_tie (T *tp, ::CORBA::Boolean release = true);
    /// ctor with T*, ownership flag and a POA
    Stock_tie (
        T *tp,
        PortableServer::POA_ptr poa,
        ::CORBA::Boolean release = true
      );
    /// dtor

    ~Stock_tie (void);
    // TIE specific functions
    /// return the underlying object
    T *_tied_object (void);
    /// set the underlying object
    void _tied_object (T &obj);
    /// set the underlying object and the ownership flag
    void _tied_object (T *obj, ::CORBA::Boolean release = true);
    /// do we own it
    ::CORBA::Boolean _is_owner (void);
    /// set the ownership

    void _is_owner ( ::CORBA::Boolean b);
    // overridden ServantBase operations
    PortableServer::POA_ptr _default_POA (void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    char * symbol (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    char * full_name (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    ::CORBA::Double price (
      void);
  
  private:
    T *ptr_;
    PortableServer::POA_var poa_;
    ::CORBA::Boolean rel_;

    // copy and assignment are not allowed
    Stock_tie (const Stock_tie &);
    void operator= (const Stock_tie &);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_interface/tie_sh.cpp:74

  // TIE class: Refer to CORBA v2.2, Section 20.34.4
  template <class T>
  class  Modify_Stock_tie : public Modify_Stock
  {
  public:
    /// the T& ctor
    Modify_Stock_tie (T &t);
    /// ctor taking a POA
    Modify_Stock_tie (T &t, PortableServer::POA_ptr poa);
    /// ctor taking pointer and an ownership flag
    Modify_Stock_tie (T *tp, ::CORBA::Boolean release = true);
    /// ctor with T*, ownership flag and a POA
    Modify_Stock_tie (
        T *tp,
        PortableServer::POA_ptr poa,
        ::CORBA::Boolean release = true
      );
    /// dtor

    ~Modify_Stock_tie (void);
    // TIE specific functions
    /// return the underlying object
    T *_tied_object (void);
    /// set the underlying object
    void _tied_object (T &obj);
    /// set the underlying object and the ownership flag
    void _tied_object (T *obj, ::CORBA::Boolean release = true);
    /// do we own it
    ::CORBA::Boolean _is_owner (void);
    /// set the ownership

    void _is_owner ( ::CORBA::Boolean b);
    // overridden ServantBase operations
    PortableServer::POA_ptr _default_POA (void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    char * symbol (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    char * full_name (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    ::CORBA::Double price (
      void);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/tie_sh.cpp:54

    void set_price (
      ::CORBA::Double);
  
  private:
    T *ptr_;
    PortableServer::POA_var poa_;
    ::CORBA::Boolean rel_;

    // copy and assignment are not allowed
    Modify_Stock_tie (const Modify_Stock_tie &);
    void operator= (const Modify_Stock_tie &);
  };
} // module Quoter

// TAO_IDL - Generated from
// be/be_codegen.cpp:1847


#if defined (ACE_TEMPLATES_REQUIRE_SOURCE)
#include "QuoterS_T.cpp"
#endif /* defined REQUIRED SOURCE */

#if defined (ACE_TEMPLATES_REQUIRE_PRAGMA)
#pragma implementation ("QuoterS_T.cpp")
#endif /* defined REQUIRED PRAGMA */

#include /**/ "ace/post.h"
#endif /* ifndef */

