/*
 *  C file generated by XFaceMaker Version 4.1.
 *  Do not remove this comment.
 *  Timestamp:           1157450176
 */

/*
 *  XFaceMaker 4.0  Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin user ##*/
#include <time.h>
#include <langinfo.h>

struct tm *thetime;
time_t timer;

void Doit(Widget, XtPointer, XtPointer);

Widget months[12];

char dateCommand[] = "echo %s";

/*## end user ##*/

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' setDate  ##*/
int dy;
int yr;
int mn;
int hr;
int mi;
/*## end `active_values' setDate  ##*/

/*## begin user ##*/

void Doit(Widget w, XtPointer client_data, XtPointer data)
{
  char buffer[80];
  char date[32];

  sprintf(date, "%02d%02d%02d%02d%02d", (mn + 1), dy, 
	  hr, mi, yr - (100 * (yr / 100)));
  sprintf(buffer, dateCommand, date);
  system(buffer);

}
/*## end user ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' getMonths  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
XmStringTable getMonths()
#else
XmStringTable getMonths()

#endif
{
/*## begin user  ##*/
  months[0]  = XmStringCreate(nl_langinfo(MON_1), XmSTRING_DEFAULT_CHARSET);
  months[1]  = XmStringCreate(nl_langinfo(MON_2), XmSTRING_DEFAULT_CHARSET);
  months[2]  = XmStringCreate(nl_langinfo(MON_3), XmSTRING_DEFAULT_CHARSET);
  months[3]  = XmStringCreate(nl_langinfo(MON_4), XmSTRING_DEFAULT_CHARSET);
  months[4]  = XmStringCreate(nl_langinfo(MON_5), XmSTRING_DEFAULT_CHARSET);
  months[5]  = XmStringCreate(nl_langinfo(MON_6), XmSTRING_DEFAULT_CHARSET);
  months[6]  = XmStringCreate(nl_langinfo(MON_7), XmSTRING_DEFAULT_CHARSET);
  months[7]  = XmStringCreate(nl_langinfo(MON_8), XmSTRING_DEFAULT_CHARSET);
  months[8]  = XmStringCreate(nl_langinfo(MON_9), XmSTRING_DEFAULT_CHARSET);
  months[9]  = XmStringCreate(nl_langinfo(MON_10), XmSTRING_DEFAULT_CHARSET);
  months[10]  = XmStringCreate(nl_langinfo(MON_11), XmSTRING_DEFAULT_CHARSET);
  months[11]  = XmStringCreate(nl_langinfo(MON_12), XmSTRING_DEFAULT_CHARSET);

return (months);
/*## end user  ##*/
}
/*## end `function' getMonths  ##*/
/*## begin `function' getMonth  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
int getMonth()
#else
int getMonth()

#endif
{
/*## begin user  ##*/
 return (mn);
/*## end user  ##*/
}
/*## end `function' getMonth  ##*/
/*## begin `function' fctTime  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
XtArgVal fctTime(Widget w)
#else
XtArgVal fctTime(w)
Widget w;
#endif
{
/*## begin user  ##*/
  time(&timer);
  thetime = localtime(&timer);
  dy = thetime -> tm_mday;
  yr = thetime -> tm_year + 1900;
  mn = thetime -> tm_mon;
  hr = thetime -> tm_hour;
  mi = thetime -> tm_min;

  FmSetActiveValue(w, "dy");
  FmSetActiveValue(w, "yr");
  FmSetActiveValue(w, "mn");
  FmSetActiveValue(w, "hr");
  FmSetActiveValue(w, "mi");
/*## end user  ##*/
}
/*## end `function' fctTime  ##*/
/*## begin `function' getminute  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
int getminute()
#else
int getminute()

#endif
{
/*## begin user  ##*/
return (mi);
/*## end user  ##*/
}
/*## end `function' getminute  ##*/
/*## begin `function' getDay  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
int getDay()
#else
int getDay()

#endif
{
/*## begin user  ##*/
return (dy);
/*## end user  ##*/
}
/*## end `function' getDay  ##*/
/*## begin `function' getHour  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
int getHour()
#else
int getHour()

#endif
{
/*## begin user  ##*/
return(hr);
/*## end user  ##*/
}
/*## end `function' getHour  ##*/
/*## begin `function' getyear  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
int getyear()
#else
int getyear()

#endif
{
/*## begin user  ##*/
return(yr);
/*## end user  ##*/
}
/*## end `function' getyear  ##*/
