/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1232446001
 */

/*
 *  XFaceMaker 3.5 Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' PAdd  ##*/
/*## begin user  ##*/
int PSum;
/*## end user  ##*/
#if NeedFunctionPrototypes
int PAdd(int num)
#else
int PAdd(num)
int num;
#endif
{
/*## begin user  ##*/
	PSum += num;
	return(PSum);
/*## end user  ##*/
}
/*## end `function' PAdd  ##*/
/*## begin `function' PStart  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void PStart()
#else
void PStart()

#endif
{
/*## begin user  ##*/
	PSum = 0;
/*## end user  ##*/
}
/*## end `function' PStart  ##*/
