/*
 *  C file generated by XFaceMaker Version 5.2.
 *  Do not remove this comment.
 *  Timestamp:           1233248165
 */

/*
 *  XFaceMaker 3.5 Application Functions Definitions.
 */

#ifndef STANDALONE
#include <Fm.h>
#endif

/*## begin pattern `active_values' ##*/
/*## $$AVTYPES AVNAMES;$\n$ ##*/
/*## end pattern `active_values' ##*/
/*## begin `active_values' AdderAv  ##*/
int PSum;
int PNumber;
/*## end `active_values' AdderAv  ##*/

/*## begin pattern `function' [ ! defined NAMESPACE && ! (CNAME } "::") ] ##*/
/*## begin user ##*/
/*## end user ##*/
/*## #if NeedFunctionPrototypes ##*/
/*## CTYPE CNAME($$CARGTYPES ARGNAMES$, $) ##*/
/*## #else ##*/
/*## CTYPE CNAME($$ARGNAMES$, $) ##*/
/*## $$CARGTYPES ARGNAMES;$\n$ ##*/
/*## #endif ##*/
/*## { ##*/
/*## begin user ##*/
/*## end user ##*/
/*## } ##*/
/*## end pattern `function' ##*/
/*## begin `function' PAdd  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void PAdd()
#else
void PAdd()

#endif
{
/*## begin user  ##*/
	FmGetActiveValue(NULL, "PSum");
	FmGetActiveValue(NULL, "PNumber");
	PSum += PNumber;
	FmSetActiveValue(NULL, "PSum");
/*## end user  ##*/
}
/*## end `function' PAdd  ##*/
/*## begin `function' PStart  ##*/
/*## begin user  ##*/
/*## end user  ##*/
#if NeedFunctionPrototypes
void PStart()
#else
void PStart()

#endif
{
/*## begin user  ##*/
	PNumber = 0;
	PSum    = 0;
	FmSetActiveValue(NULL, "PSum");
	FmSetActiveValue(NULL, "PNumber");
/*## end user  ##*/
}
/*## end `function' PStart  ##*/
